### ISSUE TITLE
Missing migrations.

### ISSUE THREAD

**Issue by mainameiz** [rpush/rpush#102]
After upgrading to 2.x from 1.x I found that "rpush_apps.type" column must be changed from "Rpush::Apns::App" to "Rpush::Client::ActiveRecord::Apns::App" and so on for other services.

Are you planning to add some sort of Upgrade Guide for 1.x -> 2.x versions? It sould be great!

**Comment by damoomad** [comment]
I also went from 1.0.0 to 2.3.2 (latest) and experienced some inconsistencies with the generated migrations. I'd previously implemented the details in the above wiki so everything had moved to rpush from rapns. After bundle update I ran 'rpush init' but when running the migrations I get error 'rapns_feedback' doesn't exists etc... (obviously because it's been renamed). Do you know which migrations I can safely remove and will I have to recreate the existing apps due to some of the column name changes?

**Comment by ileitch** [comment]
@damoomad What is your output from `ls db/migrate | grep -e rpush -e rapns` ?

**Comment by damoomad** [comment]
Grep before the update:

20120810063059_create_rapns_notifications.rb
20120810063100_create_rapns_feedback.rb
20120810063101_add_alert_is_json_to_rapns_notifications.rb
20120810063102_add_app_to_rapns.rb
20120810063103_create_rapns_apps.rb
20140408145838_rename_rapns_to_rpush.rb
20140408145839_add_fail_after_to_rpush_notifications.rb

after bundle update and rpush init:

1. i say yes to overwriting config?
2. i say yes to Install ActiveRecord migrations?

I get this from the output after saying yes to migrations:

      create  db/migrate/20150209172654_create_rapns_feedback.rb
      remove  db/migrate/20120810063101_add_alert_is_json_to_rapns_notifications.rb
      create  db/migrate/20150209172655_add_alert_is_json_to_rapns_notifications.rb
      remove  db/migrate/20120810063102_add_app_to_rapns.rb
      create  db/migrate/20150209172656_add_app_to_rapns.rb
      remove  db/migrate/20120810063103_create_rapns_apps.rb
      create  db/migrate/20150209172657_create_rapns_apps.rb
      remove  db/migrate/20140408145835_add_gcm.rb
      create  db/migrate/20150209172658_add_gcm.rb
      remove  db/migrate/20140408145836_add_wpns.rb
      create  db/migrate/20150209172659_add_wpns.rb
      remove  db/migrate/20140408145837_add_adm.rb
      create  db/migrate/20150209172700_add_adm.rb
      remove  db/migrate/20140408145838_rename_rapns_to_rpush.rb
      create  db/migrate/20150209172701_rename_rapns_to_rpush.rb
      remove  db/migrate/20140408145839_add_fail_after_to_rpush_notifications.rb
      create  db/migrate/20150209172702_add_fail_after_to_rpush_notifications.rb
      create  db/migrate/20150209172703_rpush_2_0_0_updates.rb
      create  db/migrate/20150209172704_rpush_2_1_0_updates.rb

I get this from grep you sent me above:

20120810063059_create_rapns_notifications.rb
20150209172654_create_rapns_feedback.rb
20150209172655_add_alert_is_json_to_rapns_notifications.rb
20150209172656_add_app_to_rapns.rb
20150209172657_create_rapns_apps.rb
20150209172701_rename_rapns_to_rpush.rb
20150209172702_add_fail_after_to_rpush_notifications.rb
20150209172703_rpush_2_0_0_updates.rb
20150209172704_rpush_2_1_0_updates.rb

which fails when I run rake db:migrate with:

==  CreateRapnsFeedback: migrating ============================================
-- create_table(:rapns_feedback)
   -> 0.0177s
-- add_index(:rapns_feedback, :device_token)
   -> 0.0047s
==  CreateRapnsFeedback: migrated (0.0228s) ===================================

==  AddAlertIsJsonToRapnsNotifications: migrating =============================
-- add_column(:rapns_notifications, :alert_is_json, :boolean, {:null=>true, :default=>false})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::Error: ERROR:  relation "rapns_notifications" does not exist

As I said above rapns_notifications is now called rpush_notifications as I'd previously done the rename schema after upgrading to version 1.0.0 from an old version I was running in 2012.. thanks for any help :)

**Comment by ileitch** [comment]
@damoomad You were bitten by bug #91. You need to rename some of those migrations so that the timestamp matches what they used to be.

```
mv db/migrate/20150209172655_add_alert_is_json_to_rapns_notifications.rb db/migrate/20120810063101_add_alert_is_json_to_rapns_notifications.rb      
mv db/migrate/20150209172656_add_app_to_rapns.rb db/migrate/20120810063102_add_app_to_rapns.rb
mv db/migrate/20150209172657_create_rapns_apps.rb db/migrate/20120810063103_create_rapns_apps.rb  
mv db/migrate/20150209172658_add_gcm.rb db/migrate/20140408145835_add_gcm.rb
mv db/migrate/20150209172659_add_wpns.rb db/migrate/20140408145836_add_wpns.rb
mv db/migrate/20150209172700_add_adm.rb db/migrate/20140408145837_add_adm.rb
mv db/migrate/20150209172701_rename_rapns_to_rpush.rb db/migrate/20140408145838_rename_rapns_to_rpush.rb
mv db/migrate/20150209172702_add_fail_after_to_rpush_notifications.rb db/migrate/20140408145839_add_fail_after_to_rpush_notifications.rb
```
