### ISSUE TITLE
APNS Disconnect. May be a invalid certificate?

### ISSUE THREAD

**Issue by ericchernuka** [rpush/rpush#103]
I've been seeing my logs riddled with error_descriptions of "The APNs disconnected without returning an error. This may indicate you are using an invalid certificate."  I'm not quite sure why its saying its invalid since the cert expires August 2015.  Anyone have any ideas why this might be happening?

**Comment by ileitch** [comment]
I've just released `2.3.0.rc1`, can you please give it a try?

**Comment by ileitch** [comment]
Please try `2.3.1` and open a new issue if you have problems.
