### ISSUE TITLE
APNS: RPush thinks everything is okay, notification gets marked as delivered, but nothing arrives on phone

### ISSUE THREAD

**Issue by maxhollmann** [rpush/rpush#113]
I set up an app with production environment, took a production device token and sent a couple of notifications via Rpush. Everything seems to be okay, the notification gets marked as delivered, the log only shows "id sent to token". But nothing happens. Nothing arrives on the phone. Feedback is empty, too.

The exact same setup with the pushmeup gem works, the push arrives within a second of sending it out.

I have no clue, any ideas what this could be?

**Comment by ileitch** [comment]
I've just released `2.3.0.rc1`, can you please give it a try?

**Comment by ileitch** [comment]
@maxhollmann any update?

**Comment by dc85** [comment]
I also noticed this problem, not sure when it started. But the strange thing is, I have a few different way of creating push notifications, one of these ways I can confirm still work, but the other ways seems to be failing.

I run a daemon to send out the push notifications once they're created.


Failing case
=======================
n = Rpush::Apns::Notification.new
n.app = Rpush::Apns::App.find_by_name("my_app_name")
n.device_token = push_token
n.alert = content.truncate(45)
n.badge = push_counter
n.sound = "default"
n.deliver_after = created_at if created_at != nil
n.data = {
              :cat => category,
              :act => action,
              :oid => org_id,
              :src => source,
              :sid => source_id,
              :sdr => sender,
              :rpt => recipient
}
n.save!

Success case
==================
n = Rpush::Apns::Notification.new
    n.app = Rpush::Apns::App.find_by_name("my_app_name")
    n.device_token = push_token
    n.alert = message.truncate(50)
    n.badge = push_counter
    n.sound = "default"
    n.data = {
      :cat => cat,
      :oid => oid,
      :sid => sid,
      :sdr => sdr,
      :chd => chd
    }
    n.save!

This is the only difference in my whole process as far as I can remember.

I updated to 2.3.1 and it is still failing for the fail case

**Comment by ileitch** [comment]
So even in the failing case the notification gets marked as delivered?

**Comment by dc85** [comment]
Yup,

Also, a different section of my code, which uses the same function to send out the push as the failed case, is succeeding,

Its mind boggling what is happening. everything gets marked as sent but nothing actually is seen on the phone for the failed case.

**Comment by ileitch** [comment]
Does it fail if you use the same device token for both workflows?

**Comment by dc85** [comment]
All my test was done under the same devices

All the iOS devices will register as sent, but the notification will not show up for that specific fail case

I then hard coded both workflows with dummy data and the same id, they were both marked as success and the device received both pushes.

**Comment by ileitch** [comment]
OK, something particular to the data is likely causing an issue. 

* What's the difference in `n.payload.bytesize` between both workflows?
* Does the failing workflow still fail with `n. deliver_after = nil`?

**Comment by dc85** [comment]
302 |     1 | 3aee71e22b54ff2f4a61f5c45c006d20712bd3e0e7eed183d3b26fb7d907d0c3 | default | Kk3 Liu: Hff                                        | {"cat":"chat","oid":1,"sid":224,"sdr":"Kk3 Liu","chd":"3e3041a4d10cda89ee599a2408450085"}                                |  86400 | t         | 2015-01-27 22:03:04.55387  | f      |                            |            |                                                                                                           |               | 2015-01-27 22:03:01.766269 | 2015-01-27 22:03:01.766269 | f             | Rpush::Client::ActiveRecord::Apns::Notification |              | f                |                  |      5 |       0 |     |            | f          |          |          | 
 301 |     2 | 3aee71e22b54ff2f4a61f5c45c006d20712bd3e0e7eed183d3b26fb7d907d0c3 | default | Announcement: test announce                         | {"cat":"open_detail","act":"announcement","oid":1,"src":4,"sid":971,"sdr":"Coffee Developers","rpt":"Coffee Developers"} |  86400 | t         | 2015-01-27 21:59:24.28191  | f      |                            |            |                                                                                                           |               | 2015-01-27 21:59:21.578421 | 2015-01-27 21:59:21.578421 | f             | Rpush::Client::ActiveRecord::Apns::Notification |              | f                |                  |      5 |       0 |     |            | f          |          |          |

**Comment by dc85** [comment]
the above is the two rows I tested recently, 302 is the success case,

301 failed

**Comment by ileitch** [comment]
@dc85 I just tried using the same data as 301 however I'm unable to reproduce.

**Comment by nancy134** [comment]
I am seeing the same issue with any of the 2.3.x releases.  I am sending notifications to Windows Phone.  When I downgrade to 2.2.0, everything works fine.  I am issuing the following commands in the console:

app = Rpush::Wpns::App.new
app.name = "windows_phone_app"
app.connections = 1
app.save!
n = Rpush::Wpns::Notification.new
n.app = Rpush::Wpns::App.find_by_name("windows_phone_app")
n.uri = "http://..."  <== This is a valid Uri that I haven't shown here
n.data = {title:"MyApp", body:"Hello world", param:"user_param1"}
n.save!
Rpush.push

For 2.2.0 I do n.alert = "xx" instead of n.data = ...

I noticed with the 2.3.x releases, I just see "=> {}" after I execute the Rpush.push command rather than a series of SQL commands that I see in the 2.2.0 version.

Let me know what I can supply to help you debug the issue.

**Comment by ileitch** [comment]
@nancy134 what version of Ruby are you using? Is the notification being marked as delivered?

By the way, seeing `=> {}` is expected. In 2.3 you wont see SQL queries in the console, you need to look at `tmp/rpush.log` instead.

**Comment by nancy134** [comment]
Ruby version is 2.0.0p598.  I will run the test again and check to see if the notification is being marked as delivered.

**Comment by nancy134** [comment]
Here is the Notification record using Rpush 2.3.2 when the message never arrives to the phone:

id: 1, 
badge: nil, 
device_token: nil, 
sound: "default", 
alert: nil, 
data: "{\"title\":\"MyApp\",\"body\":\"Hello World\",\"param\":\"use...", 
expiry: 86400, 
delivered: true, 
delivered_at: "2015-02-03 13:19:53", 
failed: false, 
failed_at: nil,
error_code: nil, 
error_description: nil, 
deliver_after: nil, 
created_at: "2015-02-03 13:17:27", 
updated_at: "2015-02-03 13:17:27", 
alert_is_json: false, 
type:"Rpush::Client::ActiveRecord::Wpns::Notification", 
collapse_key: nil, 
delay_while_idle: false, 
registration_ids: nil, 
app_id: 1, 
retries: 0, 
uri: "http://s.notify.live.net/u/1/bn1/HmQAAADNd6BYiQZ_u...", 
fail_after: nil, 
processing: false, 
priority: nil, 
url_args: nil, 
category: nil>]>

**Comment by maxhollmann** [comment]
I updated to 2.3.2, everything works fine for me now :)

**Comment by shawnbro** [comment]
Is there any update to this issue - I am also trying to send push notifications from my production server and it is not sending anything to the device, even though it all works on my local machine.

**Comment by dc85** [comment]
There is an change in the call you make to get permission to send push notifications since iOS SDK version 8. If you updated your SDK then you might want to check into that. Could be what is causing this

**Comment by shawnbro** [comment]
Can you be any more specific about what about the permissioning has changed and how I might change the call to fix the issue?

**Comment by dc85** [comment]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
{
    //-- Set Notification
    if ([application respondsToSelector:@selector(isRegisteredForRemoteNotifications)]) 
    {
           // iOS 8 Notifications
           [application registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];

           [application registerForRemoteNotifications];
    }
    else
    {
          // iOS < 8 Notifications
          [application registerForRemoteNotificationTypes:
                     (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeAlert | UIRemoteNotificationTypeSound)];
    }

     //--- your custom code
     return YES;
}

http://stackoverflow.com/questions/24454033/registerforremotenotificationtypes-is-not-supported-in-ios-8-0-and-later

**Comment by dc85** [comment]
http://stackoverflow.com/questions/24454033/registerforremotenotificationtypes-is-not-supported-in-ios-8-0-and-later

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions
{
    //-- Set Notification
    if ([application respondsToSelector:@selector(isRegisteredForRemoteNotifications)]) 
    {
           // iOS 8 Notifications
           [application registerUserNotificationSettings:[UIUserNotificationSettings settingsForTypes:(UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge) categories:nil]];

           [application registerForRemoteNotifications];
    }
    else
    {
          // iOS < 8 Notifications
          [application registerForRemoteNotificationTypes:
                     (UIRemoteNotificationTypeBadge | UIRemoteNotificationTypeAlert | UIRemoteNotificationTypeSound)];
    }

     //--- your custom code
     return YES;
}

**Comment by istvanfazakas** [comment]
I am having the same problem with rpsuh 2.4.0 
Apns is being marked as delivered, I checked the callbacks from the config as well, but the notification is not arriving when sending to multiple devices

For 2 or 3 devices it is working just fine, but when sending to 11 for ex, the notification is not received

**Comment by jiajiawang** [comment]
@istvanfazakas Are you running rpush as a deamon (rpush start) or not?
I'm having the same problem but only if I run rpush as 'Rpush.push' or 'rpush push'.
#154

**Comment by istvanfazakas** [comment]
@jiajiawang I am not using it as a daemon, not running the rpush start command. I am pushing the notifications from code, running 'Rpush.push'. Did you manage to use it somehow and make it actually work?

**Comment by jiajiawang** [comment]
@istvanfazakas At this moment, I'm just using it as a daemon as everything works fine in this case.
Still waiting for the response why error reporting doesn't work if use 'Rpush.push' or 'rpush push'.

**Comment by istvanfazakas** [comment]
@jiajiawang Thank you for your reply

**Comment by ileitch** [comment]
@jiajiawang are you saying that only logging doesn't work with Rpush.push, or that the notification.failed attribute never becomes true?

**Comment by jiajiawang** [comment]
@ileitch The notification.failed attribute never becomes true.
Also when error happens, it seems that it just drops the connection and mark all the subsequential notification as delivered.

**Comment by ileitch** [comment]
I suspect what's happening is that when using `Rpush.push` there's only (usually) a single batch sent, the connection is closed before the APNs has a chance to respond with an error.

This isn't an issue when run as a daemon, as another batch will discover the connection as been closed and the error handling kicks in as designed.

I'll have to add an IO select on the connection for `Rpush.push` and hope we receive the error before some small timeout. Unfortunately Apple really messed up the APNs protocol when it comes to error handling.

**Comment by pdaire** [comment]
I'm having the same issue. I'm looking deeper into the problem and I think it might be related to malformed notifications. 
> If you send a notification that is malformed or otherwise unintelligible, APNs returns an error-response packet and closes the connection. Any notifications that you sent after the malformed notification using the same connection are discarded, and must be resent. 
> Apple. [source](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html)

> The simple notification format drops the connection if the push service receives a notification that is incorrect in some way. Your provider may see this as an EPIPE or broken pipe error in response to sending a notification. On the other hand, the enhanced notification format will send an error response with more detailed information about what was wrong with the notification before dropping the connection. Be sure your provider catches and handles these conditions properly.
> Apple. [source](https://developer.apple.com/library/ios/technotes/tn2265/_index.html)

I think if you have several PN in the same batch, sharing the connection and one of the notifications is malformed the APNS feedback is just an `EPIPE` error and all following notifications are discarded from being delivered, but rpush didn't receive any feedback for them.

@istvanfazakas I had the same problem because one of the many device tokens was from sandbox environment so rpush doesn't find any problem but APNS rejected it a closes the connection.
What do you think of the theory @ileitch ?

**Comment by ileitch** [comment]
@pdaire There's a fix for this in master, can you give it a try?

**Comment by pdaire** [comment]
@ileitch ok, I'll try it tomorrow.
what's the expected behaviour of this fix? to collect feedback? to mark as failed each non-delivered notification?

**Comment by pdaire** [comment]
@ileitch it worked fine for me. marking the error code and retrying :smile: 
 but the feedback is not been captured. How do coexist the feedback mirror and the feedback checking? which are the advantages of using one or another?

**Comment by kwojtaszek** [comment]
@ileitch I have the same problem  with mongoid backend. In my case I'm running daemon and it looks like it never delivers notification to certain devices.

**Comment by masahirominami** [comment]
we are having similar problems.
1) certain devices are not receiving notifications at all
2) once in a day or so, notifications are not delivered for some time (hours) then delivered. 
3) also some notifications are marked "delivered" but never reach devices.

our environment and configurations are:
- rpush 2.5.0/ruby 2.0.0p598
- rpush running as daemon
- connections : 3 (for both APNs and GCM )
- batch_size: 100 (default)
- our rpush is serving for 2 apps, both APNs and GCM, therefore 12 dispatchers running

in case of 2), if i do "bundle exec rpush push" from command line, the stacked notifications seem to get delivered. after that the daemon seems to work ok for a while, but falls back to 2) or 3) again after some time.

**Comment by avitus** [comment]
I am testing in the sandbox/dev environment and am having a very similar problem to @masahirominami.

Environment:

ruby 2.1.5p273
rpush 2.6
iOS 9
(All other settings are default as per the tutorial on rpush/rpush page.)

I had 3 notifications that were delivered=true, failed=false after running the daemon. I shut down the daemon, added another notification in the Rails console, and then ran "bundle exec rpush push". 

Two notifications arrived at my phone (first two ever, yay!).

**Comment by masahirominami** [comment]
hi, @avitus, an update from our case:
we set connections to 1 for all the applications (so 2 apps x 2 platforms, 4 dispatchers at work) and running rpush for about a week.

result seems stable so far, however we are not sure as we are not intensively testin at this point.

another thing to note may be:
we added code to eliminate duplicated device tokens and registration ids. as we been testing reinstalling our app caused duplicate device tokens which resulted in delivering multiple pushes to one device.

we have no idea if this caused the notification failure though.

any feedback will be appreciated, thank you.

**Comment by boyfunky** [comment]
Are there any documentations regarding the data field of the Push  Notification message i mean n.data { }. what does it mean? 

I seem to be having the same issue as well 

This is my code 
    

> n = Rpush::Apns::Notification.new
>     n.app = Rpush::Apns::App.find_by_name("Loanstreet Partners")
>     n.device_token = @user_auth_token.device_token # 64-character hex string
>     n.alert = "New Case Submission: " + la.case_code
>     n.data = { foo: :bar }
>     n.badge = 1
>     n.save!
> 
>     Rpush.push
>     Rpush.apns_feedback

In my rpush_notifications table, i see the notification created but in my rpush_feedback it is empty. not sure why it doesn't get sent. Anyone has a clue?

I don't get any error or anything as well. So I'm sort of confused.

**Comment by aried3r** [comment]
Here you can see what the `data` attribute does. https://github.com/rpush/rpush/blob/master/spec/unit/client/active_record/apns/notification_spec.rb#L94-L105

It's the custom payload you can give a notification.

**Comment by mpospelov** [comment]
I met same issue and figure out what happens. When you send incorrectly encoded payload APNS do not notify about that, so these notifications handled as successful. In my case it was happened because of using `oj` gem.

The payload sent to APNS was looks like
```
"{\"^o\":\"ActiveSupport::OrderedHash\",\"self\":{\"aps\":{\"^o\":\"ActiveSupport::OrderedHash\",\"self\":{\"alert\":\"test 1234\",\"sound\":\"default\"}}}}"
```
but have to be
```
{\"aps\":{\"alert\":\"test 1234\",\"sound\":\"default\"}}
```

If someone met same issues just put 
```
Oj.mimic_JSON
```
on start up of your application.

Also I think we can handle the payload validation in rpush so root keys was required.

**Comment by fertobar** [comment]
I'm having same issue when I stress a little the system. Eg 100 PN very fast. and if I send same a little slow, like a micro delay is working ok. so seems not a payload or token issue for me.
The failure when I stress the system is intermittent. some PN are delivered and other missing.
Apple said in theory a rate of 9000 per second without retry.



All PNs I'm sending are independent, for different devices, with many workers in parallel.
checking logs I see all as **successful delivered**, but some users never got the PN.

Do you know if in the practice there are other rate limit?

I'm using Redis, Rails 4 and rpush 3.0
