### ISSUE TITLE
Ruby 2.2.0 - GCM delivery failed

### ISSUE THREAD

**Issue by jiajiawang** [rpush/rpush#116]
GCM failed after upgrade ruby from 2.1.x to 2.2.0.

[2015-01-05 12:35:53] [ERROR] Rpush::DeliveryError, Unable to deliver notification 660, received error (Failed to deliver to recipients . Errors: .)
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:87:in `handle_failures'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:54:in `ok'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:34:in `handle_response'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:21:in `perform'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher/http.rb:12:in `dispatch'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:61:in `dispatch'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:35:in `block (2 levels) in start'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
/Users/JJ/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `block in start'

APNS is still working fine.

**Comment by ileitch** [comment]
Fix in master here https://github.com/rpush/rpush/commit/634a507ad9ccfe5ad0305aef2451386dce86c08a. I'll be releasing 2.3.0 is the next few days.

**Comment by jiajiawang** [comment]
Great!
Thanks for a quick response.
