### ISSUE TITLE
GCM notifications stuck as "processing" 

### ISSUE THREAD

**Issue by chrise86** [rpush/rpush#120]
APN notifications are sending fine, but for some reason GCM notifications all get marked as processing, and never get marked as delivered.

No errors, no retries, it doesn't even seem to hit the rpush logs.

Am I missing something? Maybe a startup command? I'm currently running rpush as a daemon. Using latest version, direct from master branch.

**Comment by chrise86** [comment]
Scratch that, must have been a server related issue as stopping and restarting a couple times seems to have fixed it...

**Comment by soulfly** [comment]
I see the same but with both APNS and GCM pushes

do you have any ideas why it can stuck as "processing"? what's the reason?
