### ISSUE TITLE
issue with rpush => 2.1.0

### ISSUE THREAD

**Issue by alihabib-tp** [rpush/rpush#121]
I'm having issue with rpush => 2.1.0 as follows: 
( =< 2.0.0 doesn't show any errors)

/home/ali/.rvm/rubies/ruby-1.9.3-p545/bin/ruby /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/bin/passenger start -a 0.0.0.0 -p 3000 --max-pool-size 1 --spawn-method conservative -e development
=============== Phusion Passenger Standalone web server started ===============
PID file: /home/ali/rubyProjects/ati/hitch_web/tmp/pids/passenger.3000.pid
Log file: /home/ali/rubyProjects/ati/hitch_web/log/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#troubleshooting
===============================================================================
App 18227 stdout: 
App 18227 stdout: 
[ 2015-01-26 15:44:14.6500 18189/7fbc747f6700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /home/ali/rubyProjects/ati/hitch_web: An error occured while starting the web application.
  Error ID: a4afdfe7
  Error details saved to: /tmp/passenger-error-74bpHd.html
  Message from application: undefined method `option' for Rpush::CLI:Class (NoMethodError)
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.1.0/lib/rpush/cli.rb:21:in `<class:CLI>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.1.0/lib/rpush/cli.rb:7:in `<module:Rpush>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.1.0/lib/rpush/cli.rb:6:in `<top (required)>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `block in require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.1.0/lib/rpush.rb:16:in `<top (required)>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
  /home/ali/rubyProjects/ati/hitch_web/config/application.rb:7:in `<top (required)>'
  /home/ali/rubyProjects/ati/hitch_web/config/environment.rb:2:in `require'
  /home/ali/rubyProjects/ati/hitch_web/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:108:in `eval'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:108:in `load_app'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:127:in `<module:App>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:27:in `<module:PhusionPassenger>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:26:in `<main>'

[ 2015-01-26 15:44:14.6551 18189/7fbc726d1700 agents/HelperAgent/RequestHandler.h:2306 ]: [Client 20] Cannot checkout session because a spawning error occurred. The identifier of the error is a4afdfe7. Please see earlier logs for details about the error.

**Comment by ileitch** [comment]
Please try `2.3.1` and report back.

**Comment by alihabib-tp** [comment]
Hi Ian,

Thor installed is : thor-0.14.6
here's log for 2.3.1, I had tried it before (but failed) hence I moved to previous version(s).



/home/ali/.rvm/rubies/ruby-1.9.3-p545/bin/ruby /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/bin/passenger start -a 0.0.0.0 -p 3000 --max-pool-size 1 --spawn-method conservative -e development
=============== Phusion Passenger Standalone web server started ===============
PID file: /home/ali/rubyProjects/ati/hitch_web/tmp/pids/passenger.3000.pid
Log file: /home/ali/rubyProjects/ati/hitch_web/log/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#troubleshooting
===============================================================================
App 4612 stdout: 
App 4612 stdout: 
[ 2015-01-27 10:30:55.6363 4575/7f6845dba700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /home/ali/rubyProjects/ati/hitch_web: An error occured while starting the web application.
  Error ID: 06a2fed0
  Error details saved to: /tmp/passenger-error-A5vF7U.html
  Message from application: undefined method `option' for Rpush::CLI:Class (NoMethodError)
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.3.1/lib/rpush/cli.rb:19:in `<class:CLI>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.3.1/lib/rpush/cli.rb:7:in `<module:Rpush>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.3.1/lib/rpush/cli.rb:6:in `<top (required)>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `block in require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:236:in `load_dependency'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rpush-2.3.1/lib/rpush.rb:16:in `<top (required)>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
  /home/ali/rubyProjects/ati/hitch_web/config/application.rb:7:in `<top (required)>'
  /home/ali/rubyProjects/ati/hitch_web/config/environment.rb:2:in `require'
  /home/ali/rubyProjects/ati/hitch_web/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:108:in `eval'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:108:in `load_app'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:127:in `<module:App>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:27:in `<module:PhusionPassenger>'
  /home/ali/.rvm/gems/ruby-1.9.3-p545@dctc/gems/passenger-4.0.57/helper-scripts/rack-loader.rb:26:in `<main>'


[ 2015-01-27 10:30:55.6620 4575/7f68377fe700 agents/HelperAgent/RequestHandler.h:2306 ]: [Client 20] Cannot checkout session because a spawning error occurred. The identifier of the error is 06a2fed0. Please see earlier logs for details about the error.

**Comment by alihabib-tp** [comment]
Ok thanks

Please update docs on : https://rubygems.org/gems/rpush

Runtime Dependencies:
activesupport >= 0 ansi >= 0 multi_json ~> 1.0 net-http-persistent >= 0 railties >= 0 thor >= 0

**Comment by ileitch** [comment]
That'll happen automatically when I make a new release.
