### ISSUE TITLE
Redis: Ability to query notifications by device token

### ISSUE THREAD

**Issue by paulwalker** [rpush/rpush#123]
I guess this would require storage of an additional key, value set?

**Comment by ileitch** [comment]
After the `Rpush.configure` block, add:

```ruby
class Rpush::Client::Redis::Apns::Notification
  index :device_token
end
```

You can now do: `Rpush::Apns::Notification.where(device_token: 'abc123...')`

A word of warning though, [Modis](https://github.com/ileitch/modis) indexes are not terribly efficient. Their only intended use case is for finding an App by its name, of which there are likely very few. You'll probably therefore want to keep an eye on how many indexes there are, and how large they get. You can get the key for an index with `Rpush::Client::Redis::Apns::Notification.index_key(:device_token, 'abc123...')`

**Comment by ileitch** [comment]
Please open a new issue if you need further assistance with this.

**Comment by paulwalker** [comment]
Thanks for the previous answer.
