### ISSUE TITLE
Problem sending Gcm notifications.

### ISSUE THREAD

**Issue by matiaslina** [rpush/rpush#126]
Hello,

Here's the situation, I create a gcm notification like this:

```ruby
n = Rpush::Gcm::Notification.new
n.app = Rpush::Gcm::App.find_by_name("android_app")
n.registration_ids = ["first-token", "second-token"]
n.data = { message: "hi mom!" }
n.save!
```

With the `first-token` being a valid token, and `second-token` a not registered token, the notification will fail saying *Unable to deliver notification 5062, received error (Failed to deliver to recipients 2. Errors: NotRegistered.)* and it will not send the notification to the first **valid** token.

My question is, this is something that rpush have to handle? or I've to handle it somewhere in my application?

Greetings

**Comment by ileitch** [comment]
`Unable to deliver notification 5062, received error (Failed to deliver to recipients 2. Errors: NotRegistered.)` This error indicates that only the notification at `n.registration_ids[2]` failed. This doesn't match up with your example though, your `registration_ids` does not contain 3 tokens.

Have you confirmed that the notification is not received on the device? Or is it the confusing error message?

**Comment by matiaslina** [comment]
Sorry for the example @ileitch, was just a copy/paste of the code for creating a new android notification and one error on my logs. That was just to show the error on the logs.

I've done some testings today. Seems like I can't reproduce it anymore :disappointed:. It's working as it should, although this was a problem that I had some days ago.

I'll close this issue and if I can reproduce it again, I'll open it again.
