### ISSUE TITLE
IOError for apns_tcp loops forever

### ISSUE THREAD

**Issue by gsusmonzon** [rpush/rpush#128]
Hello

My system is running Rpush on Linux (ubuntu 14.04) with Ruby 2.1.2

I have experienced a weird behaviour in newer version of Rpush , regarding to `Dispatcher::ApnsTcp`. 
Sometimes, randomly (probably when the other end decides to close the connection), my server runs out of space because **rpush loops forever** at these lines: (It could take days to reproduce the failure again)

    [2015-02-11 20:03:16] [ERROR] IOError, closed stream
    ../rpush-2.3.1/lib/rpush/daemon/tcp_connection.rb:65:in `select'
    ../rpush-2.3.1/lib/rpush/daemon/tcp_connection.rb:65:in `select'
    ../rpush-2.3.1/lib/rpush/daemon/dispatcher/apns_tcp.rb:65:in `check_for_error'
    ../rpush-2.3.1/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver'
    [2015-02-11 20:03:16] [ERROR] IOError, closed stream
    ../rpush-2.3.1/lib/rpush/daemon/tcp_connection.rb:65:in `select'
    ../rpush-2.3.1/lib/rpush/daemon/tcp_connection.rb:65:in `select'
    ../rpush-2.3.1/lib/rpush/daemon/dispatcher/apns_tcp.rb:65:in `check_for_error'
    ../rpush-2.3.1/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver' 
    [2015-02-11 20:03:16] [ERROR] IOError, closed stream
    ../rpush-2.3.1/lib/rpush/daemon/tcp_connection.rb:65:in `select'
    ../rpush-2.3.1/lib/rpush/daemon/tcp_connection.rb:65:in `select'
    ../rpush-2.3.1/lib/rpush/daemon/dispatcher/apns_tcp.rb:65:in `check_for_error'
    ../rpush-2.3.1/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver' 

(Note that it is happening w the latest rpush 2.3.2 version as well, but the only logs I have are for the old version. The code in rpush has not changed for this section)

Starting from commit b4d04435e67e04a813783e693dc70e34f609e1cb `apns_tcp` is rescueing `StandardError` and so the `IOError` is catched as well (line ~73). So, the Thread would loop forever, instead of trying to reconnect and **the disk fills with Gb of logs in a matter of seconds**.

        def start_error_receiver
          @error_receiver_thread = Thread.new do
            check_for_error until @stop_error_receiver
            Rpush::Daemon.store.release_connection
          end
        end

As these lines were added, there must be a reason for rescueing any `StandardError`.
But with this `IOError`, **if the stream is closed we could try to reconnect** or rethrow the exception after logging the error?.

Something like

        rescue IOError => e
          log_error(e)
          @connection.reconnect
        rescue StandardError => e
          log_error(e)
        end

Makes sense?

Thanks

**Comment by ileitch** [comment]
I mistakingly assumed `IOError` inherited `SystemCallError`, my bad,

**Comment by gsusmonzon** [comment]
I had to review Exceptions inheritance tree too, :)

**Comment by xiaoronglv** [comment]
Hi Guys,

I still encounter this type of problem, although I have already used the 2.4.0 version.

## rpush runs into an infinite loop, causing the log file to fill up.

```
root@production-tiger: du -sh *
573M    bundle
38G     log
591M    pids
4.0K    system
```

The system soon are out of disk space.

## Log content

```
## 34G rpush.log
[2015-05-28 17:30:45] [ERROR] Errno::EINVAL, Invalid argument
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `sysread'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:102:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:61:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:71:in `check_for_error'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver'
[2015-05-28 17:30:45] [ERROR] Errno::EINVAL, Invalid argument
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `sysread'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `fill_rbuff'
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:102:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/tcp_connection.rb:61:in `read'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:71:in `check_for_error'
/var/www/xproject/production/shared/bundle/ruby/2.1.0/gems/rpush-2.4.0/lib/rpush/daemon/dispatcher/apns_tcp.rb:46:in `block in start_error_receiver'
[2015-05-28 17:30:45] [ERROR] Errno::EINVAL, Invalid argument
/opt/ruby-2.1.3/lib/ruby/2.1.0/openssl/buffering.rb:61:in `sysread'^C
```

I don't know how to deal with it.
