### ISSUE TITLE
Help for first run of  rpush

### ISSUE THREAD

**Issue by desmocolo** [rpush/rpush#132]
Hi,
I'm trying to implement a simple push notification server in rails 4 by using rpush.
I need to send push notification from rails server to Android apps.
I read the tutorial and i installed the gem and create the tables by migration, I don't understand where i have to write the following code:
app = Rpush::Gcm::App.new
app.name = "android_app"
app.auth_key = "..."
app.connections = 1
app.sav

n = Rpush::Gcm::Notification.new
n.app = Rpush::Gcm::App.find_by_name("android_app")
n.registration_ids = ["token", "..."]
n.data = { message: "hi mom!" }
n.save!

I searched some samples and tutorials on the web but I didn't find anything.
Someone can help me?

**Comment by ileitch** [comment]
If you're just testing, you can create your app and notification in the Rails console.

In the future, you'll likely want to create notification in response to an event, so probably triggered in an after_save hook on a model.

**Comment by desmocolo** [comment]
I would like create a scaffold to permit to an administrator to write a message and send it to the app generating a push. 
If I understood, I have to write a method in the controller that take the message parameter and to implement the piece of code like the previous message. Is correct?

**Comment by ileitch** [comment]
Yes, that's correct.
