### ISSUE TITLE
Validation Failed: Device token is invalid

### ISSUE THREAD

**Issue by shawnbro** [rpush/rpush#133]
I'm building an Ionic/ngCordova app with a rails back end - and attempting to use this gem to handle push notifications.  I've gone through the example, but when I hit "n.save!" I get the error Validation failed: Device token is invalid.

I have properly configured my certs, I believe - and have sent the device ID to the server using the $cordovaDevice.getUUID() method (http://ngcordova.com/docs/plugins/device/).  

Any idea why this would fail?  What does a correctly formatted device ID look like for APNS?

Any tips would be very helpful.

**Comment by ileitch** [comment]
The device UUID is not the same as the APNs Device Token. See here for setting up push notifications: http://ngcordova.com/docs/plugins/pushNotifications/
