### ISSUE TITLE
Running rpush as linux service

### ISSUE THREAD

**Issue by casertap** [rpush/rpush#135]
I want to start rpush using a linux service.
I have correctly created the service. It runs 13s before stopping.
It seems that the rpush process is not running after that.

/usr/local/bin/rpush
````
#!/bin/bash
cd /home/as/as-capistrano/current && bundle exec /home/as/as-capistrano/shared/bundle/ruby/2.0.0/bin/rpush start -e production
````

/lib/systemd/system/rpush.service
````
[Unit]
Description=rpush service
After=syslog.target network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/rpush

[Install]
WantedBy=multi-user.target
````

````
[as@ns bin]$ sudo systemctl start rpush.service
[as@ns bin]$ sudo systemctl status rpush.service
rpush.service - rpush service
	  Loaded: loaded (/lib/systemd/system/rpush.service; enabled)
	  Active: active (running) since Tue, 03 Mar 2015 12:31:13 +0100; 6s ago
	Main PID: 12569 (rpush)
	  CGroup: name=systemd:/system/rpush.service
		  ├ 12569 /bin/bash /usr/local/bin/rpush
		  └ 12570 ruby /home/as/as-capistrano/shared/bundle/ruby/2.0.0/bin/rpush start -e production
```
after few second
````
[as@ns bin]$ sudo systemctl status rpush.service
rpush.service - rpush service
	  Loaded: loaded (/lib/systemd/system/rpush.service; enabled)
	  Active: inactive (dead) since Tue, 03 Mar 2015 12:31:27 +0100; 56s ago
	 Process: 12569 ExecStart=/usr/local/bin/rpush (code=exited, status=0/SUCCESS)
```

**Comment by casertap** [comment]
even if the service is shutdown it works.
I think it starts a dispatched service.

**Comment by itsSaad** [comment]
for anyone else stumbled upon here. The fix or the  above script is to set `Type` to `forking`. 
see this pull request: https://github.com/rpush/rpush/pull/257
