### ISSUE TITLE
bad behavior with json notification :data field and ActiveAdmin

### ISSUE THREAD

**Issue by yoyos** [rpush/rpush#141]
Hello

I posted a bug report https://github.com/activeadmin/activeadmin/issues/3871 for a bug I thought was coming from ActiveAdmin but it seems rpush changed a default behavior on the :data field.

For example, If I totally comment out these lines in file `lib/rpush/client/active_record/notification.rb`, ActiveAdmin can display json strings correctly in its edit form like `{"foo":"bar"}` and not `{"foo"=>"bar"}` anymore : 

```
def data=(attrs)
   return unless attrs
   attrs = JSON.parse(attrs) if attrs.is_a?(String)
   fail ArgumentError, "must be a Hash" unless attrs.is_a?(Hash)
   write_attribute(:data, multi_json_dump(attrs.merge(data || {})))
end
```

Are these lines really useful ? Could you make it work with activeadmin please ? If possible, is there a way to do it without changing default behaviors if not necessary ?

Thanks !

**Comment by aried3r** [comment]
Hey! Thanks for reporting the issue! Since there haven't been any new feedback for some time I'm closing this issue. Please feel free to open a new issue if you're still experiencing this issue with the latest Rpush and ActiveAdmin release.
