### ISSUE TITLE
Single Table Inheritance apparently not working properly with Redis store

### ISSUE THREAD

**Issue by haslo** [rpush/rpush#147]
We have a similar error to #136 (and maybe #127). We're not using ActiveRecord but rather Redis for storage. The bug was not reproducible with ActiveRecord storage in sqlite3 when I tried that.
- There's the `to_binary` bug from #136 showing up for some of our notifications to Gcm. I found that it happens only when I actually have an APNs app in the storage - trying `Rpush.push` will result in the APNs path being executed and `to_binary` being called.
- Similarly, there was trouble when I tried to do `Rpush.apns_feedback` with any apps that aren't APNs apps in the storage. They'll be iterated through and will have problems with `environment` being nil.

I think that both bugs come down to this reproducible test case (I've made a new Rails app to reproduce it, with minimal gems):

https://github.com/haslo/rpush_redis_bug

Essentially, every app is in the list of all apps (including all GCM apps being in the list of APNs apps and vice versa), and every notification is in the list of all notifications (thus iterating over all GCM notifications will return plenty of APNs notifications etc.).

**Comment by antulik** [comment]
@haslo any work arounds until this is fixed?

**Comment by haslo** [comment]
@antulik I made https://github.com/ileitch/modis/pull/2 as a somewhat hacky workaround. It doesn't change the storage structure, but has a bit of a performance impact, particularly with wide STI trees.

**Comment by antulik** [comment]
@haslo thx, will give it a shot 👍

**Comment by avolkovi** [comment]
any updates on this? It's been a year and a half and the patch in modis still isn't released... we ended up working around this by patching `Rpush.apns_feedback` to use `Rpush::Apns::App.all.select { |app| app.is_a?(Rpush::Client::Redis::Apns::App) }` instead of `Rpush::Apns::App.all`

**Comment by antulik** [comment]
@avolkovi it's been a while, seems like i've given apps prefixed names like "ios_app" or "android_app" and search only by name instead of a class.

**Comment by haslo** [comment]
Should be fixed now, with 3d7f0b3a1fcfad98587be8a86d5d61b7a4cb0d19 - I did close my PR, but not the issue, and nobody else did either...

@ileitch, you wanna close this issue?

**Comment by aried3r** [comment]
Seems this was resolved, closing.
