### ISSUE TITLE
Undocumented "Registration ids can't be blank error"

### ISSUE THREAD

**Issue by vedant1811** [rpush/rpush#149]
I was getting a `Registration ids can't be blank` error when I created a GCM notification and passed in an empty array for registration IDs. and took me a while to debug this, partly because no where could I find the documentation such a behavior.

I dont know if throwing an exception in case registration IDs is empty is the desired behaviour (It wasn't for me definitely), but even if it is, it should be clearly mentioned in the readme and/or wiki.
Anyway, I would rather have rpush not do anything but just log this incident in its default logger.

I request you to to point me to other possible (the ones created in rpush) errors.

**Comment by philipgiuliani** [comment]
Its a validation error. You only got an exception because you called `.save!` and that means that the errors will raise an InvalidRecord exception. To fail silently you should call `.save` without the bang. As result you get true/false to check if it was successful. Its just ActiveRecord ;)

**Comment by vedant1811** [comment]
Yeah that is true.

But I still think that it should be documented that such validations are
being performed.

Failing silently is obviously a very bad option; if I call 'save' then I
would have to check the errors and Log them. I would love for rpush to do
this by default. But it is just me.
I still love rpush and am using it.

**Comment by ileitch** [comment]
Feel free to write a Wiki article if you like, but I'm satisfied that the validation error is sufficient. The majority of users would already know that a registration ID is required from reading Google's GCM documentation.
