### ISSUE TITLE
fatal: deadlock detected

### ISSUE THREAD

**Issue by ileitch** [rpush/rpush#15]
_Issue by **[milindphirake](https://github.com/milindphirake)** from Wednesday Jan 22, 2014 at 17:47 GMT_
_Originally opened as https://github.com/ileitch/rapns/issues/195_

---

I implemented the push notifications and GCM notifications using this gem working great.

@ileitch 

But i came across one strange issue. Sometimes my rails server goes into deadlock state.

Any Help on this will be great

I got the following log.

It cames when there is noting to push and we call "Rapns.push" 

Log= > 

Rapns::Notification Load (0.6ms)  SELECT `rapns_notifications`.\* FROM `rapns_notifications` WHERE (delivered = 0 AND failed = 0 AND (deliver_after IS NULL OR deliver_after < '2014-01-22 17:30:48')) AND (app_id IN (1,2,3,4))
 => {} 

1.9.3-p484 :005 > Rapns.push

   (0.3ms)  SELECT COUNT(_) FROM `rapns_apps` 
  Rapns::App Load (0.2ms)  SELECT `rapns_apps`._ FROM `rapns_apps` 
  Rapns::Notification Load (0.6ms)  SELECT `rapns_notifications`.\* FROM `rapns_notifications` WHERE (delivered = 0 AND failed = 0 AND (deliver_after IS NULL OR deliver_after < '2014-01-22 17:30:55')) AND (app_id IN (1,2,3,4))
**fatal: deadlock detected**
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/daemon/delivery_handler.rb:21:in `join'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/daemon/delivery_handler.rb:21:in`stop'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/daemon/app_runner.rb:81:in `map'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/daemon/app_runner.rb:81:in`stop'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/daemon/app_runner.rb:46:in `map'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/daemon/app_runner.rb:46:in`stop'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/rapns-3.3.2/lib/rapns/push.rb:15:in `push'
    from (irb):5
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.6/lib/rails/commands/console.rb:47:in`start'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.6/lib/rails/commands/console.rb:8:in `start'
    from /home/ubuntu/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.6/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
1.9.3-p484 :006 >

**Comment by xiaoronglv** [comment]
rpush 2.4.0 still have this problem.

```

*** (1) TRANSACTION:
TRANSACTION 2535007187, ACTIVE 0 sec fetching rows
mysql tables in use 1, locked 1
SELECT `rpush_notifications`.* FROM `rpush_notifications` WHERE (processing = 0 AND delivered = 0 AND failed = 0 AND (deliver_after IS NULL OR deliver_after < '2015-09-08 06:23:19')) ORDER BY created_at ASC LIMIT 100 FOR UPDATE

*** (2) TRANSACTION:
TRANSACTION 2535007188, ACTIVE 0 sec updating or deleting
mysql tables in use 1, locked 1
3 lock struct(s), heap size 1248, 2 row lock(s), undo log entries 1
UPDATE `rpush_notifications` SET processing = 0, delivered = 1, delivered_at = '2015-09-08 06:23:19' WHERE `rpush_notifications`.`id` IN (4711324, 4732115, 4711326)

```
