### ISSUE TITLE
APNS_ERRORS (New code)

### ISSUE THREAD

**Issue by henb** [rpush/rpush#150]
Hello, I love APNS: D
Today, APNS presented me a new error.

```ruby
[2015-04-28 18:02:42] [ERROR] [ios_production] Unknown error code 10. Possible Rpush bug? (10)
```

**A status code of 10 indicates that the APNs server closed the connection (for example, to perform maintenance).**

I think we need to add it in **rpush**.

**Comment by philipgiuliani** [comment]
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW3

**A status code of 10 indicates that the APNs server closed the connection (for example, to perform maintenance).**

Would be maybe nice to get a better error in rpush :+1:

**Comment by ileitch** [comment]
This is now fixed in master. I'll release a new version soon.
