### ISSUE TITLE
APNS expired certificate problem

### ISSUE THREAD

**Issue by matiaslina** [rpush/rpush#152]
An expired certificate on one apns application makes other applications (gcm and wpns included) unable to send notifications.

 I have some Gcm batch notification in a permanent 'processing' status, and the last thing that show the logs are:

```
[WARNING] [osx_superbanner_development] Certificate will expire at 2015-06-09 13:14:00 UTC.
[2015-05-10 16:22:21] [ERROR] [osx_photomontager_development] Certificate expired at 2015-05-09 17:52:10 UTC.
[2015-05-10 16:22:21] [ERROR] Rpush::CertificateExpiredError, osx_photomontager_development certificate expired at 2015-05-09 17:52:10 UTC.
```

guess is expected that we can send notifications from other apps, except from the expired app.

**Comment by ileitch** [comment]
Were the batches stuck in 'processing' crated just before this happened? I don't see how this error could effect other apps, they're all self-contained.

**Comment by aried3r** [comment]
Closing because no new reports of this have come in and a lot has happened since then in the codebase. Feel free to open a new issue if you think this is still an issue with the current Rpush release!
