### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by thepelican** [rpush/rpush#170]
Hi All,

I'm using Rpush to send android and ios notifications. I have .pem setup but im testing only CGM at the moment.  Every time I create a notification I get 

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

I have updated all my certs on the mac but I cant pass this issue.Any help?

**Comment by anpr** [comment]
I have the same problem. Could you tell me how you solved it?

**Comment by cjlucani** [comment]
Me too

**Comment by af23me** [comment]
For me problem was solved by using:
`brew update && brew upgrade openssl`

Also check with rvm:
`rvm osx-ssl-certs update all`
