### ISSUE TITLE
Send multiple ios push notification

### ISSUE THREAD

**Issue by desmocolo** [rpush/rpush#171]
Hi,
just a little precisation...
I need to send the same push notification to apns to all ios device tokens in my database.
Reading the following code:
n = Rpush::Apns::Notification.new
n.app = Rpush::Apns::App.find_by_name(params[:title])
n.device_token = iosToken.token # 64-character hex string
n.alert = params[:message]
n.data = { foo: :bar }
 n.save!

there is a method to replace n.device_token line with an array of tokens?

**Comment by ileitch** [comment]
I'm afraid not, you'll need to create a notification for each device. This is a feature I would like to add in the future though.

**Comment by elhowm** [comment]
@ileitch And three years later? Still need to push for each device? :)
