### ISSUE TITLE
Not able to start and stop rpush in production using capistrano 3

### ISSUE THREAD

**Issue by devendrabobde** [rpush/rpush#173]
Here is what I am doing,

after :finished, :restart_rpush do
  on roles(:web) do
    within release_path do
      with rails_env: fetch(:rails_env) do
        execute :bundle, :exec, "rpush stop -e #{fetch(:rails_env)}"
        execute :bundle, :exec, "rpush start -e #{fetch(:rails_env)}"
      end
    end
  end
end

It gives error "ERROR: config/rpush.rb does not exist. Please run 'rpush init' to generate it or specify the --config option."

After mentioning -c option it shows it start successfully but on server there is no such process of rpush running and when we try to stop it using rpush stop then it gives this error,
- Stopping Rpush (pid 28985)... 

//bundle/ruby/2.0.0/gems/rpush-2.4.0/lib/rpush/cli.rb:39:in `kill'
DEBUG [eebbea89]    : 
DEBUG [eebbea89]    No such process
DEBUG [eebbea89]     (
DEBUG [eebbea89]    Errno::ESRCH
DEBUG [eebbea89]    )
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/gems/rpush-2.4.0/lib/rpush/cli.rb:39:in`stop'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/gems/rpush-2.4.0/bin/rpush:4:in `<top (required)>'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/bin/rpush:23:in`load'
DEBUG [eebbea89]        from //bundle/ruby/2.0.0/bin/rpush:23:in `<main>'

**Comment by devendrabobde** [comment]
Hi there,
Can you please help with this issue?

**Comment by ileitch** [comment]
Try starting rpush manually on your server, just to see if gives you an error message.

**Comment by pratibha-spa** [comment]
Hi devendrabobde
I am facing the same issue with capistrano3 and rails4.
Please tell me what did you specified in -c option.
Did you find the solution?
Thanks

**Comment by igneus** [comment]
It is also useful to log output of rpush to a file. If it crashes, it crashes loudly.

**Comment by ileitch** [comment]
@devendrabobde any luck solving this?

**Comment by nahaylo** [comment]
It looks like your rpsuh pid file was stored in tmp/rpsuh.pid (which is default pid file) and after creating a new release directory, capistrano simply lost it. To avoid this, you should do the following thing:
1). change default path in /config/initializers/rpush.rb 
config.pid_file = 'tmp/pids/rpush.pid'
2). in /config/deploy.rb
# Default value for linked_dirs is []
set :linked_dirs, fetch(:linked_dirs, []).push('log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'vendor/bundle')

**Comment by aried3r** [comment]
I use a similar solution to what @nahaylo proposed. Setting the `pid_file` config option is the way to go.
