### ISSUE TITLE
APNS: batch_size vs multiple connections

### ISSUE THREAD

**Issue by soulfly** [rpush/rpush#174]
Hi there, 

I have read this topic https://github.com/rpush/rpush/wiki/Why-open-multiple-connections-to-the-APNs%3F

and have a question: you recommend there to increase the connections number if I need to send for example 10K push notifications quickly

But what about a 'batch_size' setting? should we also increase it to some bigger value?

Do you have any recommendations when to increase the connections number and when batch_size?

**Comment by ileitch** [comment]
`batch_size` is split evenly between the connections, so you can increase the batch_size if you increase the number of connections. However you need to monitor the memory usage of the rpush process as you increase it. For example, loading 100,000 notification records into memory is going to require a lot of memory, possibly too much.

I recommend you monitor memory usage and delivery performance and tweak the number of connections and batch_size until you're happy.

Note: don't go crazy with too many connections. If you're using MRI Ruby, too many connections will cause a decrease in performance, as each worker ends up fighting for time on the single CPU.

**Comment by ileitch** [comment]
Also, if you're using the APNs, increasing the `batch_size` with a single connection will also help, as APNs allows for many notifications to be delivered in a single `write()` to the connection.

**Comment by ileitch** [comment]
You might also want to try the StatsD plugin, it may help you monitor throughput performance.

https://github.com/rpush/rpush-plugin-statsd
