### ISSUE TITLE
Add support for APNS alert hash and customized titles.

### ISSUE THREAD

**Issue by skunkworker** [rpush/rpush#175]
Beginning in iOS 8.2, although I only just noticed this in iOS 8.4. Apple added support for customizing the alert notification finally and you can now set a Title that is different than the app name. This is made possible by adding support for the 'title' attribute under the alert dictionary. This feature is mainly used for Apple Watch push notifications.
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

Here is proof that the title attribute is working as of iOS 8.4 (Take a look at the Tinder notification, its using the 'title' key because this allows a apple watch app to use that instead of the app name)
http://i.imgur.com/fmkNQPO.png?1

I'm glad that apple finally added support for this feature as it will allow cleaner notifications.

**Comment by ileitch** [comment]
I think this should already work, you can already assign a hash to the `alert` attribute.

Does the `title` key only display instead of the app name if you have an Apple Watch?

**Comment by skunkworker** [comment]
Actually no, I don't have an apple watch on my iPhone and the title key now overrides the app name on 8.4 if present.

**Comment by ileitch** [comment]
Hmm, I did try but it didn't change the title for me. Does the app required a plist setting for this to work?

**Comment by skunkworker** [comment]
You know I am not sure on that one. I'll have to do some testing into it to see what it requires. Strangely, on the app, if I got a token pre 8.4 it wouldn't work, but post 8.4 it does work. I'll try to debug and see what exactly is going on here, as it wasn't in any release notes that it was even a feature and I only found about it as a fluke.

**Comment by ileitch** [comment]
Any progress?

**Comment by nofxx** [comment]
Works here:

```ruby
n.alert = { title: title, body: msg } 
```

Now to sound and icon ;)

**Comment by schmidt** [comment]
It looks like, the custom title is only shown within the notification area. When displayed on the lock screen, only the app name is used.

**Comment by PaulEvanCox** [comment]
skunkworker, have you gotten the title to appear on a notification on the lock screen or just in the Notification Center?  My experience indicates that the title does appear in the latter, but not the former (as schmidt indicates).

**Comment by skunkworker** [comment]
@PaulEvanCox that depends on how many there are, if there are two or more notifications on the lock screen, one of them will not have the title while the other ones will. And on the notification screen every one of them has the title. 
It's a strange behavior that I noticed on 8.4 for the first time, but there has been no fanfare from apple at all about this topic.

**Comment by PaulEvanCox** [comment]
@skunkworker, thanks for the clarification on your experience.  I just tested again, and for me (iOS 9.1), multiple notifications on the lock screen still displays the same behavior -- the title is never displayed.  I'm holding out hope that there's some setting within the app or plist file that allows for the display of the title on the lock screen.  We waste space and create our own 'title' within the alert body with a newline (ie. {title}\n{message}.

**Comment by aried3r** [comment]
Does this work for everyone with the current version of rpush? If so, please drop a short message so I can close this issue :)

**Comment by aried3r** [comment]
Closing. Btw, setting a title on a notification works for us on iOS 10 and 11. Haven't tested with 9.

**Comment by smenor** [comment]
Does this actually work ? I just tried it and am not getting any notifications if I attempt to set 

```rb
notification.alert = {"title": "some title", "body": "body content"}
```

**Comment by smenor** [comment]
Sorry / disregard the above; I have it working now
