### ISSUE TITLE
Everything is working but (Errno::ENOENT)

### ISSUE THREAD

**Issue by dyaa** [rpush/rpush#182]
i really appreciate your work guys, i have a weird problem GCM is working and pushing to my device, But when i type 

    rpush status --rails-env=production

the result will be

    /ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/daemon/rpc/client.rb:6:in `initialize': No such file or directory - connect(2) for /tmp/rpush.16456.sock (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/daemon/rpc/client.rb:6:in `open'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/daemon/rpc/client.rb:6:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/cli.rb:97:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/lib/rpush/cli.rb:97:in `status'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rpush-2.5.0/bin/rpush:4:in `<top (required)>'
	from /usr/local/bin/rpush:23:in `load'
	from /usr/local/bin/rpush:23:in `<main>'

for more details after my first deploy to production i typed 

    rpush start --rails-env=production
and the result was 

    ERROR: config/rpush.rb does not exist. Please run 'rpush init' to generate it or specify the --config option.

so now i have two rpush.rb files one in the *config* and another in the *config/initializers/* 

so now i can't see the status i cant even make the stop command.

**Comment by ileitch** [comment]
Weird, it looks like Rpush is failing to detect that your app is a Rails app. `config/initializers/rpush.rb` is used for Rails, and `config/rpush.rb` for non-rails apps.

As for the missing file, it looks like Rpush started, but was then stopped, and failed to remove the PID file. Do you see Rpush actually running in `ps`?

**Comment by shooley** [comment]
I'm also seeing this issue.  

Initially ran <code> rpush start -e my_env_name</code>

Which prompts me with an error to run <code>rpush init</code>

I then tried: 
<code>rpush start -e my_env_name --config="/home/ubuntu/my_app/config/initializers/rpush.rb"</code>

Which finishes without an error, but I am not seeing the rpush process in <code>ps</code> after that.  

One other bit of information, we are successfully using rpush with this same application in other environments that have been live for around a year.  This behavior is in a new running server.

Rails version is 4.2.3
RPush is version 2.5.0

**Comment by shooley** [comment]
It looks like this is an environmental issue in how RPush detects rails.  This check is failing 
https://github.com/rpush/rpush/blob/0713c8659e65f619e14be14484cdd97db4f2c7b1/lib/rpush/cli.rb#L9 
 
RPush looks like it halts after that.  We were using a Shared bin folder and switched to a Project specific /bin and it looks to resolve the issue.  

Thanks!
