### ISSUE TITLE
Only raise error if the notification has run out of retries

### ISSUE THREAD

**Issue by thejspr** [rpush/rpush#183]
Hi,

We're getting a several delivery exceptions running rpush and sending them to honeybadger, and I was wondering if it's possible to only send the exception is the notification is not going to be retried?

Thanks in advance

**Comment by ileitch** [comment]
What's the exception? Is this for APNs? You should only see an exception raised for the notification that actually failed.

**Comment by thejspr** [comment]
Most are regarding APNs and certificates, which were solving now. If we only get exceptions for actual failures, we're golden :+1: Thanks @ileitch
