### ISSUE TITLE
Apple VOIP pushes 

### ISSUE THREAD

**Issue by soulfly** [rpush/rpush#196]
Apple released VOIP pushes for iOS

https://developer.apple.com/library/prerelease/ios/documentation/Performance/Conceptual/EnergyGuide-iOS/OptimizeVoIP.html

http://pierremarcairoldi.com/ios-8-voip-notifications/

 http://stackoverflow.com/a/28562124/760518

They are the same pushes (backend url + payload) but a developer should generate different push certificate,

So let's say I would like to use standart push notifications and VOIP
then I have to use 4 certificates: 2(dev+prod) for standart and 2(dev+prod) for VOIP 

Is it possible to use VOIP pushes with the current version of rpush?

**Comment by ileitch** [comment]
Yes, the process is the same for standard notifications. You just need an App instance for each certificate.

**Comment by jaigouk** [comment]
voip notification works with proper headers.

```
def send_apns2_msg(app_name, message, device_token)
  notification = Rpush::Apns2::Notification.new
  notification.app = Rpush::Apns2::App.where(name: app_name).first # using redis here

  notification.device_token = device_token
  notification.alert = message
  notification.data = {
    headers: {
      'apns-topic': 'my.bundle.io.voip',
      'apns-push-type': 'voip',
      'apns-priority': '10'
    },
    aps: { alert: message, badge: 1, sound: 'default' }
  }
  notification.save!
end
```
