### ISSUE TITLE
app.auth_key = auth_key

### ISSUE THREAD

**Issue by AlicanAkyol** [rpush/rpush#198]
Hi,
What is app.auth_key?

**Comment by evanwchurchill** [comment]
your api key

**Comment by AlicanAkyol** [comment]
Ok, thanks. So, How to change it? Because  I entered wrong key so I have to change it.

**Comment by huteri** [comment]
just find the data and update_attributes

**Comment by aried3r** [comment]
Closing, I think this isn't a bug and @huteri answered the question.
