### ISSUE TITLE
Problem connecting to sandbox or production 

### ISSUE THREAD

**Issue by fokcep** [rpush/rpush#202]
can't connect the daemon, always getting same error. ruby 2.2.1 tried on heroku same things

[ERROR] Rpush::Daemon::TcpConnectionError, OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A

any idea?

**Comment by squarism** [comment]
@fokcep did you figure out what was wrong?

**Comment by fokcep** [comment]
apparently was certificate issue

**Comment by squarism** [comment]
Mine was a certificate issue too.  I found the [Knuff app](https://github.com/KnuffApp/Knuff) incredibly useful for testing.
