### ISSUE TITLE
Mocking Rpush::Apns::Notification in Rspec

### ISSUE THREAD

**Issue by ikbenben** [rpush/rpush#205]
Hi There,

I've just upgraded our application to use RSpec 2.5.0. Previously we were using 1.0.0 if you can believe it. Anyways, the unit tests we previously had are now failing due to an uninitialised constant:

     1) Fitmo::PushNotifications::Base deliver User has no notification tokens should not send any notifications
         Failure/Error: expect(Rpush::Apns::Notification).to receive(:new).never
         NameError:
           uninitialized constant Rpush::Apns
         # ./spec/lib/push_notifications/base_spec.rb:23:in `block (4 levels) in <top (required)>'

I'm assuming I need to update my spec_helper class to configure rpush appropriately but I don't see any documentation on it.

Do you have any guidelines or examples?

thanks

**Comment by ikbenben** [comment]
Found the solution. For anyone else, I had to add a Rpush config in spec_helper and set the client for it to work:

require 'push'

Rpush.configure do |config|
  # Supported clients are :active_record, :redis and :mongoid
  config.client = :active_record
end

**Comment by squarism** [comment]
Thanks for this.  Also it should be

```
require 'rpush'
```
