### ISSUE TITLE
Problem With Timezone in GCM

### ISSUE THREAD

**Issue by huteri** [rpush/rpush#207]
Hi,  I have problem with timezone, the timezone will get reset to UTC after I assign the data into rpush.data

Here is the example
```
content = { time: Time.now }
=> {:time=>2015-10-13 09:56:33 +0700}

rpush.data = content
=> {:time=>2015-10-13 02:56:33 UTC}
```
It breaks my app, could you tell me the workaround?

**Comment by aried3r** [comment]
I don't think this is a problem with rpush or GCM. Using `Time.now` you use the servers time zone, if you'd use `Time.current`, you'd use the Rails environments time zone. See http://api.rubyonrails.org/classes/Time.html#method-c-current

Can you confirm?

Here's some further reading:
http://www.elabs.se/blog/36-working-with-time-zones-in-ruby-on-rails
https://robots.thoughtbot.com/its-about-time-zones

**Comment by huteri** [comment]
Sure, I'm logged in into my server and run this in console

```
Time.current
=> Wed, 16 Dec 2015 20:11:07 WIB +07:00

rpush = Rpush::Gcm::Notification.new
rpush.data = {time: Time.current}
=> {:time=>2015-12-16 13:11:24 UTC}
```

there is no way to make rpush.data using the timezone instead of UTC.

**Comment by huteri** [comment]
I think, I know how to solve it. Convert the data into string first, then assigned it into rpush.data. 

```
Time.current.iso8601
=> "2015-12-16T20:22:13+07:00"

rpush.data = {time: Time.current.iso8601}
=> {:time=>"2015-12-16T20:22:38+07:00"}
```
