### ISSUE TITLE
rpush migrations fail with oracle db

### ISSUE THREAD

**Issue by arjun14381** [rpush/rpush#209]
I m unable to run  rpush migrations with oracle , i wanted rpush tables to track the delivery of notifications ,but the migrations are failing since the sequence names used in the migrations are greater than 32 characters length which is not allowed by oracle ,hence the migrations are failing , i altered sequence names and was able to run the migrations but there are still problems with the working of rpush , i guess as i changed certain sequence names it would have affected it

**Comment by aried3r** [comment]
Closing this issue as stale.
