### ISSUE TITLE
Rpush Priority High On GCM

### ISSUE THREAD

**Issue by huteri** [rpush/rpush#217]
Hi, I've set the rpush.priority = "high" in gcm, but it seems it does not work, I don't see the parameter in the response result. How do you set this?

**Comment by schmidp** [comment]
in the current master branch, priority on GCM is not supported.
I just added in my branch: https://github.com/openresearch/rpush/commit/ff0ce6df8c2e27981ad01c85fdf90e4ce8ae31a6

**Comment by huteri** [comment]
Hi @schmidp, thank you, this library needs people like you..
