### ISSUE TITLE
Support for GCM notification payload

### ISSUE THREAD

**Issue by aried3r** [rpush/rpush#223]
https://developers.google.com/cloud-messaging/concept-options?hl=en#notifications_and_data_messages

It has a predefined set of key options, see https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support

**Comment by NeoElit** [comment]
Looking forward to it. Anyone working on this feature?

**Comment by aried3r** [comment]
This repo just got a lot of new collaborators, so while I don't think anyone is working on it right now, we could merge it, once somebody does it.

I just don't know if I'd just have something like a `notification_payload` column in which one can serialize whatever is needed or have a separate column for every predefined key.


PS:
@ileitch Thanks for adding collaborators! Can we somehow contact you for releasing to rubygems, once more PRs are merged?

**Comment by NeoElit** [comment]
@aried3r i think the existing :data column itself can be changed to json payload . If that's the case there won't be any need for changes when GCM adds new features.

**Comment by ileitch** [comment]
Just open an issue when you need a release. Once a trusted contributor emerges I'll give them the power to release.

**Comment by aried3r** [comment]
> i think the existing :data column itself can be changed to json payload . If that's the case there won't be any need for changes when GCM adds new features.

The `data` payload is different from the `notification` payload. But I guess we could handle it in the same way and have a separate `notification` or `notification_payload` column?

```JSON
{
    "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
    "notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark",
      "icon" : "myicon"
    },
    "data" : {
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
  }
```

On the other hand, since rpush already supports APNs, it already has all the columns for the `notification` payload. Maybe we can somehow re-use that? I didn't really read much into the code other than for my own PR (#221).

**Comment by aried3r** [comment]
@ileitch Thanks!

**Comment by NeoElit** [comment]
>On the other hand, since rpush already supports APNs, it already has all the columns for the notification payload. Maybe we can somehow re-use that?

@aried3r if that's the case it's better to reuse same column. I was thinking if it requires to add new column we might as well accept whole payload:
```
{
    "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
    "notification" : {
      "body" : "great match!",
      "title" : "Portugal vs. Denmark",
      "icon" : "myicon"
    },
    "data" : {
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
  }
```
as json and simply add to request body, since rpush has nothing to do with the content. Then new added features of GCM won't require an update to rpush. Just a thought :)

**Comment by NeoElit** [comment]
I have done some dirty hack and made rpush support for gcm with general payload.
https://github.com/NeoElit/rpush/tree/implement_feature_gcm_topic_%23219

**Comment by aried3r** [comment]
Care to send a PR?

**Comment by NeoElit** [comment]
@aried3r I don't know if it's worth to pull to rpush since what i did is kind of a dirty hack to make it work. It skips existing registration_ids validations and all keys are embedded in ```:data``` itself as json, they also lack validations.

**Comment by aried3r** [comment]
> I was thinking if it requires to add new column we might as well accept whole payload

Yeah, that sounds like a good idea. However that would either require a bit of a rewrite and maybe a major version change if it changes the API. Also we lose *some* validations that come almost for free now, which I guess was @ileitch's intention.

Hmm,... I'm not sure if I want to re-write so much right now. I think I'll add a separate column, even if I just  alleviate the symptoms.
