### ISSUE TITLE
Implement the new HTTP/2 API for APNS

### ISSUE THREAD

**Issue by frane** [rpush/rpush#229]
In this year's WWDC Apple announced and introduced improvements to the APNS [1], the most significant one being a new HTTP/2 interface [2].
I think that replacing the old TCP based interface with the new HTTP/2 version would also be a huge improvement for Rpush. However, I see that this would imply major and possibly breaking changes to the whole APNS implementation in Rpush.
Are there any plans regarding the HTTP/2 interface?

I'm willing to help out, but would need some pointers how to approach this.

[1] https://developer.apple.com/videos/play/wwdc2015-720/
[2] https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html

**Comment by ileitch** [comment]
This would be a huge win, much of the complexity in Rpush is caused by the craziness needed to check for APNs delivery errors.

**Comment by aried3r** [comment]
There is https://github.com/alloy/lowdown which could be used for inspiration, collaboration or even integration.

**Comment by soulfly** [comment]
Do you have any ETA when this can be implemented?

**Comment by aried3r** [comment]
I'm not a maintainer, but I don't think anyone is working on it at this time.

**Comment by frane** [comment]
I'm started working on it last week. It took me some time though to understand the code base and come up with ideas how to replace the old TCP-APNS code with the new HTTP/2 version. 

I'm still not sure how to properly test the new functionality.

**Comment by gregmurray** [comment]
Outstanding.  I'm glad you guys are on this.  I just added this Gem to a new project, and was shocked when I was throwing errors for having a payload size greater than 2k.  I'd very much like to have integration with HTTP/2 to support up to 4k payloads.  Let me know what I can do to help, if I can.

**Comment by nextofsearch** [comment]
@frane Can you please update the current status? Please let me know if I can help.

**Comment by soulfly** [comment]
Hi guys, any updates so far?

**Comment by arunjiffler** [comment]
Hi Guys, 
Any updates on this?

@frane

**Comment by soulfly** [comment]
Guys, does anybody work on this task?

**Comment by soulfly** [comment]
@frane could you please give us some updates? how we can access your fork and help you to speed up things?

**Comment by onpaws** [comment]
@frane I know some folks who would be very interested in checking out your efforts here.
If you wouldn't mind pushing your work to a branch e.g. `apnsv2`, however far you got, I'll be happy to try and continue.

**Comment by soulfly** [comment]
@frane 

> I see that this would imply major and possibly breaking changes to the whole APNS implementation in Rpush.

from my understanding, we do not need to patch current **apns** service, but create alternative one, for example, call it **apns2**
So end users will be able to use both **apns** and **apns2** for some time

**Comment by soulfly** [comment]
We have started internal development of this feature
Will be able to share pull request with everybody later

**Comment by soulfly** [comment]
Here it is https://github.com/rpush/rpush/pull/315

please comment

**Comment by onpaws** [comment]
Thanks @soulfly, excited to check this out!

**Comment by amaierhofer** [comment]
Has been merged.

**Comment by onpaws** [comment]
Great work.
