### ISSUE TITLE
Proper `as_json` Support

### ISSUE THREAD

**Issue by chaffeqa** [rpush/rpush#231]
calls to `as_json` error out since all `as_json` implementations are supposed to have a single argument: `as_json(args={})`

Called from trying to use Airbrake and pass a notification.

Fix would be pretty simple: just add the default params to the `notification.rb` files (sorry, just really busy or else id pull request it ><)

**Comment by aried3r** [comment]
How exactly do they error out? But I agree, we should probably make them `as_json(options = nil)` as documented in http://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html#method-i-as_json
