### ISSUE TITLE
Cannot save a valid APNS notification because of alert length

### ISSUE THREAD

**Issue by schmidt** [rpush/rpush#235]
When storing a `Apns::Notification` with a long alert text, the notification model is valid, but saving it fails (using the ActiveRecord backend with MySQL) since the alert column is to small.

```
test "alert size" do
  n = Rpush::Apns::Notification.new(app: Rpush::Apns::App.first, device_token: "a" * 64, alert: "*" * 300)
  assert n.valid?
  assert_nothing_raised do
    n.save
  end
end
```

The above simplified test case raises the following error:

    ActiveRecord::StatementInvalid: Mysql2::Error: Data too long for column 'alert' at row 1: INSERT INTO `rpush_notifications` (`type`, `app_id`, `device_token`, `alert`, `created_at`, `updated_at`) VALUES ('Rpush::Client::ActiveRecord::Apns::Notification', 1, 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', '************************************************************************************************************************************************************************************************************************************************************************************************************', '2016-01-21 11:52:52', '2016-01-21 11:52:52')

Changing the alert column from `string` to `text` would fixes the bug.

    change_column "rpush_notifications", "alert", "text"

... but I don't know if this would cause any undesired side effects.

Happy to provide a pull request if desired.

**Comment by aried3r** [comment]
That seems reasonable, given `alert` can be a dictionary with [these keys](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW4).

> Happy to provide a pull request if desired.

And we'd be happy to receive it :)

**Comment by schmidt** [comment]
> And we'd be happy to receive it :)

There you go: #248

I'm looking forward to your feedback.

**Comment by schmidt** [comment]
Thanks :+1:
