### ISSUE TITLE
There is no notification attribute in Rpush::Gcm::Notification

### ISSUE THREAD

**Issue by huangjun604** [rpush/rpush#252]
When I create a new `Rpush::Gcm::Notification` and try to give the `notification` some value, but it says `ActiveRecord::UnknownAttributeError: unknown attribute 'notification' for Rpush::Client::ActiveRecord::Gcm::Notification.`

**Comment by aried3r** [comment]
Which version of rpush are you using? And could you show the code that is
failing?

**Comment by huangjun604** [comment]
This failing code is:

```
n = Rpush::Gcm::Notification.new
n.app = Rpush::Gcm::App.find_by_name("android_app")
n.registration_ids = ["..."]
n.data = { message: "hi mom!" }
n.priority = 'high'        # Optional, can be either 'normal' or 'high'
n.content_available = true # Optional
# Optional notification payload. See the reference below for more keys you can use!
n.notification = { body: 'great match!',
                   title: 'Portugal vs. Denmark',
                   icon: 'myicon'
                 }
n.save!
```

This is the description about the question.
http://stackoverflow.com/questions/35328824/missing-notification-attribute-for-gcm-in-rpush
