### ISSUE TITLE
How to create new app in rails?

### ISSUE THREAD

**Issue by huangjun604** [rpush/rpush#253]
In Rpush, the first thing is to register a new app. Mostly, the app will create once for each platform when the rails start running.

```
app = Rpush::Apns::App.new
app.name = "ios_app"
app.certificate = File.read("/path/to/sandbox.pem")
app.environment = "sandbox" # APNs environment.
app.password = "certificate password"
app.connections = 1
app.save!
```

So what is the best place to put those code in? To make sure not create more app. Should be in `initializers`? I try to put it in as a script, but it looks like not formal. Maybe something like `configure` things? Thanks.

By the way, what the meaning of `connections` in `app` attributes?

**Comment by chadiso** [comment]
up

**Comment by amaierhofer** [comment]
This is up to you. I think it is reasonable to place that kind of into an initializer. 

The `connections` attribute refers to how many connections are used when sending messages to the appropriate push endpoint. More specific information for the APNS endpoint can be found in wiki.
