### ISSUE TITLE
Running rpush as asystemd service

### ISSUE THREAD

**Issue by itsSaad** [rpush/rpush#256]
Im having some problem running the rush service. The process runs but the service `status` says that it exited and 0/success. That might mean that the command im running creates another process and exits itself. So infact the process is running in the background but its not running through the service.
the `.service` file is as bellow
```bash
[Unit]
Description=momentz RPush production Server
After=unicorn_temp_directory.service

[Service]
Type=forking
SyslogIdentifier=momentz_production_rpush
User=deployer
PIDFile=/home/deployer/apps/momentz_production/shared/tmp/pids/rpush.pid
WorkingDirectory=/home/deployer/apps/momentz_production/current

ExecStart=/bin/sh -c 'RBENV_ROOT=/home/deployer/.rbenv RBENV_VERSION=2.2.3 /home/deployer/.rbenv/bin/rbenv exec bundle exec rpush start -e production'
ExecStop=/bin/kill -9 $MAINPID
#ExecReload=/bin/kill -s HUP $MAINPID
#ExecReload=/bin/kill -s USR2 $MAINPID
#ExecStop=/bin/sh -c 'RBENV_ROOT=/home/deployer/.rbenv RBENV_VERSION=2.2.3 /home/deployer/.rbenv/bin/rbenv exec bundle exec rpush stop -e production'

[Install]
WantedBy=multi-user.target
```

What am i missing here.
This file is generated by the setup_config task I've written for capistrano.

**Comment by itsSaad** [comment]
ok so I've changed the `Type` of the service to `forking` and it seems to recognize the process and pid.

**Comment by aried3r** [comment]
Would you consider sending a PR with your final config? Maybe for the `examples/` directory. https://github.com/rpush/rpush/tree/master/examples

**Comment by itsSaad** [comment]
sure i will in the morning.

**Comment by itsSaad** [comment]
https://github.com/rpush/rpush/pull/257
