### ISSUE TITLE
rpush shuts down after start when using capistrano

### ISSUE THREAD

**Issue by nwittstruck** [rpush/rpush#265]
I'm trying to start rpush using capistrano. This is what my cap task looks like:

```
task :restart_rpush do
  on roles(:web) do
    within release_path do
        if test('[ -f /var/www/webroot/shared/tmp/pids/rpush.pid ]')
          # Rpush is running
          execute :bundle, :exec, "rpush stop -e production"
          execute :bundle, :exec, "rpush start -e production"
        else
          # Rpush is not running
          execute :bundle, :exec, "rpush start -e production"
        end
      end
  end
end
```

I've also linked the tmp/pids folder.

Sometimes, starting rpush doesn't work. Regardless whether it was running previously or not, even if I clean the pid file and make sure that there is no process running. The capistrano output shows that the command is run successfully, there is also a pid file created, but the process is not running. Is it possible to enable more debug output?

This is what I am currently getting:

```
INFO [] Running /usr/local/rvm/bin/rvm default do bundle exec rpush start -e production as 
DEBUG [] Command: cd /var/www/webroot/current && /usr/local/rvm/bin/rvm default do bundle exec rpush start -e production
DEBUG []    * Booting Rails 'production' environment... 
DEBUG []    ✔
INFO [] Finished in 9.862 seconds with exit status 0 (successful).
```

**Comment by nwittstruck** [comment]
I just noticed that it works when I use the development mode instead of production. Any ideas?

**Comment by aried3r** [comment]
Hey @nwittstruck, is this still an issue for you? I'm doing a bit of cleanup on old issues and I'm gonna close this. Should this still occur, please feel free to open a new issue or reply here.
