### ISSUE TITLE
Blackberry 10 push notifications

### ISSUE THREAD

**Issue by soulfly** [rpush/rpush#275]
Are there any plans to support Blackberry 10 push notifications?

If not - what's the standard process here? Fork your repo, do it ourselves and create a pull request?

**Comment by aried3r** [comment]
> what's the standard process here? Fork your repo, do it ourselves and create a pull request?

Pretty much this, yes. :)

I'm not an official maintainer, me and a few other guys have push access so this repo doesn't go completely unmaintained, but we can't release anything ourselves.
So your best bet is to send a PR (with tests!) and we'll try to get it merged and released.
