### ISSUE TITLE
APNS communication

### ISSUE THREAD

**Issue by vinceferro** [rpush/rpush#280]
APNS endpoint should be used instead of the legacy binary interface, as documented by apple here: 
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html

This is the new APNs API is documented here: 
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW16

**Comment by amaierhofer** [comment]
Thanks for pointing that out. It's already being discussed here https://github.com/rpush/rpush/issues/229
