### ISSUE TITLE
Support for google's  Firebase Cloud Messaging 

### ISSUE THREAD

**Issue by RobWu** [rpush/rpush#284]
https://firebase.google.com/docs/cloud-messaging/
> Firebase Cloud Messaging (FCM) is a cross-platform messaging solution that lets you reliably deliver messages and notifications at no cost.

https://firebase.google.com/support/faq/#gcm-fcm
> Cloud Messaging: I am an existing Google Cloud Messaging (GCM) developer. Should I move to Firebase Cloud Messaging?
> 
> FCM is the new version of GCM under the Firebase brand. It inherits GCM’s core infrastructure, with new SDKs to make Cloud Messaging development easier.
> 
> Benefits of upgrading to FCM SDK include:
> 
> Simpler client development. You no longer have to write your own registration or subscription retry logic.
> An out-of-the-box notification solution. You can use Firebase Notifications, a serverless notifications solution with a web console that lets anyone send notifications to target specific audiences based on Firebase Analytics insights.

**Comment by aried3r** [comment]
I think rpush already supports FCM, because it's no different to GCM from what I gathered.

> You won’t need to make any server-side protocol changes for the upgrade. The service protocol has not changed. [<sup>source</sup>](https://developers.google.com/cloud-messaging/faq)

We could change the endpoint URLs, like [node-gcm](https://github.com/ToothlessGear/node-gcm/pull/232/files) does, but even that seems to be optional for now.

> Updating these endpoints is not strictly required, as Google will continue to support the existing GCM endpoints. [<sup>source</sup>](https://developers.google.com/cloud-messaging/android/android-migrate-fcm#update_the_usage_of_gcmpubsub)


I'm gonna close this, but I'll reopen it, should I have missed something. :)

**Comment by RobWu** [comment]
Thanks for your fast response.

**Comment by Kris-Simpson** [comment]
@aried3r do I understand correctly, now, when I use `Rpush::Gcm::Notification.new` notification will be sent on FCM server? Or is it only plans?

**Comment by robban** [comment]
Hi, I signed up for the FCM service (GCM does not seem to be available anymore) and I am trying to use the rpush libraries. I am getting 401 (Unauthorized) errors when doing: rpush push . Tried to change the urls but that did not help.
I am guessing that I my auth_key is wrong, I am using the "current_key" from the google-services.json. Anyone have an idea on how i find the auth key for FCM?

**Comment by robban** [comment]
Oki, so I finaly found the auth_key. If anyone else has trouble finding it is in the firebase console-> Your project name -> Settings -> Cloud messaging -> Server name

**Comment by jogiranjith** [comment]
@robban thank you so much it worked for me \m/

**Comment by spaghetticode** [comment]
@robban thank you, I think this note should be in the readme to save other people's time

**Comment by vokrut** [comment]
For using with FCM needed two parameters: app.name = "android_app" and app.auth_key = "...". In FCM console we have Server key, Legacy server key, Sender ID, project ID, package name, App ID. Could someone help with it? What exactly we need to put in that parameters?

**Comment by aried3r** [comment]
Server key, yes.

**Comment by aried3r** [comment]
@vokrut, the server key is needed.

**Comment by ronyfhebrian** [comment]
What is registration_id in rpush FCM and how to get it?

**Comment by aried3r** [comment]
@ronyfhebrian, it's the devices [registration token](https://firebase.google.com/docs/cloud-messaging/android/client#sample-register). The link shows how to get it on Android.

**Comment by nikolai-b** [comment]
I came here because it is linked to in the readme.

@aried3r I think this might need re-opening

> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as April 11, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more. <sup>[source](https://developers.google.com/cloud-messaging/android/android-migrate-fcm#update_the_usage_of_gcmpubsub)</sup>

**Comment by aried3r** [comment]
Yep, you are right! I read about this too. There's also structural changes to the payloads, which I want to test out at work first.

I think it might also be a good time to *really* replace all occurrences of GCM in the code. This might break compatibility so maybe it's going to be in 4.0.

I don't really have much time currently to work on Rpush, so I'm happy for every contribution. :)

**Comment by nikolai-b** [comment]
Once I've settled in using rpush I might be able to look at helping.
Thanks.

**Comment by alexshikov** [comment]
Just curious, is that something scheduled or the contribution wanted?
