### ISSUE TITLE
Logs spamming [ERROR] Rpush::CertificateExpiredError

### ISSUE THREAD

**Issue by yoyos** [rpush/rpush#285]
Hello,

I got lot of CertificateExpiredError in my logs, spamming it literally every 5 seconds.
The problem is it concerns old apps I can't remove, they are not used for the moment and I don't need to replace all those certificates right now until an unknown time.

Is there a way to disable them without removing them ?
Or maybe could the CertificateExpiredError check happen only one time a day ? not every minute on each app .. ?

Thanks !

**Comment by risinglf** [comment]
+1 same here

**Comment by palya** [comment]
This error increased log file size up to 28Gb for 3 days, so this is definitely a bug.

**Comment by michele** [comment]
+1 same here

**Comment by stefangomez** [comment]
This is kind of an old thread, but I realized (for me) that these errors were coming from other (older) "Rpush::Apns::App" that were still in the db. Not sure if that helps, but you should be able to see all of the apps your db store has by doing: Rpush::Apns::App.all.to_a and seeing which ones you no longer use/are expired
