### ISSUE TITLE
Turn off `Errors: NotRegistered` error log

### ISSUE THREAD

**Issue by sydneyitguy** [rpush/rpush#298]
My `rpush.log` file getting filled with `Errors: NotRegistered` errors (and its stack traces) because a big amount of users delete the app and the registration IDs become invalid every day.

I think it would be useful to disable this particular error log as I'm already handling those cases on this block.
```
on.gcm_invalid_registration_id do |app, error, registration_id|
    ...
end
```

**Comment by amaierhofer** [comment]
I don't know if this can be done inside the block. It's probably simpler to stop sending push messages to those devices
