### ISSUE TITLE
Rpush.push not called

### ISSUE THREAD

**Issue by giomv** [rpush/rpush#299]
Hi, I've started using rpush for a project and it's working fine. I've managed to setup the apps for Android and iOS and send the notifications to the devices correctly. To accomplish that, I've called directly Rpush.push from the rails console, after creating the Rpush::Apns::Notification object for both platforms. 

I want to be able to call Rpush.push on an after_create callback of a PushNotification model I created. However, when the callback is fired, the Rpush::Apns::Notification objects for Android and iOS are created, but calling Rpush.push is not sending any notification. After that, I go to the rails console and run Rpush.push, and only after that the notifications are delivered to the devices. Is not correct to call Rpush.push inside a callback? What should be the appropriate way to send the notifications? Thanks in advance!

**Comment by umarana** [comment]
i have the same issue in my background job

**Comment by jim0020** [comment]
Use the daemon, running in the background, or as a cron/scheduled job, or embedded.  See the section "Running Rpush" in the Readme.md file.

**Comment by giomv** [comment]
Yes, I ended up using the embeded. Thanks!
