### ISSUE TITLE
RPUSH Freezes, connection stay in CLOSE_WAIT status 

### ISSUE THREAD

**Issue by tcolepc** [rpush/rpush#301]
Sometimes rpush freezes "locked" for processing notifications. When we have large number of notifications system works perfectly, we have problems processing when the amount is lower.

Rpush log stops writing, these are the last lines:

> SQL (1.6ms)  UPDATE `rpush_notifications` SET processing = 0, delivered = 1, delivered_at = '2016-09-15 07:43:41.307147' WHERE `rpush_notifications`.`id` IN (2952279, 2952283, 2952287, 2952291)
> [2016-09-15 07:43:43] [WARNING] Lost connection to database, reconnecting...
> [2016-09-15 07:43:43] [WARNING] Attempt 1
>    (36.9ms)  SELECT COUNT(_) FROM `rpush_notifications`
> [2016-09-15 07:43:43] [WARNING] Database reconnected
>   SQL (1.4ms)  UPDATE `rpush_notifications` SET processing = 0, delivered = 0, delivered_at = NULL, failed = 1, failed_at = '2016-09-15 07:43:41.299176', error_code = NULL, error_description = 'Mysql2::Error: MySQL server has gone away: SELECT  `rpush_apps`._ FROM `rpush_apps` WHERE `rpush_apps`.`id` = 1 L
> IMIT 1' WHERE `rpush_notifications`.`id` = 2952275
> [2016-09-15 07:43:43] [ERROR] ActiveRecord::StatementInvalid, Mysql2::Error: MySQL server has gone away: SELECT  `rpush_apps`.\* FROM `rpush_apps` WHERE `rpush_apps`.`id` = 1 LIMIT 1
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in `query'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in`block in execute'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:299:in`execute'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in`exec_query'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:347:in `select'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in`select_all'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/querying.rb:39:in`find_by_sql'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/statement_cache.rb:107:in `execute'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/associations/singular_association.rb:59:in`get_records'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/associations/singular_association.rb:63:in `find_target'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:138:in`load_target'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/associations/association.rb:53:in `reload'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/associations/singular_association.rb:9:in`reader'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/activerecord-4.2.1/lib/active_record/associations/builder/association.rb:115:in `app'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/gcm/delivery.rb:146:in`do_post'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/gcm/delivery.rb:21:in `perform'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/dispatcher/http.rb:12:in`dispatch'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/dispatcher_loop.rb:66:in `dispatch'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/dispatcher_loop.rb:35:in`block (2 levels) in start'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
> /usr/local/lib/rvm/gems/ruby-2.1.3/gems/rpush-2.7.0.1/lib/rpush/daemon/dispatcher_loop.rb:25:in`block in start'

In the haproxy database (Galera MariaDb) , we do not see established connections and the server itself rpush have a connection in CLOSE_WAIT\* state:

```
tcp        1      0 192.168.123.123:5600   192.168.123.141:5601    CLOSE_WAIT  14551/rpush
```

*CLOSE_WAIT means that the local end of the connection has received a FIN from the other end, but the OS is waiting for the program at the local end to actually close its connection. The problem is your program running on the local machine is not closing the socket. It is not a TCP tuning issue. A connection can (and quite correctly) stay in CLOSE_WAIT forever while the program holds the connection open.

Thanks in advance

**Comment by amaierhofer** [comment]
Most likely this is due the a Database Deadlock. This has already been discussed here https://github.com/rpush/rpush/issues/200

Check your Database log file to verify  that the "lock" correlates to deadlocks encountered by the database
