### ISSUE TITLE
net-http-persistent 3.0.0 breaks rpush

### ISSUE THREAD

**Issue by jmoline** [rpush/rpush#306]
net-http-persistent has changed their initialize method to accept a hash:

`def initialize name: nil, proxy: nil, pool_size: DEFAULT_POOL_SIZE`

Which causes issues when it is called with just the name parameter, as it is on line 8 of rpush/lib/rpush/daemon/dispatcher/http.rb:

`@http = Net::HTTP::Persistent.new('rpush')`

Edit: This is not critical for me or anything; I'm going to downgrade my net-http-persistent version. I just wanted to make you aware of the issue.

**Comment by jeryRazakarison** [comment]
Oh yeah, than you very much! I spent one hour trying to compare a new app with an old one where push notifications worked... You saved me another hour or more I think!
`gem 'net-http-persistent', '2.9.4'`
