### ISSUE TITLE
rpush command not found

### ISSUE THREAD

**Issue by HienNguyenAsnet** [rpush/rpush#312]
I try install rpush `2.7.0` then run `bundle exec rpush init`. It's raise error
`bundler: command not found: rpush`

**Comment by odedharth** [comment]
happened to me on only development from some reason

**Comment by aried3r** [comment]
Could you guys specify what exactly you did? How did you install it, do you use spring binstubs or anything special?

**Comment by aried3r** [comment]
Closing this since there have been no additional reports of this and I couldn't reproduce it locally.

If anyone is still facing this issue, please open a new issue.
