### ISSUE TITLE
Support Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by MioGreen** [rpush/rpush#319]
Hello, guys! Do you have any plans to support Firebase Cloud Messaging (FCM)? Right now we can't anymore create new GSM for Android.

**Comment by aried3r** [comment]
For now, FCM and GCM are the same, thus rpush already supports it. You can find more info in these issues: https://github.com/rpush/rpush/issues?q=is%3Aissue+fcm+is%3Aclosed

But maybe we should reflect this in the README.
