### ISSUE TITLE
Is rpush support to send data message of FCM.

### ISSUE THREAD

**Issue by fredgit** [rpush/rpush#321]
With FCM, you can send two types of messages to clients:

*Notification messages, sometimes thought of as "display messages."
*Data messages, which are handled by the client app.

But I found the RPush seems only support the first type: Notification messages.
So I can't handle the receive message when my android app on background.
Can anybody correct me? Thanks.

**Comment by aried3r** [comment]
> But I found the RPush seems only support the first type: Notification messages.

You can find the necessary information in the [README.md here](https://github.com/rpush/rpush#google-cloud-messaging). You just need to set `data` to whatever you wish. :)

**Comment by fredgit** [comment]
@aried3r Thank you. I think I get the information I want. Sorry, I don't good at ruby code.
