### ISSUE TITLE
[question] Is the new APNs Auth Key (.p8) usable?

### ISSUE THREAD

**Issue by jeryRazakarison** [rpush/rpush#322]
Apple introduced .p8 APNs Auth Key to ease the creation of keys to authenticate our server to APNs servers.
Is it taken into account in rpush? I saw this line:

> To use the newer APNs Api replace Rpush::Apns::App with Rpush::Apns2::App.

But I wonder if it is a reference to the new APNs Auth Key.

**Comment by soulfly** [comment]
So far it is not
It works with certificates only

**Comment by IevgenRagulin** [comment]
Is there a plan to add support for it?

**Comment by thomasgallagher** [comment]
This would simplify things in the certificate creation department.

Happy to help out if anyone can give a steer on implementation?

**Comment by mariannegru** [comment]
Hi,

I added p8 support: https://github.com/rpush/rpush/pull/386

Marian

**Comment by aried3r** [comment]
Seeing as @mariannegru added support and I don't use APNS, it would be really great if some of the others in here could test it a bit. :)

**Comment by aried3r** [comment]
This will be in the upcoming 3.2 release.
