### ISSUE TITLE
[REDIS] Rpush::Apns::App.all selects ALL apps (GCM, MPNS, etc.)

### ISSUE THREAD

**Issue by nattfodd** [rpush/rpush#325]
There is an issue with Redis, when we need to select specific Rpush apps (notifications as well) like:

```ruby
> Rpush::Gcm::App.all

[10] pry(main)> Rpush::Gcm::App.all
=> [
#<Rpush::Client::Redis::Apns2::App:0x000000093ef7e8
  @attributes=
   {"id"=>1,
    "name"=>"1_p_apns2",
    "environment"=>"production",
...
#<Rpush::Client::Redis::Apns2::App:0x000000093edad8
  @attributes=
   {"id"=>3,
    "name"=>"2_d_apns2",
    "environment"=>"development",
```

I'm not sure if this is a particular Rpush issue, but still it causes non-obvious things to happen when debugging code with that stuff.

**Comment by fertobar** [comment]
yes, I notice same issue in my tries @Nattfodd

**Comment by Tonkpils** [comment]
Yeah, I just ran into this as well using `rpush-redis`

```ruby
irb(main):017:0> Rpush::Gcm::App.all
=> [#<Rpush::Client::Redis::Apns::App:0x007f2b052b9710 ...
```

**Comment by Tonkpils** [comment]
@Nattfodd I've released a new version of the library backing rpush-redis which fixes this issue. Could you update `bundle update modis` and let me know if you still see this?

**Comment by aried3r** [comment]
@Tonkpils, I'm currently working on #366 but I had to lock `modis` to 1.4.1 in the tests because even with 1.4.2 I saw tests failing. Do you think you could help me make it work with the newer modis version?

Since the future of #366 is unclear, maybe you could send a separate PR for the current master branch.

**Comment by Tonkpils** [comment]
@aried3r I'll make an update for it and see if I can fix any failing specs.

**Comment by milgner** [comment]
Running Modis 1.4.2 and the problem has gone for newly created apps. Interestingly enough, existing apps don't show up in their proper scope but the new ones seem to work properly.

**Comment by aried3r** [comment]
Hey, since I'm not using rpush-redis, can anyone tell me if this is still an issue with Modis 2.x? Otherwise I'd close this issue.

**Comment by milgner** [comment]
This has been resolved by the modis upgrade!

**Comment by aried3r** [comment]
Thank you for the quick feedback!
