### ISSUE TITLE
Rpush installed via bundler doesn't have the correct gemspec

### ISSUE THREAD

**Issue by dexterouschen** [rpush/rpush#327]
net-http-persistence has breaking changes since 3.0.0 and rpush can't use it as a dependency. The gemspec is correct in this repo but for some reason the gem release doesn't have that restriction.

**Comment by kntmrkm** [comment]
How is this going?

**Comment by kntmrkm** [comment]
I found what is problem.

version `2.7.0` does't restrict `net-http-persistence` version.

Check this commit.
https://github.com/rpush/rpush/commit/b8f18f00d2b3fbd866ab6df2531355d544832d79

version `2.9.0` will works fine with `net-http-persistence 2.9.4`.

**Comment by aried3r** [comment]
We'll try to either correct the README to point people to only use git branches or tags until we can contact @ileitch to draft another release.

Closing since this issue is fixed, except it's not shipped yet.
