### ISSUE TITLE
Notification to open link in browser

### ISSUE THREAD

**Issue by sridharraman** [rpush/rpush#336]
I am trying to create notifications (iOS, Android) that, when clicked, open up a link in a browser. Is this possible using rpush? Or is there more of a native iOS/Android feature we have to look at?

**Comment by aried3r** [comment]
I don't think you can do this with a simple payload of a notification. You'd have to handle the payload inside your app natively which could open a browser window. There's nothing we can do in rpush to help you with this feature.

You should be able to find a solution on StackOverflow. Best of luck!
