### ISSUE TITLE
Hours exceptions

### ISSUE THREAD

**Issue by claudioldf** [rpush/rpush#337]
Hi,

It is not exactly an issue, but an improvment.
I need to push notification between 8am and 10pm.
There is alread some feature/configuration available today? I could not find something like this on documentation.
Is it possible to you implement it?

Thank you.

**Comment by aried3r** [comment]
I think this is out of scope for this gem. Scheduling and queuing is a responsibility in itself. I think you can come up with something using gems like [whenever](https://github.com/javan/whenever) and/or ActiveJobs. This is just an idea, not saying this will work for your scenario.

Good luck!
