### ISSUE TITLE
Apps for multiple environments

### ISSUE THREAD

**Issue by alameenkhader** [rpush/rpush#338]
Recently I had to use two different certificates for production and demo environments for my app. 

Can we have the ability to create apps for multiple environments?

**Comment by chris** [comment]
You can create as many `Rpush::Apns2::App` (or whatever variant you need) instances as you like. We typically have at least 2 of these per platform, sometimes more (debug vs. release, adhoc vs. enterprise, and other variations). We then associate push tokens/registrations ID's with a particular `App`, so when you go to send a push you know which Rpush `App` to target.
