### ISSUE TITLE
notification_delivered not working for Apns2

### ISSUE THREAD

**Issue by chris** [rpush/rpush#339]
I'm using the latest code in master, and the Apns2 classes. I'm finding that the `notification_delivered` callback is not called for my notifications (yet they arrive on the device - usually). I've done a bit of logging/debugging and have found that `@delivered` is empty when being processed by `Batch.complete_delivered`. `Batch.mark_all_delivered` does indeed get called, and it sets `@delivered` to a collection of notifications. From the logging, it seems like `complete_delivered` gets called _before_ `mark_all_delivered` finishes (I see my logging fire for `complete_delivered` where it shows empty `@delivered`, and the next log message is one saying `@delivered` is being set to non-empty `@notifications`).

I wanted to get this issue opened to see if anyone knew more about this before I dug further (this may have to do with the mutexes, and/or other threading issues, so before I dive into that too far...).

I will note that using Apns (1) appears to work fine. I also noticed there are no tests for Apns2, so maybe Apns2 isn't really something I should use in production yet?

**Comment by chris** [comment]
I also noticed that once I switched back to Apns, that the APNS feedback service started working (I hadn't gotten a single feedback item before, and now I've gotten a ton).

**Comment by Fivell** [comment]
@chris ,  did you manage somehow this problem?

**Comment by chris** [comment]
@Fivell I just changed my code to use `Apns`, and do not yet have a fix for `Apns2`. From further testing and use now, I would consider `Apns2` in rpush to be unusable - we simply did not get consistent push notification delivery, and there are issues with the callbacks, plus there are no specs/tests for it. I'm hoping to circle back around and dig into this issue further, but at the moment I'm trying to finish up a couple projects, so I'm not sure when I'll get to it.

**Comment by Nattfodd** [comment]
Hey guys. There's a fix for it for a pretty long time  https://github.com/rpush/rpush/pull/332

It's not merged to master yet

**Comment by aried3r** [comment]
@Nattfodd, have you been using it in production successfully? Then I guess we can merge it. We don't use APNs2 in our project, so I can't really say anything about it.

**Comment by Fivell** [comment]
@Nattfodd , thanks for pointing to this PR , will try it until it merged

**Comment by Nattfodd** [comment]
@aried3r we are testing it for a month or so in test environment, no issues have been found until now.

**Comment by aried3r** [comment]
I have merged the fix by @Nattfodd, please use the master branch version and try it. I cannot verify myself.

**Comment by aried3r** [comment]
Closing this. Everyone, feel free to discuss this here or open another issue if this did not fix your issue.

**Comment by Fivell** [comment]
@Nattfodd , sometimes exception crashes rpush 
```
[2017-03-15 16:33:44] [ERROR] SocketError, Socket was remotely closed
/opt/***/vendor/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:122:in `callback_or_raise'
/opt/***/vendor/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:107:in `rescue in block (2 levels) in ensure_open'
/opt/***/vendor/bundle/ruby/2.2.0/gems/net-http2-0.15.0/lib/net-http2/client.rb:101:in `block (2 levels) in ensure_open'
```

**Comment by Nattfodd** [comment]
@Fivell is it related to the delivery status issue fix?

**Comment by Fivell** [comment]
@Nattfodd, I don't know , did you notice something ?

**Comment by Nattfodd** [comment]
@Fivell we use older version of APNS2 in our production (https://github.com/rpush/rpush/pull/315) and from time to time some threads with APNS2 applications crash. Rpush keeps working, in general, but notifications for these particular apps that have been crashed stop being delivering until complete rpush daemon restart. I've enabled debugging mode to watch what's going on when thread crashes, and I see these kind of errors:

```
[2017-03-13 12:00:09] [ERROR] SocketError, Socket was remotely closed
/home/***/shared/bundle/ruby/2.1.0/bundler/gems/rpush-9043da6b93b1/lib/rpush/daemon/dispatcher_loop.rb:27:in `pop'
/home/***/shared/bundle/ruby/2.1.0/bundler/gems/rpush-9043da6b93b1/lib/rpush/daemon/dispatcher_loop.rb:27:in `block (2 levels) in start'
/home/***/shared/bundle/ruby/2.1.0/bundler/gems/rpush-9043da6b93b1/lib/rpush/daemon/dispatcher_loop.rb:26:in `loop'
/home/***/shared/bundle/ruby/2.1.0/bundler/gems/rpush-9043da6b93b1/lib/rpush/daemon/dispatcher_loop.rb:26:in `block in start'
```

But, as I said, this is an issue for initial APNS2 code. Since then APNS2 code has been changed a lot, so I don't think this is the same thing.
