### ISSUE TITLE
70mb log file when using gem from master branch

### ISSUE THREAD

**Issue by Fivell** [rpush/rpush#343]
Hello, why this file needed ? https://github.com/rpush/rpush/blob/master/log/rpush.log

**Comment by Fivell** [comment]
cc @amaierhofer

**Comment by aried3r** [comment]
This was probably committed by accident, can be deleted and the `log/` directory added to `.gitignore` (unless it's expected to exists and not created if it isn't). However, I think we can't make the repository smaller for future clone operations, as this file now exists in the history and will always be there as long as it's reachable.

AFAIK you can only remove files permanently by rewriting the history of the repository which is a destructive operation.

**Comment by Fivell** [comment]
@aried3r, because 3.0 is not released at the moment we use master branch, and our bundle directory is + 70 mb because of this

**Comment by aried3r** [comment]
You can subscribe to #344 if you want where this will be fixed. I'm not sure exactly how bundler does it, but I guess if you specify a branch or git ref it will only download that ref instead of the whole repository + history, so this should fix your issue.

Thanks for reporting!

**Comment by MSchmidt** [comment]
Regarding this, why not release a 3.0 beta, so we don't need to pull the full repo?

**Comment by aried3r** [comment]
I stand corrected, I checked the bundler source code and issues and from a quick glance it seems it does in fact download the whole repository. See https://github.com/bundler/bundler/issues/228 and https://github.com/bundler/bundler/issues/4556.

@MSchmidt, a beta is a good idea, but only @ileitch can cut a new release.

/cc @ileitch think we can have a beta release of 3.0.0?

**Comment by aried3r** [comment]
@MSchmidt 3.0.0.rc1 is released which should resolve your issue.
