### ISSUE TITLE
Auto switch APNS certificate based on rails env

### ISSUE THREAD

**Issue by NeoElit** [rpush/rpush#347]
Is there any way to setup APNS certificate path & password that depend on Rails env?
Based on "Readme" I'll have to have different apps on each of different environments. Is it the recommended way or am I missing any better methods?

Also is it advisable to have the certificate password without any encryption in the database?

**Comment by Nattfodd** [comment]
You can use Rpush::App names to quickly distinguish applications for a proper environment. For example:
```ruby
# Kinda pseudocode for short:
Rpush::Apns::App.create(
  name: 'apns_development',
  certificate: File.read('certificate.pem'),
  environment: 'development'
)
Rpush::Apns::App.create(
  name: 'apns_production',
  certificate: File.read('certificate.pem'),
  environment: 'production'
)

# And then you find the proper app using Rails.env:
Rpush::App.find_by_name("apns_#{Rails.env}")
```

**Comment by NeoElit** [comment]
@Nattfodd Thanks, that will do.

**Comment by NeoElit** [comment]
@Nattfodd  Had one more doubt. Will rpush be copying the content from certificate file while creation of the app or does that certificate has to be at the mentioned location always?

**Comment by NeoElit** [comment]
I can find certificate data from Rpush::Apns::App certificate column. Guess no need then.
