### ISSUE TITLE
[Question] How to send Rich notifications ? 

### ISSUE THREAD

**Issue by Michaelvilleneuve** [rpush/rpush#349]
From what I've seen it seems that all I need is to add specific data to the payload of the request. But there is very few documentation about it. Has anyone achieved this with Rpush ?
Thanks

**Comment by aried3r** [comment]
I don't know how to do it specifically for iOS, but you need the `mutable_content` field in the payload which is currently only supported if you use the master branch version of rpush.

https://github.com/rpush/rpush/commit/71ba8181fa7fe13d3f0d8b4300ae255b47795c88

**Comment by aried3r** [comment]
This has been released now in 3.x. Please feel free to open a new issue if you feel this was not resolved.
