### ISSUE TITLE
APNS2 Support in Version 2.7.0 and 3.0.0

### ISSUE THREAD

**Issue by gregblake** [rpush/rpush#350]
I'm curious about the road map for APNS2 support, and am hoping someone can provide additional insight on this.

According to the [readme](https://github.com/rpush/rpush/blob/a49f714c74743068d496c0c7a69a7040986e7254/README.md#create-an-app--notification), you can replace `Rpush::Apns::App` with the new API `Rpush::Apns2::App`. This looks to be incorrect on version 2.7: using `Rpush::Apns2::App` on version 2.7.0 returns a `NameError: uninitialized constant Rpush::Apns2`.

From what I can tell, the [version 2.7.0](https://github.com/rpush/rpush/tree/v2.7.0/lib/rpush/client/active_record) does not support APNS2, and it looks to be on the road map for [version 3.0.0](https://github.com/rpush/rpush/blob/master/lib/rpush/client/active_record/apns2/app.rb). 

Is the above correct? 

If so, I'd be happy to provide a quick update to the README, with details on the APNS2 support in rpush 2.7.0 and 3.0.0.

Thanks!

**Comment by soulfly** [comment]
Here it is
https://github.com/rpush/rpush/blob/master/CHANGELOG.md

**Comment by gregblake** [comment]
Thank you!
