### ISSUE TITLE
missing time_to_live field in GCM ?

### ISSUE THREAD

**Issue by fertobar** [rpush/rpush#352]
I'm working on PNs with rpush **2.7.0**, and I notice when I log the payload for FCM the **time_to_live** is not there.
The PN is sent ok and other fields like expiry, category, etc are in the payload with the correct values except time_to_live.

I set time_to_live when I create the notification like:
```
Rpush::Gcm::Notification.create({
    ...
   time_to_live:   1800,
   ....
})
```
do you know if there is a reason for that field that is ignored, or could be an issue?

thanks in advance! 

ref:
GCM:
https://developers.google.com/cloud-messaging/http-server-ref
FCM
https://firebase.google.com/docs/cloud-messaging/concept-options#ttl

**Comment by Nattfodd** [comment]
I believe it is called `expiry` in Rpush.

https://github.com/rpush/rpush/blob/644ba8fd5372aa974eb42c1db42a1ebf8ed35604/lib/rpush/client/active_model/gcm/notification.rb#L47

**Comment by fertobar** [comment]
thanks @Nattfodd ! make sense now
