### ISSUE TITLE
getaddrinfo: Name or service not known error

### ISSUE THREAD

**Issue by ikbenben** [rpush/rpush#357]
For the last week we have started to receive a Name or service not known error intermittently. There are a lot of successful rpush notifications being sent so it is not a configuration issue.

The last reported issue was at 14:17 UTC today and if I look at the rpush_notifications table, I do not see any notifications that were created at that time or any that have a failed_at timestamp for that time (nor a matching delivered_at timestamp).

The stack trace is as follows:
```
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:137:in `initialize'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:137:in `new'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:137:in `connect_socket'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/tcp_connection.rb:40:in `connect'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:57:in `check_for_feedback'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:32:in `block (2 levels) in start'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `loop'
vendor/bundle/ruby/2.1.0/gems/rpush-2.7.0/lib/rpush/daemon/apns/feedback_receiver.rb:30:in `block in start'
```

There has not been any new builds to our environment in the past month and we are using version 2.7.0 of the gem.

Not sure where to look to try to resolve this. Any suggestions?

**Comment by Shawn-Xiao** [comment]
I am currently using Houston gem to Push Notification. I am also struggle with this getaddrinfo: Name or service not known error. It happens sometimes without any reason. I am using a developement certificate and environment. Hope someone can figure out what's happening..

**Comment by hmistry** [comment]
+1 Ideas?

**Comment by Nattfodd** [comment]
We also faced with issue with some old clients using old apns protocol. So I suggest maybe this is some sign of deprecation of the feedback service?

**Comment by aried3r** [comment]
Closing since this doesn't seem to be a problem of rpush itself.
