### ISSUE TITLE
Status of APNS2?

### ISSUE THREAD

**Issue by hmistry** [rpush/rpush#360]
Hi 

What's the status of APNS2 implementation? Is it ready for production use or working well enough but not yet battle proven? Can I use the master branch?

I'm having issues with old APNS regarding connection closed due to invalid tokens and it seems the feedback API is not handling it properly... anyways would like to move to improved APNS2.

I appreciate your thoughts. Thank you.

**Comment by Nattfodd** [comment]
We use APNS2 on production for 6 months already, so.. probably yes, it's production ready.

**Comment by chris** [comment]
We were using it, but abandoned due to callback issues. However, that appears to be fixed (I haven't tested), see this issue: https://github.com/rpush/rpush/issues/339

**Comment by hmistry** [comment]
@Nattfodd Thats good to hear. Does the feedback API work well for invalid tokens? (Assume I delete the invalid token in feedback api.)  Does APNS2 keep resending the batch removing the one bad token only to have another fail or is it designed better?

@chris Thanks for sharing. We'll evaluate it and I'll post how it goes.

**Comment by sveredyuk** [comment]
Hey guys, I am trying to move from APNS to APNS2. For APNS I used certificate, If I correctly understand the doc, everething that I should to change app from Apns to Apns2 and change certificate entry ?

**Comment by aried3r** [comment]
Closing since both APNS2 and APNSP8 have been implemented.
