### ISSUE TITLE
APNS key support

### ISSUE THREAD

**Issue by lolgear** [rpush/rpush#369]
Apple added keys that doesn't expire. ( awesome! )

Does RPush support these keys?

**Comment by Nattfodd** [comment]
Can you please explain in details, what keys?

**Comment by lolgear** [comment]
https://developer.apple.com/videos/play/wwdc2016/724/

https://stackoverflow.com/questions/39943701/how-to-send-apns-push-messages-using-apns-auth-key-and-standard-cli-tools

**Comment by Nattfodd** [comment]
Still not sure what are you talking about, but from this presentation:

HTTP/2 protocol works with certificates-based authentication (use master branch), does not work with JWT tokens (unimplemented).

**Comment by soulfly** [comment]
I guess @lolgear is talking about JWT tokens that can be used instead of push certificates.

So @Nattfodd is right

**Comment by troya2** [comment]
This would be a great addition to the library.  Non expiring keys are so much more practical for a production system.  One less thing to deal with every year.

**Comment by aried3r** [comment]
I'm not completely sure since I don't use APNS, but I think this is part of #386.

**Comment by aried3r** [comment]
I think this has been done and released.
