### ISSUE TITLE
Unable to deliver notification 27, received error 400 (GCM failed to parse the JSON request. Possibly an Rpush bug, please open an issue.

### ISSUE THREAD

**Issue by sveredyuk** [rpush/rpush#370]
Hi, I am using Redis as backend for rpush:

This is one of rpush in redis record:
`
#<Rpush::Client::Redis::Apns::Notification:0x0000000c739f40 @attributes={"id"=>27, "badge"=>nil, "device_token"=>"80AE9B9E8952671CA37F48F260C3E9937A16177EB59E13B0905EA588BBE76E87", "sound"=>"default", "alert"=>"TEST8 ALL", "data"=>{"push_notification_id"=>602}, "expiry"=>86400, "delivered"=>false, "delivered_at"=>nil, "failed"=>true, "failed_at"=>2017-07-17 17:11:58 +0000, "fail_after"=>nil, "retries"=>0, "error_code"=>400, "error_description"=>"Unable to deliver notification 27, received error 400 (GCM failed to parse the JSON request. Possibly an Rpush bug, please open an issue.)", "deliver_after"=>nil, "alert_is_json"=>nil, "app_id"=>14, "collapse_key"=>nil, "delay_while_idle"=>nil, "registration_ids"=>nil, "uri"=>nil, "priority"=>nil, "url_args"=>nil, "category"=>nil, "content_available"=>false, "notification"=>nil, "type"=>"Rpush::Client::Redis::Apns::Notification", "push_notification_id"=>602, "device_id"=>12143}, @changed_attributes=nil, @new_record=false>
`

**Comment by L3K0V** [comment]
Hello, It looks like that the rpush JSON for the Firebase contains an extra (deprecated already) which are causing the problem.

In a fork of the project I created I was able to fix this error and added support for topics:
https://github.com/L3K0V/rpush/commit/881987dc73f0c430e6e803242a7d473f9bad40e0#diff-07f36eb5322b38eec3f476e77104b305L46

**Comment by oliveriobw** [comment]
Using Rpush::Gcm::Notification (v5.0.0) this was causing this same crash
`n = Rpush::Gcm::Notification.new  `
`  n.data = {"from"=>"b8031295-6982-40d2-b92c-4ae64effcd1e"} `
After renaming the "from" key to something else (ie "pfrom") did it work!

**Comment by aried3r** [comment]
Reopening as this now seems to have repro steps. I haven't yet confirmed this myself however.
