### ISSUE TITLE
Missing version 2.8.0

### ISSUE THREAD

**Issue by cupofjoakim** [rpush/rpush#373]
Had some trouble reinstalling all my gems on my workstation when my head project cried out that it couldn't download a dependency. It's about rpush @ v2.8.0, which my git history says we've used the last 8 months. 

I'll try downgrading to 2.7.0 for now, but for peace of mind: Did 2.8.0 exist at some point?

**Comment by aried3r** [comment]
2.8.0 was never released, neither was "3.0.0" (I call whatever is currently in the `master` branch "3.0.0" right now). You can either use the `master` version or point your Gemfile to use a certain commit, which is probably a more stable approach.
