### ISSUE TITLE
rpush not working with Firebase Cloud Messaging

### ISSUE THREAD

**Issue by jitinnagpal1989** [rpush/rpush#374]
Rpush is working fine for APNS, but does not work for Firebase push notifications. I followed the steps and added my registration is as  `n.registration_ids = ["123"]`, it saves notification in rpush table but it is never sent, and gives no error.

**Comment by aried3r** [comment]
We've successfully been using rpush with FCM ever since it was released.

Are you sure you're [running rpush](https://github.com/rpush/rpush#running-rpush)?

Also please give more information about your setup. Rpush version, Ruby version, Rails version, are you using ActiveRecord, Redis for the notifications etc.

**Comment by jitinnagpal1989** [comment]
I am using Ruby 2.3.4, Rails 4.2.4, yes I am using ActiveRecords. I am running RPush and it is working fine for Apple notifications. I am using GCM for device_type = android and then it stops to work. It saves the notification in rpush table but never sends it.
Relevant code:
```
def initialize_apps
if !Rpush::Apns::App.find_by_name("ios_app")
         ios_app = Rpush::Apns::App.new
         ios_app.name = "ios_app"
         ios_app.certificate = File.read("cert.pem")
         ios_app.environment = Rails.env # APNs environment.
         ios_app.connections = 1
         ios_app.save!
       end
       if !Rpush::Gcm::App.find_by_name("android_app")
         android_app = Rpush::Gcm::App.new
         android_app.name = "android_app"
         android_app.auth_key = "SERVER-KEY"
         android_app.connections = 1
         android_app.save!
       end

def send_android_notification(notification,device)
      android_notification = Rpush::Gcm::Notification.new
      android_notification.app = Rpush::Gcm::App.find_by_name("android_app")
      android_notification.registration_ids = ["very long device identifier"]
      message = "test"
      android_notification.data = {message: message}
      android_notification.notification = {"title":"[rails test title]","body":"[add your message]"}
      android_notification.save!
end
end
```

**Comment by jitinnagpal1989** [comment]
I solved issue by downgrading gem 'net-http-persistent', '2.9.4'. It never gave any error earlier but when i forced 'rpush push', it gave error that 
> Exception raised during startup. Notifications will not be delivered for this app
I downgraded gem net-http-persistent to 2.9.4, worked like a gem

**Comment by aried3r** [comment]
Rpush 3.0.0.rc1 is released which should resolve your issue.
