### ISSUE TITLE
n.registratin_id

### ISSUE THREAD

**Issue by flaviolpgjr** [rpush/rpush#376]
Hello, I have a question, I'm sorry if it's a simple question, in n.registration_ids, you must pass a token, how is that token obtained?
Every time I send the notification, I get the error: Errors: InvalidRegistration.
Thank you

**Comment by aried3r** [comment]
You get the token from the FCM server response. Your clients have to register with FCM, get the token, send the token to your server and then you can use it to send out notifications.

For Android for example, you can follow this guide. https://firebase.google.com/docs/cloud-messaging/android/client#sample-register

**Comment by flaviolpgjr** [comment]
Thank you!
