### ISSUE TITLE
Scheduled notifications

### ISSUE THREAD

**Issue by tudormunteanu** [rpush/rpush#383]
Is there a way to scheduled a notification to be sent at a particular time?

**Comment by aried3r** [comment]
You'll have to use the scheduler of your choice to do that. See also my answer here https://github.com/rpush/rpush/issues/337#issuecomment-281059440

**Comment by ileitch** [comment]
You can try setting `deliver_after`, though I don't remember if that'll work because it's typically used by the retry mechanism.
