### ISSUE TITLE
rpush stops working after several hours of activity

### ISSUE THREAD

**Issue by gdeglin** [rpush/rpush#39]
I have an rpush instance running on a server with several dozen Rpush::Apns (Sandbox & production) and Rpush::Gcm apps. It also polls the APNS feedback service every 180 seconds.

After around 24 hours, rpush appears to stop working and no longer writes anything to the log file. Restarting it resolves the problem, but of course this is not a good long term solution.

I attached GDB to the process and ran rb_backtrace. Here is the output:

	from /var/www/APP/shared/bundle/ruby/2.1.0/bin/rpush:23:in `<main>'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bin/rpush:23:in `load'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/bin/rpush:36:in `<top (required)>'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon.rb:61:in `start'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon/feeder.rb:14:in `start'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon/feeder.rb:32:in `feed_forever'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon/feeder.rb:32:in `loop'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon/feeder.rb:34:in `block in feed_forever'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon/interruptible_sleep.rb:26:in `sleep'
	from /var/www/APP/shared/bundle/ruby/2.1.0/bundler/gems/rpush-b6ea10de660e/lib/rpush/daemon/interruptible_sleep.rb:26:in `select'

This seems to indicate that it's stuck in this code, on line "rs, = IO.select(read_ports, nil, nil, timeout) rescue nil"

    def sleep(timeout)
        read_ports = [@sleep_reader]
        read_ports << @udp_wakeup if @udp_wakeup
        rs, = IO.select(read_ports, nil, nil, timeout) rescue nil

        # consume all data on the readable io's so that our next call will wait for more data
        perform_io(rs, @sleep_reader, :read_nonblock)
        perform_io(rs, @udp_wakeup, :recv_nonblock)

        !rs.nil? && rs.any?
      end

I also tried attaching to the process using your Hijack tool, but couldn't get it working.

**Comment by dzubi** [comment]
I get the same problem with rpush 2.4.0 and 2.5.0 on ruby 2.1.0.
After several days and processing thousands of notifications, the daemon process suddenly stops working.
The process does not react to SIGTERM signal, I have to use SIGKILL to terminate it.

Has the cause for this problem been found?
