### ISSUE TITLE
Send picture in push notification

### ISSUE THREAD

**Issue by chaitanya-nyros** [rpush/rpush#395]
I am unable to send image in notification. Following is my configuration.

`		n = Rpush::Gcm::Notification.new
		n.app = Rpush::Gcm::App.find_by_name("AppName")
		n.registration_ids = [device_id]
		n.data = { message: "Some message" }
		n.priority = 'high'
		n.content_available = true
		n.notification = { body: 'great match!', title: 'Portugal vs. Denmark', picture: 'picture_url', style: 'picture' }
		n.save!
		Rpush.push`

Please let me know is it possible to send image using this gem 

Thanks.

**Comment by chaitanya-nyros** [comment]
Ping

**Comment by aried3r** [comment]
I do not see a `picture` payload in the notification part in the documents, can you point me to where you found it?

https://firebase.google.com/docs/cloud-messaging/http-server-ref

**Comment by aried3r** [comment]
Closing for now. I'll re-open if necessary.
