### ISSUE TITLE
support for mongoid orm

### ISSUE THREAD

**Issue by ileitch** [rpush/rpush#4]
_Pull request by **[kwojtaszek](https://github.com/kwojtaszek)** from Wednesday Jul 24, 2013 at 18:07 GMT_
_Originally opened as https://github.com/ileitch/rapns/pull/146_

----

Draft of code that add support for mongoid orm

----

_**[kwojtaszek](https://github.com/kwojtaszek)** included the following code: https://github.com/ileitch/rapns/pull/146/commits_

**Comment by pencilcheck** [comment]
+1

**Comment by 23tux** [comment]
I began with this integration, but didn't come very far (too less time since November). Anyone else who tried it?

**Comment by ileitch** [comment]
I've started, I'll let y'all know when it's ready to test.

**Comment by ileitch** [comment]
Just pushed this to master, can you please give it a try?

```ruby
gem 'rpush', github: 'rpush/rpush'
gem 'rpush-mongoid'
```

**Comment by 23tux** [comment]
Awesome, thanks! I'll give it a try and let you know how it works ;)

**Comment by pencilcheck** [comment]
How's the test result?
