### ISSUE TITLE
Upgrade from 2.7 to 3.0, application side changes.

### ISSUE THREAD

**Issue by Ritesh-Katare** [rpush/rpush#406]
I want to upgrade Rpush to 3.0 which is a backwards incompatible.
Please help me with changes i have to do before and after upgrading Rpush. 
I am using
Rpush 2.7.0
Rails 4.2.6
Ruby 2.3.1

**Comment by nattfodd** [comment]
Breaking changes in 3.0:

> **Breaking:** Dropped support for old Rubies and Rails versions. rpush 3.0 only supports Ruby versions 2.2.2 or higher and Rails 4.2 or higher. (#366 by @aried3r)
> 
> **Breaking:** Dropped MongoDB support because there was no one maintaining it. But we're open to adding it back in. (#366 by @aried3r)
> 
> **Breaking:** Dropped JRuby support. (#366 by @aried3r)

According to your environment and unless you're using MongoDB as a storage, you should not have any incompatibility issues.

**Comment by Ritesh-Katare** [comment]
@nattfodd Thanks man! I'm not using MongoDB.

From Rpush changelog https://github.com/rpush/rpush/blob/master/CHANGELOG.md#300rc1-2017-08-31
Make synchronizer aware of GCM and WNS apps, what does extra implementation is required?

**Comment by nattfodd** [comment]
I don't see any extra implementations requiter for that, that's about rpush internals.

**Comment by Ritesh-Katare** [comment]
After upgrading to 3.0, which is correct way to call APNS2
Rpush::Apns::Notification.new OR Rpush::Apns2::Notification.new?

**Comment by Ritesh-Katare** [comment]
I guess Rpush 3.0 Rpush::Apns::Notification.new will call Apns2 by default, Is it?

**Comment by nattfodd** [comment]
It should be both fine with Apns, but I would stick with `Rpush::Apns2::Notification` to match the app. The important part is to have `Rpush::Apns2::App` created instead of `Rpush::Apns::App`.

**Comment by Ritesh-Katare** [comment]
Thanks again @nattfodd.

**Comment by aried3r** [comment]
Don't forget
>When upgrading, don't forget to run `bundle exec rpush init` to get all the latest migrations.

I'm closing this since I think everything has been clarified. Thanks @nattfodd!

**Comment by Ritesh-Katare** [comment]
@nattfodd  @aried3r rake aborted!
Mysql2::Error: Table 'push_notifications' already exists: RENAME TABLE `apns notifications` TO `push_notifications`
After bundle exec rpush init and bundle exec rake db:migrate.
