### ISSUE TITLE
Rpush with systemctl

### ISSUE THREAD

**Issue by spaghetticode** [rpush/rpush#413]
I think the readme could be clearer about how to make rpush work nice with `systemctl`: unless you add the -f flag the command `rpush start` will not work correctly when supervised by systemctl. 

This happens because, as you correctly wrote, rpush deamonizes by default when started with `rpush start`. 

Having an explicit suggestion about `rpush start -f` for not daemonizing the service (and playing nice with systemctl) seems to me a good improvement to the readme.

I can open a PR for this, if it helps.

Of course, thank you very much for this great gem!

**Comment by aried3r** [comment]
@spaghetticode, I don't use rpush using systemctl but was actually planning to look into that. I – and I think many others as well – would be really grateful if you could improve the documentation on that.

**Comment by elieteyssedou** [comment]
I think we can close this issue because this argument exists : https://github.com/rpush/rpush/blob/master/lib/rpush/cli.rb#L19

Enjoy !

(may be it would be nice to update the documentation)

**Comment by aried3r** [comment]
Done with #478, thanks @elieteyssedou!

**Comment by elieteyssedou** [comment]
You are welcome ! 😁
