### ISSUE TITLE
APNS expiry should be number of seconds since epoch

### ISSUE THREAD

**Issue by loadhigh** [rpush/rpush#416]
https://github.com/rpush/rpush/blob/75863e6fea64cb892687a1d37c81a81cf1650e88/lib/rpush/client/active_model/apns/notification.rb#L84

In here the expiry with default of 86400 is effectively 0 and APNS will not resend the notification if the device is off.
`APNS_DEFAULT_EXPIRY` is not needed because the attribute has default value of 86400
`frame << [4, 4, expiry ? Time.now.to_i + expiry.to_i : 0].pack("cnN")`

**Comment by aried3r** [comment]
Hey! Thanks for looking into the code and opening issues :)
Are you using rpush already or just evaluating if you would?

I wondered, would you be up for opening a few PRs for that as well? No obligations, of course
