### ISSUE TITLE
Rpush 3 APNS app NoMethodError, undefined method `to_sym' for nil:NilClass Did you mean?  to_s

### ISSUE THREAD

**Issue by Ritesh-Katare** [rpush/rpush#418]
I have upgraded Rpush 2.7 to 3.0.2, When tried sending push notification got following error in Rpush log :

  Rpush::Client::ActiveRecord::App Load (0.3ms)  SELECT  `rpush_apps`.* FROM `rpush_apps` WHERE `rpush_apps`.`id` = 16 LIMIT 1
[2018-02-28 10:42:36] [1317761734] Starting 1 dispatcher... 
[2018-02-28 10:42:36] [ERROR] [1317761734] Exception raised during startup. Notifications will not be delivered for this app.
[2018-02-28 10:42:36] [ERROR] NoMethodError, undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/dispatcher/apns_http2.rb:17:in `initialize'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/service_config_methods.rb:34:in `new'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/service_config_methods.rb:34:in `new_dispatcher'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:174:in `new_dispatcher_loop'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:101:in `block in start_dispatchers'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:101:in `times'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:101:in `start_dispatchers'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:31:in `start_app'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:25:in `start_app_with_id'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:17:in `block in enqueue'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:16:in `each'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:16:in `enqueue'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:58:in `enqueue_notifications'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:48:in `block in feed_forever'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:47:in `loop'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:47:in `feed_forever'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:11:in `block in start'

**Comment by Ritesh-Katare** [comment]
This was due to environment is nil for apns app. After updating environment, error gone.

**Comment by Ritesh-Katare** [comment]
After fixing above, Got new error

[2018-02-28 10:58:39] [ERROR] URI::InvalidURIError, bad URI(is not URI?): 
/home/CityApp1/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:18:in `rescue in split'
/home/CityApp1/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:15:in `split'
/home/CityApp1/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
/home/CityApp1/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/net-http2-0.16.0/lib/net-http2/client.rb:18:in `initialize'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/dispatcher/apns_http2.rb:18:in `new'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/dispatcher/apns_http2.rb:18:in `initialize'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/service_config_methods.rb:34:in `new'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/service_config_methods.rb:34:in `new_dispatcher'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:174:in `new_dispatcher_loop'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:101:in `block in start_dispatchers'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:101:in `times'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:101:in `start_dispatchers'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:31:in `start_app'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:25:in `start_app_with_id'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:17:in `block in enqueue'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:16:in `each'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/app_runner.rb:16:in `enqueue'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:58:in `enqueue_notifications'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:48:in `block in feed_forever'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:47:in `loop'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:47:in `feed_forever'
/home/CityApp1/.rvm/gems/ruby-2.3.1/gems/rpush-3.0.2/lib/rpush/daemon/feeder.rb:11:in `block in start'

**Comment by Sohair63** [comment]
@Ritesh-Katare  did you get this fixed? I am also getting the same.

I am using `Rpush::Apns2::Notification` with `Rpush::Apns2::App`

When **environment: "sandbox"**
```
[ERROR] [ios__app] Exception raised during startup. Notifications will not be delivered for this app.
[ERROR] URI::InvalidURIError, bad URI(is not URI?): 
```


When **environment: "production"**
```
[ERROR] Errno::EPIPE, Broken pipe
```

Any suggestion that where I am doing it wrong?
