### ISSUE TITLE
Does this gem support apns-collapse-id?

### ISSUE THREAD

**Issue by superchen14** [rpush/rpush#422]
IOS10 notification can support collapse function via apns-collapse-id request header (see [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW13))

Does this gem support apns-collapse-id?

**Comment by superchen14** [comment]
@ileitch it's seems the implementation of rpush following APNs legacy binary interface. So there is not chance to implement apns-collapse-id in this gem.

**Comment by ileitch** [comment]
@superchen14 https://github.com/rpush/rpush/blob/master/lib/rpush/daemon/apns2/delivery.rb

**Comment by superchen14** [comment]
@ileitch thanks for showing me this code, after research I find out the latest gem support "apns-collapse-id". Here is the sample code.
 
```
app = Rpush::Apns2::App.new
app.name = "ios_app"
app.certificate = File.read("/path/to/cert/cert.pem")
app.environment = "production"
app.connections = 1
app.save!

Rpush.embed # to deliver in console on notification save

n = Rpush::Apns2::Notification.new
n.app = app
n.alert = "hello"
n.device_token = "TOKEN" # replace TOKEN with ios device token
n.data = {'headers' => { 'apns-topic' => "com.ios.app", "apns-collapse-id" => "***" }} # replace com.ios.app with ios app bundle id
n.save!
```
