### ISSUE TITLE
Rpush3 rpush_notification processing flag

### ISSUE THREAD

**Issue by Ritesh-Katare** [rpush/rpush#424]
After trying to send notifications rpush updates flags failed, delivered on basis of status of delivery.
There is one more flag ie. 'processing', what is it meant for?

Rpush retries only for notifications which has processing flag false.
But there are notifications in rpush_notifications table which has failed, delivered is zero and processing as 1.

@aried3r @nattfodd

**Comment by benrugg** [comment]
@Ritesh-Katare, I believe the processing state is used internally by rpush when it grabs a batch of notifications to send out. So `processing` == true would be notifications that are currently in memory and will be sent out. I haven't seen a case where `processing == true` and `failed == true`
