### ISSUE TITLE
Reconsider removing Gemfile.lock from repo

### ISSUE THREAD

**Issue by hmistry** [rpush/rpush#425]
This is in regards to the following commits: https://github.com/rpush/rpush/commit/ff9a3dd39b5a25ca099886d5166dac24f23b9b64 and https://github.com/rpush/rpush/commit/ff9a3dd39b5a25ca099886d5166dac24f23b9b64

@aried3r Yehuda's recommendations to not check-in the lock file made sense at the time when locking dependencies was not a big practice, and it made sense to place the burden of having the CI's test the gem with latest dependencies. However it had an unforeseen side effect where new gem contributors had to deal with broken installs, thus discouraging them from contributing.

The Bundler team have reconsidered this recently and have changed the new gem templates to include Gemfile.lock in the repo. Given the state of things today, they felt it to be more important to have new contributors contributing and reduce hurdles for them. This can be achieved without trading off CI checks against latest dependencies because you can run the test suite twice, once with the lock file and second without the lock file. See this article: http://bundler.io/blog/2018/01/17/making-gem-development-a-little-better.html

Let's make it easier for new contributors to get a working setup quickly.

**Comment by aried3r** [comment]
Great! I kinda thought the article was outdated but didn't stumble across your article back when I did the commit. I'll definitely re-add the `Gemfile.lock`. (Also grateful for PRs, haha)

I have two questions if that's ok. Is there anything we can do looking forward to Bundler 2.0 with `gems.rb`? Also, is the discussion David Rodriguez brought up available anywhere? I'd love to read up on that, your blog entry only mentions it, not sure if it happened on Discord, Slack, Github, real life.

**Comment by hmistry** [comment]
Regarding `gem.rb`, it seems bundler 2.0 will support it but `Gemfile` will still remain.

There was some discussions in Slack but I got more info talking to him and Andre directly. This gist of it is in the comment above. It's always nice to learn the context.

**Comment by aried3r** [comment]
Hey, I'm planning to do this this week. Seeing as you are the author of the article, what is your opinion regarding CI? Using option 1 (`rm Gemfile.lock`) or option 2 (bot)?

**Comment by hmistry** [comment]
Option 2 with Dependabot is a really nice because it'll generate a PR like this [example](https://github.com/greysteil/ruby-test/pull/4) and you simply merge it. The downside is other PR's are not tested against latest dependencies.

I personally prefer option 1 but instead of removing the Gemfile.lock, have 2 Gemfiles - one with a lock and the other without. The trade-off with this is travis will run the tests twice but from a dev perspective, it's a lot clearer to see that tests passing with locked versions and tests not passing with latest versions of dependencies in each PR. See this [example repo](https://github.com/hmistry/travistest) and Travis can be configured like:

```
gemfile:
  - Gemfile
  - Gemfile.latest
```

**Comment by hmistry** [comment]
There's no set convention. People in Bundler team don't ship specs with the gem. With Readme's it's a toss up - it depends on what percentage of your users open the installed the gem directory to read documentation and code vs going to the github repo.
