### ISSUE TITLE
what is app.auth_key?

### ISSUE THREAD

**Issue by umair50** [rpush/rpush#431]
I am trying to use this gem with firebase and for auth_key i have tried all the following from firebase

Web API Key
Server key

 but i get the error

 Rpush::DeliveryError, Unable to deliver notification 5, received error 401 (Unauthorized, check your App auth_key.

**Comment by aried3r** [comment]
Hi! I explained this here https://github.com/rpush/rpush/issues/346#issuecomment-289218776, please do test with Postman or similar tool like HTTPie to verify everything works. This shouldn't be an Rpush issue I think.

But I guess we should document it somewhere.
