### ISSUE TITLE
FCM && Emoji

### ISSUE THREAD

**Issue by Exact1990** [rpush/rpush#432]
Problem with displaying emoji on android devices:

n = Rpush::Gcm::Notification.new
n.app = Rpush::Gcm::App.find_by_name("android")
n.registration_ids = ["token"]
n.data = {:action=>"", :extraId=>nil, :timestamp=>Time.current.to_i, :title => "Заголовок 😉", :message=>nil, :sound => 'default'} 
n.priority = 'high'
n.sound='default'
n.content_available = true # Optional
n.save!

![screenshot_20180503-092819](https://user-images.githubusercontent.com/2375793/39560086-7fc3f96c-4eb4-11e8-874b-6847a51a7eee.png)

When sending a message through online services, emoji is displayed correctly:

![screenshot_20180503-093341](https://user-images.githubusercontent.com/2375793/39560152-0f2bb5d6-4eb5-11e8-8e72-1dfcf94ee7d9.png)

**Comment by Exact1990** [comment]
Found the cause: https://github.com/rails/rails/issues/3727

**Comment by aried3r** [comment]
Hey! Glad you found a solution. Would you like to share your solution so others can profit it from it if they stumble upon this in the future? :)

Saying that, I couldn't reproduce this on our setup.

**Comment by Exact1990** [comment]
This problem appears to be common in older rails versions (up to 3.3). The solution in the form of a monkey-patch describes on the url page
