### ISSUE TITLE
Rpush to iOS with FCM

### ISSUE THREAD

**Issue by wedercm** [rpush/rpush#434]
I would like to use FCM rather than APNS to send iOS notification. Is it possible?

I configured APP iOS in FCM and tried to send notification using Rpush like I send to Android app. But isn't worked. I'm doing as in the example below

````
n = Rpush::Gcm::Notification.new
n.app = Rpush::Gcm::App.find_by(name: 'ios')

n.registration_ids = [device_token]
n.data = { title: 'Title', message: 'Message' }

n.save!
````

**Comment by aried3r** [comment]
Yes, it's definitely possible, we use it in production.

I think you have to set `title` and `body` in the notification payload, not the `data` payload.

Something like this should work:
```Ruby
n.notification = { title: 'Title', body: 'Body' }
```

**Comment by aried3r** [comment]
Closing. Feel free to reply if you think your issue is not solved by Rpush.
