### ISSUE TITLE
How to Set Redis Keys to Expire?

### ISSUE THREAD

**Issue by gregblake** [rpush/rpush#436]
Our application is configured to use Redis with Rpush. The Redis keys are not expiring, which is causing memory usage growth over time.

In order to limit this growth, we've considered adding a scheduled task to prune old keys, but have also discussed configuring Rpush such that keys will [expire](https://redis.io/commands/expire) after a certain amount of time.

Is having keys expire after a certain amount of time something that can be configured via [Rpush.config.redis_options](https://github.com/rpush/rpush/blob/644ba8fd5372aa974eb42c1db42a1ebf8ed35604/spec/unit/configuration_spec.rb#L41-L45), or otherwise?

Thank you.

**Comment by aried3r** [comment]
Hey! Sorry for the long silence. I am not using Redis myself and haven't written any of the redis integration code of Rpush. There was recently a similar request and an additional section was added to the README and Wiki. https://github.com/rpush/rpush#cleanup

Hope this helps!

**Comment by gregblake** [comment]
That looks like a great solution. Much appreciated, @aried3r.
