### ISSUE TITLE
Rpush Memory Leak

### ISSUE THREAD

**Issue by armahmoudi** [rpush/rpush#439]
I'm using the CLI to run an Rpush daemon and i'm using Redis. It appears that the Rpush daemon has a memory leak which causes the process to consume more and more memory until the instance runs out of memory, then it causes notifications to be dropped (they stay in the queue but won't get a success/failure update), and sometimes get stuck in the internal queue.

These issues don't happen if there's memory available, but as soon as the host starts swapping the daemon has a hard time delivering notifications and eventually gets stuck.

**Comment by aried3r** [comment]
Does Rpush use more and more memory or Redis? Redis is a known "issue", it was recently added as a gotcha in the README https://github.com/rpush/rpush#cleanup

**Comment by armahmoudi** [comment]
@aried3r I'm talking about the application memory on the server, not Redis. I was aware of notifications not being cleaned up from Redis and had put a mechanism to destroy each notification on any success/failure reflection. That part works great as long as the application doesn't run out of memory.

**Comment by armahmoudi** [comment]
@aried3r I'm trying to use Rpush for all of our Push Notifications at Tesla, and this is the main blocker to take it to production right now. Would appreciate any help I can get. Would be happy to contribute to the repository as well once we do find the issue.
Right now I'm trying to detect what's the cause of this growing memory usage on the process, and my suspicion is on the feeder and dispatchers.

**Comment by aried3r** [comment]
Hey! Sorry for the silence, I was gone for the week.

Hmm, that's really strange. I haven't seen that behaviour before in production and you're the first to report it, but maybe you use it at a different scale at Tesla :)
But I am also not using Redis but Postgres for persistence with FCM. Could you describe your setup in more detail (Ruby, Rpush version etc)?

Sadly I don't have a lot of insight in how the feeders and dispatchers work exactly, all credit goes to @ileitch and contributors. But I'll monitor our own daemons more closely in the coming weeks to see if I experience the same issue. Sorry that I can't help more right now :\

**Comment by armahmoudi** [comment]
@aried3r could it be that the [InterruptibleSleep](https://github.com/rpush/rpush/blob/master/lib/rpush/daemon/interruptible_sleep.rb#L5) is leaking dead threads?

**Comment by aried3r** [comment]
It could be, but if I read the code and your heap dumps somewhat correctly, there's only `Kernel.sleep` "in" the threads, but it leaks the most memory. But judging from the ref counts, it might be modis (but might just be because of the number of notifications).

I did a bit of googling, and it could be that the values of the thread are [being retained](https://gist.github.com/ryanlecompte/3281509#gistcomment-392677), maybe returning `nil` at the end of the block is already enough? Could be that or that `@thread` is being retained, but I don't see how, since it's set to `nil` when killed.

Interestingly enough, there's a different implementation by @ileitch in a [gist](https://gist.github.com/ileitch/1459987).

Sadly I don't currently have the time to look more into it. :\

**Comment by armahmoudi** [comment]
@aried3r I ran a memory benchmark and it seems like we need to set `@thread = nil` at the end of each `stop` as well: https://github.com/rpush/rpush/pull/441

**Comment by aried3r** [comment]
3.2.1 is now released https://rubygems.org/gems/rpush

Mind taking it for a spin so we can confirm this is indeed fixed?

**Comment by armahmoudi** [comment]
made it a little better, but not good enough. The Modis model attributes are still retained for some reason.

**Comment by aried3r** [comment]
Oh, that's too bad :\
Do you think it's a bug within rpush, retaining instances of objects or is it within modis?

**Comment by armahmoudi** [comment]
@aried3r I think this is an issue with Modis.
The top two memory retainers are Modis and Msgpack which Modis uses.
```
/vendor/bundle/ruby/2.4.0/gems/msgpack-1.2.4/lib/msgpack.rb:34
/vendor/bundle/ruby/2.4.0/gems/modis-2.1.0/lib/modis/attribute.rb:102
```
