### ISSUE TITLE
Relax jwt version dependency

### ISSUE THREAD

**Issue by jsantos** [rpush/rpush#446]
Context: https://github.com/rpush/rpush/pull/444#issuecomment-404892133

We should set the dependency as `s.add_runtime_dependency 'jwt', '>= 1.5.6'` in order to ensure support of older versions of `jwt` (and gems depending on it).

**Comment by sposinff** [comment]
Thank you! (I would be happy to do it, but I can't quite get the rpush tests to run locally)

**Comment by aried3r** [comment]
Just submit a PR, let Travis do the work :)

Not sure if we need a separate Gemfile for JWT 1 and 2.

**Comment by sposinff** [comment]
PR #447

**Comment by jsantos** [comment]
Guess it's also time to submit a PR to include development guidelines on the README (for those who aren't familiar with [Appraisal](https://github.com/thoughtbot/appraisal).

**Comment by aried3r** [comment]
@jsantos, good idea. Would you be up for that? :)

#447 is merged, closing.

**Comment by jsantos** [comment]
@aried3r Yup, I can add some basics there. I'll get a few guidelines from [Paperclip](https://github.com/thoughtbot/paperclip/blob/master/CONTRIBUTING.md)'s repo, as it looks pretty good to me.
