### ISSUE TITLE
APNS: delivery delayed by a day or more

### ISSUE THREAD

**Issue by CodingAnarchy** [rpush/rpush#450]
I'm seeing occassional cases where the delivery of APNS notifications is being delayed for a very long time, and I'm not seeing where this is coming from.  It definitely is somewhere in the Rpush library, though, as the notifications are generally working except for a few which end up having a `deliver_after` timestamp set 12+ hours after the notification record was created in ActiveRecord.

In the latest case, the fields are like so:

`deliver_after: "2018-08-09 20:19:40", created_at: "2018-08-07 23:46:13", retries: 2`

As far as I can understand from the code, the APNS notifications should only retry if there is a connection error, and the delay for that is only 10 minutes.  Can anyone help me find where this delay of 45 hours on 2 delays comes from?

Below is the full notification, with personal details scrubbed:

```
=> #<Rpush::Client::ActiveRecord::Apns::Notification id: 554474, badge: nil, 
device_token: "...", sound: nil, alert: "...", data: "{\"data\":\"...", expiry: 86400, 
delivered: true, delivered_at: "2018-08-09 20:19:40", failed: false, 
failed_at: nil, error_code: nil, error_description: nil, 
deliver_after: "2018-08-09 20:19:40", created_at: "2018-08-07 23:46:13", 
updated_at: "2018-08-09 20:19:40", alert_is_json: false, 
type: "Rpush::Client::ActiveRecord::Apns::Notification", collapse_key: nil, 
delay_while_idle: false, registration_ids: nil, app_id: 1, 
retries: 2, uri: nil, fail_after: nil, processing: false, priority: nil, 
url_args: nil, category: nil, content_available: false, notification: nil, 
mutable_content: false, external_device_id: nil>
```

Might be relevant:

Ruby: 2.5.1
Rails: 5.2.0
Rpush: 3.2.3

**Comment by benrugg** [comment]
I just deployed rpush on a medium size project (350k users), and I am seeing this, too. What I consistently see is a part of a batch (a few hundred notifications at a time) that get stuck in the processing state for hours or even days.

My guess is that the APNs connection occasionally hangs, and rpush doesn't have a timeout on it. Is there any way to add a connection timeout? Or return the backlogged notifications out of the processing state so that they can be picked up separately?

**Comment by CodingAnarchy** [comment]
Just to add my 2 cents, since I am still running into it and see a "live" batch stuck in processing right now.  It looks like @benrugg is correct and the messages get stuck in processing and just wait until a connection is restored.

I have since updated to Ruby 2.5.3, Rails 5.2.1, and Rush 3.2.4 without any change in behavior.

**Comment by benrugg** [comment]
Thank you for chiming in @CodingAnarchy. I have been monitoring this more closely in the last few days, and it happens in my application 10-20 times a day. It holds up the remaining notifications in that batch, and the reconnection delay duration has a wide range. Sometimes it continues to send after a few minutes, and sometimes a few hours. 

This was actually a bug in the last APNs library I was using, which was a big reason I switched over to rpush: https://github.com/grocer/grocer/issues/14

@aried3r, I would love if you could look into this when you have time. I would imagine it affects many people, even if they haven't noticed it yet.

(I'm hoping there's a quick fix by just setting a timeout for a given notification, and reconnecting after that)

**Comment by benrugg** [comment]
Oh, I am using the Apns8 connection. @CodingAnarchy, are you using that as well?

**Comment by CodingAnarchy** [comment]
@benrugg I am using the old Apns setup.  We haven't migrated to Apns8 yet.  I would suspect there is some common implementation that is the root of the issue if you are seeing it too.

**Comment by benrugg** [comment]
Good to know. That's interesting, because the two different Apns systems are very different. This definitely narrows down the places to start investigating...

**Comment by benrugg** [comment]
I think I may have fixed the issue (at least in my current application environment) by changing the number of Apns connections to 2. I had previously set it to 3 (in the `connections` field of the rpush app in the db).

@CodingAnarchy, are you using more than 1 connection?

**Comment by CodingAnarchy** [comment]
It looks like we are only using one connection:

```
irb(main):003:0> Rpush::App.find_by(name: 'ios_app').connections
=> 1
```

**Comment by benrugg** [comment]
Gotcha. I was hoping that would help track down the root cause. Thanks for the response!

**Comment by aried3r** [comment]
> @aried3r, I would love if you could look into this when you have time. I would imagine it affects many people, even if they haven't noticed it yet.

Hey! Sadly I cannot really help out with APNS, I haven't used it and have no way to test it. :\
APNS is one of the parts of this gem that heavily relies on community contributions.

**Comment by benrugg** [comment]
@aried3r, gotcha. I'll keep looking into it and see if I can improve anything.
