### ISSUE TITLE
RSpec error with mongoid

### ISSUE THREAD

**Issue by webmaster219** [rpush/rpush#454]
I'm using this gem with rpush-mongoid, but just got this error.
![image](https://user-images.githubusercontent.com/3008715/45946624-0597f300-c024-11e8-9d10-2951b19b5611.png)

Please let know me how can I solve this issue.

**Comment by webmaster219** [comment]
Hi @ileitch , please check this issue and solve me.

**Comment by venriq** [comment]
I think MongoDB support was removed on version 3. I tried spending some time adding the support back but the code was quite messy and I didn't feel proud of working on it.

**Comment by aried3r** [comment]
Yes, what @venriq said is true. MongoDB integration was unmaintained and I decided to drop it to move on with other features and releases.

If anyone wants to re-add integration, feel free to open a PR! I just cannot maintain it myself.
