### ISSUE TITLE
Error "Incorrect string value" with MySQL when inserting emojis

### ISSUE THREAD

**Issue by zedtux** [rpush/rpush#457]
Given I'm using MySQL and I'm writing a message including an emoticon :

```
  SQL (3.7ms)  INSERT INTO `rpush_notifications` (`type`, `app_id`, `device_token`, `alert`, `badge`, `data`, `created_at`, `updated_at`) VALUES ('Rpush::Client::ActiveRecord::Apns::Notification', 1, 'XXXXXXX44dda59cd089190b01a80afc87ee5d926650b893658dbdfd86XXXXXXX', '👅', 12, '{\"object_id\":\"5bbc4fc4d38c960007de4795\"}', '2018-10-15 08:27:04', '2018-10-15 08:27:04')
   (0.4ms)  ROLLBACK
Incorrect string value: '\xF0\x9F\x91\x85' for column 'alert' at row 1
```

The issue seems to come from the table/column encoding, which is `utf8` by default, on 3 bytes, while emojis seem to use 4 bytes.

MySQL version 5.5.3 and earlier have a `utf8mb4` which should solves the issue.

Here is a blog article summarising everything about this issue : https://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database/.

**Comment by zedtux** [comment]
You!? Bot!? Here too!? ... OMG, you're boring me so much, not my fault if authors aren't taking care of my issue !

Stop tracking me ! Uninstall yourself now!

**Comment by zedtux** [comment]
Here we go again 🤷.

Don't know which one from Rpush setup that bot but they should use that time to do some triage instead.
Whatever...

**Comment by benlangfeld** [comment]
@zedtux You are no longer welcome to participate in this project. Try learning some manners.
