### ISSUE TITLE
APNS feedback

### ISSUE THREAD

**Issue by andrewstephenson-v1** [rpush/rpush#48]
Hi,

I'm using the reflection API to remove device tokens from my database, the intention is to respond to iOS app uninstalls or users disabling push. 

However, it would appear that the method that I'm using is causing device tokens to be deleted if an APNS is not delivered regardless of the reason.

Below is the only method that I'm overriding in config/initializers/rpush.rb:

 # Called with a Rpush::Apns::Feedback instance when feedback is received
  # from the APNs that a notification has failed to be delivered.
  # Further notifications should not be sent to the device.
  on.apns_feedback do |feedback|
        d=Pushreg.find_by_devicetoken(feedback.device_token)
        [*d].each do |registrationtodelete|
                registrationtodelete.delete
                registrationtodelete.save
        end

  end

**Comment by pdaire** [comment]
@ileitch is this query incremental or it fetches always all the feedback records? Are we responsible of clearing the table once devices were removed?
