### ISSUE TITLE
Is that safe to do monkey patching for 2.7.0 Rpush::Daemon::Gcm::Delivery.do_post or const_set GCM_URI to update FCM endpoints

### ISSUE THREAD

**Issue by McGar** [rpush/rpush#483]
<img width="896" alt="screen shot 2019-02-27 at 12 53 58 pm" src="https://user-images.githubusercontent.com/1562108/53511593-c5cfae80-3a8e-11e9-91ed-6ea2e7fa2326.png">

I have to use ruby 1.9.3, so based on this commit https://github.com/rpush/rpush/commit/f6634d98daaf45c425db4d5f22694cf01034146d#diff-56c593b9b7ce3dab0bc931b94909b436 , is that OK I just override Rpush::Daemon::Gcm.Delivery.do_post with the following code

```
Rpush::Daemon::Gcm::Delivery.class_eval do
  host = 'https://fcm.googleapis.com'
  FCM_URI = URI.parse("#{host}/fcm/send")

  def do_post
    post = Net::HTTP::Post.new(FCM_URI.path, 'Content-Type'  => 'application/json',
                               'Authorization' => "key=#{@notification.app.auth_key}")
    post.body = @notification.as_json.to_json
    @http.request(FCM_URI, post)
  end
end
```

**Comment by McGar** [comment]
Another way 

```
host = 'https://fcm.googleapis.com'
Rpush::Daemon::Gcm::Delivery.const_set(:GCM_URI, URI.parse("#{host}/fcm/send"))
```

Seems it can update the endpoints, by checking it again with `Rpush::Daemon::Gcm::Delivery.const_get(:GCM_URI)`

Will test and see which way works. Just not sure if it will break anything.

**Comment by McGar** [comment]
Both solutions work, now anyone knows if there is any security issue?

**Comment by aried3r** [comment]
Hey! Glad you could solve this issue, and thanks for posting the solution as well!

I think you should be fine doing this. If however you need to support Ruby 1.9.3 I'd recommend forking rpush and applying all changes and backports of commits there instead of monkeypatching.

Closing, since this is not really an issue.
