### ISSUE TITLE
Add support/better docs for Token-Based Connection to APNS

### ISSUE THREAD

**Issue by ThomasAlxDmy** [rpush/rpush#484]
Hey there,

I don't see any documentation on support for Token-Based Connection: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns?language=objc 

Can we add it?

**Comment by aried3r** [comment]
Hey, I think this was usually referred to as "APNS p8 Certificate Authentication" in PRs and issues. It was added in version 3.2.0 https://github.com/rpush/rpush/blob/master/CHANGELOG.md#320-2018-06-13

If this is indeed what you're looking for, maybe you can add to the README and send a PR? :)
