### ISSUE TITLE
Kill RPush embed on Heroku

### ISSUE THREAD

**Issue by jacobsmith** [rpush/rpush#485]
Hello,

I currently have a very low-volume system using RPush so I'm just embedding it alongside Rails as per the Readme

```
if defined?(Rails)
  ActiveSupport.on_load(:after_initialize) do
    Rpush.embed
  end
else
  Rpush.embed
end
```

My question is if there is a way to easily "kill" Rpush - In my Heroku Release phase, I run `rails db:migrate` to ensure that migrations are always run before new code that relies on them. However, because Rpush is embedded, it doesn't ever terminate, and thus deploys "hang" for a while. I'd love for there to be something like:

`rails db:migrate && rpush --killall`

or something of the sort that would kill the embedded ruby process. Is there a way to accomplish that sort of thing already that I'm just missing? Thanks!

**Comment by aried3r** [comment]
Hey! I haven't run Rpush in embedded mode so far, but maybe you'd have luck either using a Rails runner or Rake task that calls `Rpush.shutdown`. Sorry that I can't be of further assistance, but I hope that this might help you. :)
