### ISSUE TITLE
Skip Rpush.embed if not "start server"

### ISSUE THREAD

**Issue by atebit** [rpush/rpush#488]
What's the best method to not call Rpush.embed if not on the server startup?

I was using an [initializer helpers gem](https://github.com/olegantonyan/initializer_helpers) to accomplish this, but it stopped working the way I expected..

So, rather than rely on a gem, I'd rather just write something that says:
 "if not rails s, don't do Rpush.embed"

**Comment by atebit** [comment]
Actually.. I think this does what I want. But, if I'm wrong, please let me know

```
if defined? Rails::Server
  Rpush.embed
end
```

**Comment by aried3r** [comment]
Hey! Yeah, `if defined?(Rails)` should work and suffice. See also how another user does it here: https://github.com/rpush/rpush/issues/485#issue-421636268
