### ISSUE TITLE
Is rpush compatible with Google's transition from GCM to FCM?

### ISSUE THREAD

**Issue by gregblake** [rpush/rpush#490]
I recently noticed this message on the [Google Cloud Messaging developer docs](https://developers.google.com/cloud-messaging/http-server-ref):

> As of April 10, 2018, Google has deprecated GCM. The GCM server and client APIs are deprecated and will be removed as soon as May 29, 2019. Migrate GCM apps to Firebase Cloud Messaging (FCM), which inherits the reliable and scalable GCM infrastructure, plus many new features. See the migration guide to learn more.

Are recent versions (3.0+) compatible with this change?

**Comment by drn** [comment]
Yes, rpush is already pointing to the new FCM API endpoints as of v4.0.1

You can see `https://fcm.googleapis.com/fcm/send` is being used https://github.com/rpush/rpush/blob/master/lib/rpush/daemon/gcm/delivery.rb#L8 and matches the endpoints listed in https://developers.google.com/cloud-messaging/android/android-migrate-fcm#update-server-endpoints

These changes were added in https://github.com/rpush/rpush/pull/303 and released in v4.0.1

**Comment by gregblake** [comment]
Ok, great!

It looks like #303 actually shipped a bit earlier than 4.0.1, as it was in the [3.0.0rc](https://github.com/rpush/rpush/releases/tag/v3.0.0.rc1) release. I just wanted to mention that in case other people are wondering if an upgrade is required.

I appreciate your help, @drn.

**Comment by drn** [comment]
Ah, whoops! Read the commit tag list wrong. Updated my comment 👍

**Comment by gregblake** [comment]
No worries. Thanks again.
