### ISSUE TITLE
Notifications stuck processing in batches

### ISSUE THREAD

**Issue by pennycott** [rpush/rpush#494]
Hi guys, first of all thanks for maintaining a great project.

I've had an issue in production where all push notifications get stuck at `processing`, and never get delivered. Same thing with test notifications i manually generate & run. This has happened 2 or 3 times over a period of 6 months.

It's running on Heroku, and I'm running the RPush as a foreground process on a seperate dyno [as recommended](https://github.com/rpush/rpush/wiki/Heroku), and I'm able to fix the issue by restarting the dyno. This could admittedly be a heroku issue, but I don't know what could be going wrong with such a straightforward implementation of Rpush, and why in particular it marks as processing but never completes/returns an error.

`rpush: 3.3.1`
`rails: 5.2.0`
`ruby: 2.5.1`

**Comment by bhoormeena** [comment]
I am facing similar issues -not all but some of the notifications get stuck at processing.  I am running this on dockerized app service but that should not be an issue I guess.

Technology stack
```
rpush: 4.1.1
Ruby : 2.6.2
Rails: 5.2.3
```

 Any help will be appreciated!

**Comment by drn** [comment]
Hi @piggins & @bhoormeena,

Apologies for the delay in response. I just joined this project as a maintainer, but was out of the country for the past few weeks.

Have either of you looked into memory usage of your rpush process in Heroku? From your description, it sounds like the process may be hitting Heroku memory limits - the signs of that are essentially processes that get "stuck".

If you look into your logs / Heroku metrics during these periods of inactivity, what does it look like?

If you post logs for the rpush process while notifications are "stuck", that would be helpful in debugging

**Comment by piggins** [comment]
Memory usage was my first thought too, but I check the usage graph after every incident and it was always well under the limit. I haven't yet captured the rpush process logs during an incident, I'll give that a look next time it happens, thanks.

**Comment by benlangfeld** [comment]
@mouseofleaves @bhoormeena Please evaluate if https://github.com/rpush/rpush/pull/564 (in v5.1.0) resolves this issue.

**Comment by mouseofleaves** [comment]
@benlangfeld This looks like it could be the culprit for notifications hanging in the `processing` state. I won't be able to confirm for a while because I've experienced the issue intermittently, but I'll bump rpush to v5.1.0 now.

**Comment by pennycott** [comment]
I haven't noticed the same issue in production since making the change. I think I can cautiously call this fixed.
