### ISSUE TITLE
Help maintaining rpush

### ISSUE THREAD

**Issue by drn** [rpush/rpush#495]
Hey @aried3r - my team at [Thanx](https://www.thanx.com/) is currently using rpush very heavily - we currently manage ~100 different apps (iOS & Android). We're running at scale (~60M records in the rpush_notifications table) and quickly growing.

We have a number of contributions we'd like to contribute back to the community. For example, we're using a hybrid of Redis for MQ and ActiveRecord for persistence. Another one is https://github.com/rpush/rpush/pull/491 which I opened a couple weeks ago.

Given the current delayed engagement to that initial PR, we're finding it difficult to justify pushing our extensions back to the main project. Wondering if you would be open to adding additional project maintainers to the project.

**Comment by aried3r** [comment]
Hey @drn, that's awesome to hear that this gem is being used so heavily at your company!

I'd very much appreciate some help in maintaining this gem and I'm very grateful that you're offering. Who would be in charge at your team? I'd rather avoid adding tens of people.

As for #491, I'm sorry, that one completely slipped under my radar. I'll have a look Sadly by now it has conflicts, could you maybe resolve them?

**Comment by drn** [comment]
Hey @aried3r 

Makes total sense. You can add me and I'll work with my team on porting some of our extensions to the main project.

No problem regarding #491 - I'll rebase and resolve conflicts tonight. Not sure who else is maintaining the project now, but I'll tag you in it when conflicts are resolved

**Comment by aried3r** [comment]
Quick update. @benlangfeld and @gregblake were added as maintainers. https://github.com/rpush/rpush/issues/545#issuecomment-698325248

They've been super helpful, fixing some long outstanding issues of APNS2 and I appreciate their help a lot!
