### ISSUE TITLE
What is the difference between using Apns2 or Apnsp8

### ISSUE THREAD

**Issue by michaelirey** [rpush/rpush#504]
I have googled around a bit and did not find anything to clearly explains the difference. 

Please advise :-)

**Comment by andresbravog** [comment]
AFAIK it uses the p8 certificates, that do not expire, in our experience, APNS sockets hang after a few days and starts being extremely slow when using this solution.

**Comment by jhottenstein** [comment]
Hello!

This article describes the benefit of using the token based auth (p8): https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

@andresbravog I agree that the apns http2 connections start to hang and I hope to have a solution for this soon.
