### ISSUE TITLE
[ERROR] ActiveRecord::StatementInvalid, Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: SELECT  `rpush_notifications`.`id` FROM `rpush_notifications` WHERE (processing = 0 AND delivered = 0 AND failed = 0 AND (deliver_after IS NULL OR deliver_after < ''))  ORDER BY deliver_after ASC, created_at ASC LIMIT 100 FOR UPDATE

### ISSUE THREAD

**Issue by shivkmr94** [rpush/rpush#507]
Hi guys, first of all thanks for maintaining a great project.

I am using rpush 3.3.1 for sending notification to android and IOS devices.

when I try to send Notification to devices, getting error "[ERROR] ActiveRecord::StatementInvalid, Mysql2::Error: Lock wait timeout exceeded; try restarting transaction: SELECT  `rpush_notifications`.`id` FROM `rpush_notifications` WHERE (processing = 0 AND delivered = 0 AND failed = 0 AND (deliver_after IS NULL OR deliver_after < ''))  ORDER BY deliver_after ASC, created_at ASC LIMIT 100 FOR UPDATE"

my rpush configuration file: config/initializers/rpush.rb

    Rpush.configure do |config|
      config.client = :active_record
      config.push_poll = 2
      config.batch_size = 100
      config.pid_file = 'tmp/pids/rpush.pid'
      config.log_file = 'log/rpush.log'

      config.log_level = (defined?(Rails) && Rails.logger) ? Rails.logger.level : ::Logger::Severity::INFO
    end

    Rpush.reflect do |on|
      on.notification_delivered do |notification|
      # notification.destroy
      end

      on.gcm_canonical_id do |old_id, canonical_id|
        device = DeviceInfo.find_by_device_token(old_id)
        device.device_token = canonical_id if device
        device.save! if device
      end

      on.gcm_invalid_registration_id do |app, error, registration_id|
        devices = DeviceInfo.where('device_token = ?', registration_id)
        devices.each do |device|
          if !device.uninstalled_flag
          device.uninstalled_flag = true
          device.uninstalled_at = Time.now
          device.save
        end
      end
    end

Please check and help me fixing this issue.
If you need any details please let me know.

**Comment by drn** [comment]
Hi @shivkmr94, sorry for the delayed response.

Can you confirm that your `rpush_notifications` table has the index change introduced by this PR - https://github.com/rpush/rpush/pull/428? This was released in rpush v3.1.1 - you can confirm by comparing the index or running `rpush init`. This change should reduce number of locked records

**Comment by shivkmr94** [comment]
Hi @drn, sorry for the delayed response.
My rpush version is: 3.3.1,
Yes, The index change is there in my schema.rb
