### ISSUE TITLE
Unable to deliver notification 44, received error 400 (GCM failed to parse the JSON request. Possibly an Rpush bug, please open an issue.)

### ISSUE THREAD

**Issue by jrgonh** [rpush/rpush#509]
**Describe the bug**
I cannot send GCM notifications using the example you have in the readme file.

**To Reproduce**
1. Execute the example you have in the README

**Expected behavior**
We should be able to receive the push notifications, Yesterday I was able to receive them.

**Comment by SofiaSousa** [comment]
Getting the same issue since yesterday

**Comment by SofiaSousa** [comment]
Upgrading from **rpush 2.7.0** to **3.3.1** did solve my problem.

**Comment by aried3r** [comment]
@SofiaSousa that's good to hear!

@jrgonh, which version of Rpush are you using?

**Comment by purian** [comment]
Hey @aried3r 
We have this issue on version 2.7.0 since two days ago, we can't upgrade to 3.3.1 without upgrading the entire environment.
Any advice?

Thanks


> Unable to deliver notification 3682208, received error 400 (GCM failed to parse the JSON request. Possibly an Rpush bug, please open an issue.)

**Comment by najamtariq** [comment]
hey, we are getting the same issue on version 2.7.0 and we cant upgrade to 3.x without upgrading the complete environment . Any suggestion how can we overcome this issue without upgrading the gem ?

Thanks

**Comment by SofiaSousa** [comment]
My first attempt was to upgrade to the latest version of Rpush but that was requiring to upgrade the whole environment (including ruby version). 

So I've tried 3.0.0 version first and then 3.3.1 and solved my problem.

**Comment by SofiaSousa** [comment]
Also found this https://github.com/rpush/rpush/issues/370#issuecomment-326236413 that might help you guys @purian and @aried3r understanding what is crushing.

**Comment by najamtariq** [comment]
Actually we are using ruby 1.9.3 So, upgrading is not an option for us. We are getting this error because google deprecated this end point https://gcm-http.googleapis.com

But we found a workaround i.e. upgrade the end point in lib/rpush/daemon/gcm/delivery.rb file to new endpoint like below solved our issue.

```
host = 'https://gcm-http.googleapis.com'
GCM_URI = URI.parse("#{host}/gcm/send")
```
To

```
host = "https://fcm.googleapis.com"
GCM_URI = URI.parse("#{host}/fcm/send")
```

**Comment by purian** [comment]
Thanks All.
@najamtariq - this solved our problem.

**Comment by drn** [comment]
Great to hear that a feasible workaround has been found.

In summary:
* Upgrading to latest rpush version will resolve this issue
* If not feasible, override the endpoint in `lib/rpush/daemon/gcm/delivery.rb` as @najamtariq mentioned in https://github.com/rpush/rpush/issues/509#issuecomment-519675476

Closing this out now. Thanks all!

**Comment by venriq** [comment]
Getting the same issue. We are unable to upgrade because unfortunately, the support for MongoDB was removed in version 3. We will try the hacky approach for the time being until we can get rid of this gem.

**Comment by munam-magplus** [comment]
@SofiaSousa @drn  I have update to 3.3.1 but still the issue persists.
