### ISSUE TITLE
Unable to access rails console after Embedding Rpush inside an existing process

### ISSUE THREAD

**Issue by jose2007kj** [rpush/rpush#516]
**Describe the bug**
Everything woks perfectly fine except that when i take rails console, i am getting the live rpush log so i am not able to use console after Embeddind Rpush inside an existing process as mentioned in readme

**To Reproduce**
1. added
 `if defined?(Rails)
  ActiveSupport.on_load(:after_initialize) do
    Rpush.embed
  end
else
  Rpush.embed
end`  
added this code inside config/initializer/rpush.rb
2. Run '....'
3. See error

**Expected behavior**
I wish to access the rails console without interruption from rpush logs

**System configuration (please complete the following information):**
 - OS: [ubuntu]
 - OS version: [16.04]
 - Ruby version: [e.g. 2.5.1]
 - Rails version: [5.2]
 - Rpush version: [dont know installed 2 months back]

**Additional context**
please help me to resolve this issue, i am currently using capistrano 3 to deploy to aws, how to handle this thanks

**Comment by jose2007kj** [comment]
i just found this gem  and it fixed the issue for me[capistrano-rpush](https://github.com/juicyparts/capistrano-rpush)

**Comment by drn** [comment]
Glad to hear that the https://github.com/juicyparts/capistrano-rpush project worked! Thanks for the info 👍
