### ISSUE TITLE
"Unable to deliver notification 81869, received error 400 (GCM failed to parse the JSON request. Possibly an Rpush bug, please open an issue.)"

### ISSUE THREAD

**Issue by munam-magplus** [rpush/rpush#518]
I have gone through the following threads for this error and followed the instructions properly:

https://github.com/rpush/rpush/issues/370
https://github.com/rpush/rpush/issues/509

I updated rpush to version 3.3.1 as discussed in the above threads.

Then again there was the same error as given in this thread:

https://github.com/rpush/rpush/issues/273

I was able to solve with the given solution in it i.e initialising rpush again and running migration.

Now I am able to save! the rpush notification object as given in the wiki but the error persist from both console and front end.

Ruby version -> 2.3.1
Rails version -> 4.2

I need to send the notification. The last sent was on 15th July 2019.

Update:

I am still getting the same error even after updating to latest 4.1.1 version of rpush.

**Comment by aried3r** [comment]
Hey! I sadly don't have enough time to work on this right now myself. But would you be open to explore this error in more detail?

It seems that rpush's FCM code is a bit special in the sense that we simply ignore the response in our log message.

See FCM:
https://github.com/rpush/rpush/blob/810007859d3023795e04c042a36b3f6d999c08c8/lib/rpush/daemon/gcm/delivery.rb#L113-L115

Compared with other implementations:
https://github.com/rpush/rpush/blob/master/lib/rpush/daemon/pushy/delivery.rb#L45
https://github.com/rpush/rpush/blob/master/lib/rpush/daemon/adm/delivery.rb#L60

I don't know the exact payload that [Firebase returns in this case](https://firebase.google.com/docs/cloud-messaging/http-server-ref#interpret-downstream), so I can't really tell you which field we should print in the error log.
