### ISSUE TITLE
Prepare 4.2 release

### ISSUE THREAD

**Issue by aried3r** [rpush/rpush#521]
* [x] Update changelog with all changes, merged PRs etc
* [x] Change version number
* [x] Remove extraneous migrations added in #502 
* [x] Add migrations (4_1_2? Maybe should be 4_2_0) to tests, I think they're missing there

**Comment by jhottenstein** [comment]
I can help with this!  We have a hackathon this week and I am planning to do some rpush development.  Let me know if you have other items that you want someone to work on.  I plan on focusing on redis/apns2 items.

**Comment by aried3r** [comment]
Hey, that's awesome to hear! I think other than the points mentioned in the issue I have no other plans. Well, maybe a few, but I think your work on redis/apns2 will benefit most people.
