### ISSUE TITLE
Question about the efficiency of the Redis cleanup method

### ISSUE THREAD

**Issue by sharang-d** [rpush/rpush#525]
Hey, @aried3r!

I had a question about the cleanup task posted at https://github.com/rpush/rpush/wiki/Using-Redis#important.

`redis.keys()` is O(N) and it might take a long time and also cause problems on large Redis databases so a colleague came up with this approach instead:

```ruby
# Called when a notification is successfully delivered.
on.notification_delivered do |notification|
  logger.info "Delivered notification #{notification.id}"
  Modis.with_connection do |redis|
    redis.expire(notification.key, 24.hours.to_i)
  end
end
```

A quick read tells me that it would do what the cleanup task does but immediately after a notification is delivered and in O(1) because the notification is already fetched. If that is so, isn't this approach better?

What do you think?

**Comment by jhottenstein** [comment]
Hello!

I like this idea.  We use redis and we're using the technique that was advised against (deleting right away in the `on.notification_delivered` block).  This ended up causing an issue with retries for apns failures.

Have you successfully used this yet?

**Comment by jhottenstein** [comment]
> 👋 @jhottenstein
> 
> > We use redis and we're using the technique that was advised against (deleting right away in the `on.notification_delivered` block)
> 
> Are you saying that the hook approach I've posted above is advised against? Can you point me to some link because I have most definitely missed that!
> 
> > This ended up causing an issue with retries for apns failures.
> 
> Ah! Is this Apple-only because sending the notification is [asynchronous](https://github.com/rpush/rpush/wiki/Why-open-multiple-connections-to-the-APNs%3F) and thus the `notification_delivered` is called for failed notifications as well?
> 
> > Have you successfully used this yet?
> 
> No, it's not live yet :)

**Comment by jhottenstein** [comment]
Testing with this reveals that this effectively removes the key but doesn't remove the id from the index that modis maintains (there is a set at 'rpush:notifications:all)

I think the wiki solution has the same problem as well.

**Comment by sharang-d** [comment]
We're looking into the best way to remove it but in the meantime do you have any solutions?

(We should probably also update the Wiki page)

**Comment by aried3r** [comment]
I'm not sure if this is relevant, but I found this PR in Rails that deletes multiple keys in their cache implementation.

https://github.com/rails/rails/pull/36927/files

**Comment by jhottenstein** [comment]
I have to fix this for my own application so I'll probably have something more concrete in the future.

Expire is probably the most efficient way to solve this problem but there is no reliable way to remove the item from the index at expiration.  Maybe deleting the item from the index when the expire command is good enough?  The cleanest way to do that would be to add an expire method to modis but you could fake it in your rpush callback.

**Comment by choznerol** [comment]
> > Testing with this reveals that this effectively removes the key but doesn't remove the id from the index that modis maintains (there is a set at `rpush:notifications:all`)
> > 
> > I think the wiki solution has the same problem as well.
>
> We're looking into the best way to remove it but in the meantime do you have any solutions?
> 
> (We should probably also update the Wiki page)

Regarding the `rpush:notifications:all` issue, I submitted https://github.com/rpush/rpush/issues/744 with https://github.com/rpush/rpush/pull/743, and [updated wiki](https://github.com/rpush/rpush/wiki/Using-Redis/_compare/68e999cfa9d0ed031734bde459ce3b37e4a6c38f) to mention this caveat.
