### ISSUE TITLE
Add `apns-push-type` headers to enable silent notifications on iOS 13

### ISSUE THREAD

**Issue by jsantos** [rpush/rpush#534]
It seems that from iOS 13 onwards, we need to include an additional header (`apns-push-type`) to send silent push notifications. I can confirm that currently it doesn't work. The supported values for this header are `alert` and `background`. Regular notifications are still working, so I assume it defaults to `alert`. 

Context: 
  - https://stackoverflow.com/q/57578083/1786917
- https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

Happy to start writing a PR to support this, just wanted to know what's the favorite approach here:

Should I add a new field to `Rpush::Notification` so we can specify this in case we want to send a silent notification? By default it would set the field to `alert` (which is currently the default on APNS).

**Comment by brunow** [comment]
You can do it right now with the latest version.

Here's an example of how to do it:

n = Rpush::Apns::Notification.new
n.app = ...
n.device_token = push.ios_token
n.alert = text
n.data = { 'headers': { 'apns-push-type': 'background' } } 
n.save!

**Comment by jsantos** [comment]
Thanks @brunow! Guess we can skip adding more bloat to the models then :) 

Maybe worth to include something about this on the README?

**Comment by jsantos** [comment]
Just to confirm, it works properly. Closing and will submit a PR documenting this on the README's APNS section.

**Comment by aried3r** [comment]
A PR with documentation would be awesome! Thanks for contributing, and helping out!

**Comment by jsantos** [comment]
@aried3r I've added it to the Wiki, this seemed like the appropriate section: https://github.com/rpush/rpush/wiki/Advanced-APNs-Features
