### ISSUE TITLE
Using p8 method, when renewing the APN certificate I can only export as p12

### ISSUE THREAD

**Issue by zedtux** [rpush/rpush#536]
My Rails backend uses Rpush in order to send push notifications to my mobile app, and my code uses the p8 APNs Api.

I received the email from Apple stating that my cert is about to expire. I went through the certificate creation process (made a CSR, uploaded it, and downloaded the `.cer` file from the Apple website).

After having imported the `.cer` file in the Keychain Access app, when I export it I can only export it as a `.p12` file, there is no available `.p8` format.

 - **Question 1**: Will Rpush work if I give a `.p12` file to `app.apn_key` ?
 - **Question 2**: Should I migrate my code in order to use the `Rpush::Apns::App.new` instead?
 - **Question 3**: In the `README.md` file, a `.pem` file is passed to the `Rpush::Apns::App.new` API, but I'm getting a `.cer` file from Apple. Should I rename the `.cer` file as `.pem` and it will work?

**Comment by zedtux** [comment]
Thank you very much @aried3r for your comment 👍.

I already have a `.p8` file, and when I went to the Keys page, I couldn't find any expiration date so you could be right that `.p8` files doesn't expire.

So from your point of view, using `.p8` is the way to go, and I actually have nothing todo with the expiring certificates?

**Comment by zedtux** [comment]
@aried3r could you please confirm me that the `.p8` is enough, and the expiring certificate is useless?

**Comment by aried3r** [comment]
Yes, APNs using token authentication is the way to go. The `.p8` file contains your signing key for the tokens.

See also
https://developer.apple.com/videos/play/wwdc2016/724/
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns
<img width="817" alt="Screenshot 2019-11-06 at 16 44 45" src="https://user-images.githubusercontent.com/1301152/68313657-3a92c800-00b5-11ea-9239-ce1d07be99a5.png">

**Comment by zedtux** [comment]
Thank you very much @aried3r
