### ISSUE TITLE
APNS P8 giving occasional "Connection reset by peer"

### ISSUE THREAD

**Issue by spemmons** [rpush/rpush#538]
**Describe the bug**
Seeing the following in several environments -- DEV, INTEGRATION, PROD -- with otherwise successful deliveries but occasionally the following errors and related "rpush_notifications" records show "delivered = false, failed = false":

```
[2019-11-07 03:46:56] [ERROR] Errno::ECONNRESET, Connection reset by peer
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:182:in `sysread_nonblock'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:182:in `read_nonblock'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:141:in `block in socket_loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `socket_loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:110:in `block (2 levels) in ensure_open'
```

**To Reproduce**
Not sure, it's intermittent.

**Expected behavior**
Not sure, either finally marking the record as "failed" or "delivered".

**Logs and other output**
See above.

**System configuration (please complete the following information):**
 - OS: ubuntu
 - OS version: 16.04.6 LTS
 - Ruby version: 2.6.3
 - Rails version: 5.2.2.1
 - Rpush version: 4.1.1

**Additional context**
Using APNS P8 and FCM -- only problems w/ APNS P8...

**Comment by spemmons** [comment]
I was able to get a more complete stack trace for the error:
```
[2019-11-07 17:00:08] [ERROR] Errno::ECONNRESET, Connection reset by peer
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:322:in `syswrite'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:322:in `do_write'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:339:in `block in write'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338:in `each'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338:in `inject'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:338:in `write'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:171:in `block (3 levels) in h2'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:170:in `synchronize'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:170:in `block (2 levels) in h2'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/emitter.rb:34:in `block in emit'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/emitter.rb:33:in `delete_if'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/emitter.rb:33:in `emit'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/connection.rb:390:in `block in send'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/connection.rb:390:in `each'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/connection.rb:390:in `send'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/client.rb:38:in `send'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/emitter.rb:34:in `block in emit'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/emitter.rb:33:in `delete_if'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/emitter.rb:33:in `emit'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/stream.rb:153:in `block in send'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/stream.rb:621:in `manage_state'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/stream.rb:152:in `send'
/usr/local/bundle/gems/http-2-0.10.1/lib/http/2/stream.rb:169:in `headers'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/stream.rb:86:in `send_request_data'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/stream.rb:34:in `async_call_with'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:41:in `call_async'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/apnsp8/delivery.rb:73:in `delayed_push_async'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/apnsp8/delivery.rb:65:in `prepare_async_post'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/apnsp8/delivery.rb:21:in `block in perform'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/batch.rb:22:in `each'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/batch.rb:22:in `each_notification'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/apnsp8/delivery.rb:20:in `perform'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/dispatcher/apnsp8_http2.rb:24:in `dispatch'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/dispatcher_loop.rb:66:in `dispatch'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/dispatcher_loop.rb:35:in `block (2 levels) in start'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
/usr/local/bundle/gems/rpush-4.1.1/lib/rpush/daemon/dispatcher_loop.rb:25:in `block in start'```

Curiously, I get this error for the same device token that at other times is used for successful deliveries.

**Comment by spemmons** [comment]
it is possible that our "Connection reset by peer" is the result of sending the same message to multiple valid device tokens at almost the same time. some on our team wonder if Apple is rejecting this as "inappropriate" whereas the same devices happily receive messages at other times. does anyone know if this could be true?

**Comment by spemmons** [comment]
continuing to experience this issue ... recent example: 2 issues scheduled for delivery at the same time ... when processed, both received "Connection reset by peer" result ... i resubmitted both messages manually, and both were delivered ... is there something about the simultaneous delivery of valid messages to different devices that Apple would consider "improper"?

**Comment by spemmons** [comment]
curiously, i found the following in our logs just now:

```
E, [2019-12-31T12:40:48.453819 #7] ERROR -- : [2019-12-31 12:40:48] [ERROR] Errno::ECONNRESET, Connection reset by peer
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:182:in `sysread_nonblock'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:182:in `read_nonblock'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:141:in `block in socket_loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `socket_loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:110:in `block (2 levels) in ensure_open'

[2019-12-31 12:40:48] [ERROR] Errno::ECONNRESET, Connection reset by peer
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:182:in `sysread_nonblock'
/usr/local/lib/ruby/2.6.0/openssl/buffering.rb:182:in `read_nonblock'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:141:in `block in socket_loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:138:in `socket_loop'
/usr/local/bundle/gems/net-http2-0.18.2/lib/net-http2/client.rb:110:in `block (2 levels) in ensure_open'
```
there is only one process running, so these 2 connection reset messages occurred within a few seconds of each other ... there was NOT a message being delivered at this time ... perhaps it was just a daily reset kind of thing? ... not sure if there is any significance

**Comment by CR4567** [comment]
Hi,
I have the same issue, without using P8. It started after switching from Rpush::Apns::App to Rpush::Apns2::App. But I couldn't figure out why or when exactly it happens.

Did you find out any more specific details about it?

**Comment by CR4567** [comment]
I'm still looking for a solution.
I'm using 5 different apps, connected from the same backend.
Could this be an issue?
Anyone else with problems like this?

**Comment by mobits** [comment]
Having the same issue here.

Apparently,  when it happens not only the whole notification batch is lost, but also no new notifications are sent until you restart the daemon.

I wonder if I rescue from Errno::ECONNRESET on Rpush::Daemon::Apnsp8::Delivery#perform and mark_batch_retryable would solve the problem.

The issue is that I can't find a way to reproduce the problem. It happens very rarely.

**Comment by aried3r** [comment]
Just to chime in. While I do maintain this gem, it's in a passive maintenance mode. Meaning I do not actively develop this gem anymore beyond my own needs (via PRs) and making sure it works with latest Rubies and Rails versions.

We use it in production successfully, but not with APNs, but with FCM for both iOS and Android. Thus I cannot speak for APNs functionality.

If anyone has an idea on how we could try to either catch the exception or add hooks for reporting these, PRs are welcome.

I'm sorry I cannot help beyond that point.

**Comment by CR4567** [comment]
@mobits I did try to rescue from ECONNRESET some time ago, but with no luck.
The processing flag in the database is still processing=1 but it's not retried anymore.
I didn't find a solution for this, but didn't spend much time on it, either....

Maybe I will give it another try...

**Comment by taras-viiatyk-yalantis** [comment]
@CR4567 @aried3r @mobits @spemmons 
Hi everyone!
I know it was a while ago, but at the moment I'm facing the same issue(
Has somebody found the solution/workaround for this problem?

**Comment by kjvarga** [comment]
I have a solution that is working for me.  Take a look here: https://github.com/rpush/rpush/issues/607#issuecomment-2625504651
