### ISSUE TITLE
Some notifications incorrectly marked as invalid due to payload size

### ISSUE THREAD

**Issue by gregblake** [rpush/rpush#545]
**Describe the bug**

* Some notifications incorrectly marked as invalid due to payload size.
* APNS v1 imposes a validation payload size limit of 2kb. On APNS2, the payload limit increases to 4kb.
* When using APNS2, Rpush is validating the notification payload size based on APNS v1 size limits (2kb), rather than APNS v2 size limits (4kb).

**To Reproduce**

1. Create an APNS2 notification, where the `record.payload.bytesize` is greater than 2kb, but less than 4kb.
1. The notification is not sent, because it has the [following validation error](https://github.com/rpush/rpush/blob/5405439a83b87cd9e28999795bdfb8bf71c90c51/lib/rpush/client/active_model/apns/binary_notification_validator.rb#L6-L10): "APN notification cannot be larger than 2048 bytes. Try condensing your alert and device attributes."

**Expected behavior**

The notification payload should be valid, because APNS2 imposes a notification payload size of 4kb.

**Actual Behavior**

The notification payload is marked as invalid, because the `record.payload.bytesize` is greater than 2kb (even though APNS2 has a size limit of 4kb).

**Logs and other output**

N/A

**System configuration (please complete the following information):**

 - OS: macOS 
 - OS version: 10.14.6
 - Ruby version: ruby-2.5.0
 - Rails version: Rails 5.1.6.2
 - Rpush version: Rpush 3.0.2

**Additional context**

* Here's a [Link to Apple's docs](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html) describing the payload sizes for APNS v1 and v2.

This section of the docs *might* be relevant to the issue I'm encountering:

> If you are using the legacy APNs binary interface to send notifications instead of an HTTP/2 request, the maximum payload size is 2KB (2048 bytes)

* Is it possible that I'm using the legacy APNs binary, and that's why the 2kb limit is being imposed? In that case, this may not be an Rpush bug at all, and I'd be curious how to change my Rpush config to stop using the legacy binary interface.

**Workarounds (and potential solutions)**

* I've patched my `config/initializers/rpush.rb`, to override [the `MAX_BYTES` constant](https://github.com/rpush/rpush/blob/5405439a83b87cd9e28999795bdfb8bf71c90c51/lib/rpush/client/active_model/apns/binary_notification_validator.rb#L6) so it's 4kb:
`Rpush::Client::ActiveModel::Apns::BinaryNotificationValidator::MAX_BYTES = 4.kilobytes` (obviously, I'd prefer not overriding a constant, especially one set in a gem).
* Locally, I've tested replacing [this line](https://github.com/rpush/rpush/blob/master/lib/rpush/client/active_model/apns/notification.rb#L18) with  `validates_with Rpush::Client::ActiveModel::PayloadDataSizeValidator, limit: 4096`. This change *does* seem to resolve the issue. If a PR along these lines would be appropriate, please let me know.

**Comment by aried3r** [comment]
Hey @gregblake, thanks for the detailed bug report and even potential solutions. Sadly I currently don't have time to actively maintain this gem in the sense that I actively develop it, but I rely on the community and other maintainers that volunteered to keep this gem alive. So I'd say it's in "passive maintenance mode" right now.

That being said, would you be open to open a PR with the necessary fixes that takes into account the limits of both APNs v1 and v2?

Cheers!

**Comment by benlangfeld** [comment]
@aried3r https://github.com/rpush/rpush/pull/561 should achieve exactly that.

**Comment by benlangfeld** [comment]
@aried3r If you're still looking for additional assistance in maintaining rpush, @powerhome is committed to its continued usage and can collaborate in maintainership through @gregblake and myself . To start with, we've proposed #561 and #562, and will be preparing a fix for #477 this morning.

**Comment by aried3r** [comment]
I added the two of you as maintainers, or technically speaking, you have write access, no "Maintain" access, at least for now.

I appreciate the help and from the feedback I've seen people using this rpush already appreciate the activity and PRs you are sending. Thanks!

**Comment by benlangfeld** [comment]
@aried3r Awesome, thanks. I have a few more things to propose once #561 is in, and I'll also review other outstanding PRs and do some issue triage next week.

**Comment by gregblake** [comment]
Thank you @aried3r. I will review other outstanding PRs as well.

**Comment by aried3r** [comment]
I'll need to have a closer look at this PR as well as it seems that it changes the default values for redis users. I need to dig into the history to see when it was added as I don't want to break people's code (unless we release as 6.0 and have a breaking change).

**Comment by benlangfeld** [comment]
> I'll need to have a closer look at this PR as well as it seems that it changes the default values for redis users. I need to dig into the history to see when it was added as I don't want to break people's code (unless we release as 6.0 and have a breaking change).

It aims for parity between ActiveRecord and Redis. I can split that out if it simplifies your review.
