### ISSUE TITLE
bundle exec rpush start does not init environment based on the RAILS_ENV

### ISSUE THREAD

**Issue by sadjow** [rpush/rpush#555]
**Describe the bug**
When using Rails, the command `bin/bundle exec rpush start -f` does not init the environment based on the `RAILS_ENV` environment variable. Even when the var is set to `production`. I had to explicity set the environment using `-e production` (`bin/bundle exec rpush start -e production -f`). Also, there is no documentation about it in the Wiki or README.

**Expected behavior**
I think the command should consider the RAILS_ENV variable if set. But, it should give precedence to the command line argument if present.

**Logs and other output**
If applicable, add logs, stack traces etc. to help explain your problem.

**System configuration (please complete the following information):**
 - OS: Ubuntu
 - OS version: 16.04.6 LTS
 - Ruby version: 2.5.1
 - Rails version: 6.0.0
 - Rpush version: 4.1.1

**Comment by arusa** [comment]
Thanks for the info! It just cost me at least half an hour to try to deploy my app with rpush to production because rpush always tried to load the development environment.

For Google:
Error Message was:
... method_missing': undefined method `web_console ...

**Comment by benlangfeld** [comment]
Implemented in #562 and available for review.
