### ISSUE TITLE
Remove APNSv1 support

### ISSUE THREAD

**Issue by benlangfeld** [rpush/rpush#568]
The APNS binary interface [will cease to function next month](https://developer.apple.com/news/?id=11042019a). We should remove it from rpush. I propose then renaming `APNS2` in rpush to simply `APNS` to take its place.

Any objections @aried3r ?

**Comment by aried3r** [comment]
If Apple follows through with this and doesn't extend the deadline I don't mind getting rid of unused code. This is definitely a 6.0.0 change, since it will be breaking people's code.

**Comment by benlangfeld** [comment]
@aried3r Would you want to see Apple follow through prior to the removal hitting master, or would you be willing to preempt that?

**Comment by aried3r** [comment]
Hmm, I'm not sure where I stand on this. I guess people who got the warning already migrated or will very soon. WDYT? I'd assume reverting such a commit should be easy enough unless major refactorings happen because of it.

**Comment by benlangfeld** [comment]
I'm not sure how easy a revert would be because of the interaction with APNSv2; I suspect it might not be very easy to revert. I don't see Apple canceling their intent to shut down, though, so worst case we'd just be a little bit ahead. They already strongly encourage using the HTTP2 interface anyway, so removing the binary interface from rpush would be our way of helping with that encouragement.

**Comment by aried3r** [comment]
Hmm, I'd think of it as reverting a commit, but it might involve multiple commits, so maybe reverting a merge. But you're right, I assume we can remove it in the next version. Rpush 5 should continue working and most new features/bugfixes are targeting APNS2 anyway.

**Comment by benlangfeld** [comment]
Cool. I'll prep the removal later in the week.

**Comment by aried3r** [comment]
https://developer.apple.com/news/?id=c88acm2b

> To give you additional time to prepare, the deadline to upgrade to the APNs provider API has been extended to March 31, 2021. APNs will no longer support the legacy binary protocol after this date.

**Comment by aried3r** [comment]
Seems like Apple is in fact going through with this, as per https://developer.apple.com/news/?id=uzyxiriy. So I am okay with having a 6.0.0 ready without the legacy protocol even before that date.

We _could_ cut a release with the fix for #598 before. Or is there a reason this cannot be released in a bugfix release for v5?

**Comment by aried3r** [comment]
I'm in the process of cutting a 6.0 release. If anyone wants to tackle this and maybe have a look at #601 before that I'd really appreciate it :)

I think @gregblake already reviewed #601, but if anyone wants to have another look, feel free to!

**Comment by benlangfeld** [comment]
@aried3r I'll see if I can knock this out today.
