### ISSUE TITLE
Heroku -  sslv3 alert certificate expired

### ISSUE THREAD

**Issue by tobinharris** [rpush/rpush#58]
```
 [ERROR] OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read finished A: sslv3 alert certificate expired
```

Anyone experienced this on Heroku?

**Comment by basicBrogrammer** [comment]
@ileitch There's no examples for these reflections. Are they just to raise errors or can we automate creating a new cert?

**Comment by ileitch** [comment]
They're just for observing the expiration errors. Sorry, I don't think there are any examples.
