### ISSUE TITLE
Undefined method apn_key= and apn_key for Rpush::Client::ActiveRecord::Apnsp8::App

### ISSUE THREAD

**Issue by lmhsjackson** [rpush/rpush#581]
Hi, I am using v4.2, I have to migrate my Apns:v1 cert now and I am trying to move to Apnsp8.

Following the readme I get the `NoMethodError for apn_key=` on this step:
` app.apn_key = File.read("/path/to/sandbox.p8")`

The exact error is: ```NoMethodError: undefined method `apn_key=' for #<Rpush::Client::ActiveRecord::Apnsp8::App:0x005565c2a02508>
from /home/myusername/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/activemodel-4.2.11/lib/active_model/attribute_methods.rb:433:in `method_missing' ```

I am using rails 4.2 over ubuntu 18, and any help here would be much appreciated.

**Comment by benlangfeld** [comment]
Is your DB schema correct?

**Comment by lmhsjackson** [comment]
Sadly it was not. Thanks, you may close the issue. Thank you
