### ISSUE TITLE
ruby 3.0.0

### ISSUE THREAD

**Issue by SqueezedLight** [rpush/rpush#584]
Hi guys,
first of all, thanks for the great work. This gem really is a gem ;)

I noticed that `rpush` doesn't work with ruby 3.0.0. The problem is already fixed in the underlying gems (`net-http2` and `http2`). The `net-http2` commit is here [here](https://github.com/ostinelli/net-http2/issues/44). Can we update `rpush` to the newest `net-http2` version?

Thanks!

**Comment by aried3r** [comment]
I believe we don't restrict the `net-http2` version in a way that would prevent an update to the latest version. Are you sure it's `rpush` preventing you from updating this dependency?
