### ISSUE TITLE
Support for FCM HTTP v1

### ISSUE THREAD

**Issue by CR4567** [rpush/rpush#588]
Hi,

are there plans to support the new HTTP V1 format of Google FCM?
It's google so you never know what will happen to the legacy HTTP version.

If I find some time, I will check how to integrate the authentication mechanism. 
Changing URL and message body should be the easy part.

**Comment by aried3r** [comment]
I have the same thoughts regarding Google perhaps dropping legacy FCM at some point. However I don't have the time right now to implement the new format. But we're of course happy for any PR coming our way. :)

**Comment by mirkode** [comment]
I would definitely try and help, but don't really know where to start.
I think it should be working by using `googleauth`, but I am not sure what the best way would be to pass in the secrets.json and the project_id for the new way of authentication.

As far as I can see the only part that would need to change is in the `gcm/delivery.rb` no?

Maybe do something like this?

```
def obtain_access_token
          scope = 'https://www.googleapis.com/auth/cloud-platform'

          authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
            json_key_io: File.open('path-to-authentication-file.json'), # TODO: here we would need the path to the respective file
            scope: scope)

            authorizer.fetch_access_token!
        end

        def do_post
          access_token = obtain_access_token
          post = Net::HTTP::Post.new(FCM_URI.path, 'Content-Type'  => 'application/json',
                                                   'Authorization' => "Bearer #{access_token}")
          post.body = @notification.as_json.to_json
          @http.request(FCM_URI, post)
        end
      end
```

Oh and the URI would need to be changed to something like

```
@uri = URI.parse("#{host}/v1/projects/#{@app.project_id}/messages:send")
```

**Comment by mirkode** [comment]
Because I unfortunately cannot use `rpush` anymore since I only get a `401` and cannot re-generate a legacy token anymore.

**Comment by mirkode** [comment]
Forked this gem [here](https://github.com/mirkode/rpush) and managed to get it working with FCM.

Will try and clean it up in the next couple of days, but unsure if it is good enough for a PR. At least it is working :-)

**Comment by wolak88** [comment]
@mirkode 
Are you willing to create a PR from your fork? I can put some time and clean it up.

@aried3r 
Do you have some time to review this code and show the places where it needs some work?

**Comment by aried3r** [comment]
I'm a bit short on time, but there's also other maintainers that maybe can chip in. I definitely welcome contributions, but I'd ask you to add some tests for it as well.

I'd love to discuss this in a PR. Especially how we'd handle all the new fields of the current FCM protocol. I.e. should these be database columns or "just" catch-all serialized hashes/JSON(B) columns or something else altogether.

**Comment by mirkode** [comment]
@wolak88 
Sure! There you go: [PR](https://github.com/rpush/rpush/pull/620)
I can also help, if you could instruct me a little. But that might be more complicated in the end?

Anyway, thanks for getting back to me!  

@aried3r 
Thanks for the feedback. I was also thinking about if it would make sense to store it in the `rpush_apps` database table, since there are fields for `client_id` and a (in this case) `apn_key`, but then - due to quite some time pressure on my side I was not too sure about if I should be fiddling with migrations on top so I went a rather pragmatic route.
And I also think it could definitely use some tests. :-)

**Comment by Joe-noh** [comment]
Any update on this?

**Comment by imvishi** [comment]
Please let us know if we have any updates on this?

**Comment by aried3r** [comment]
@imvishi, I left an initial review here: https://github.com/rpush/rpush/pull/620#pullrequestreview-981798891. Feel free to chime in and leave feedback. I think it's close but I want to make sure we have adequate documentation and tests.

**Comment by Ankita9818** [comment]
Any update on this??

**Comment by mobits** [comment]
We received an email from Google today stating that "starting June 20, 2024 the legacy Firebase Cloud Messaging (FCM) APIs will be discontinued".

So, we have a year to switch to HTTP v1 API.

Is there any expectation to support the newer API?

**Comment by RowanH** [comment]
Following just got the same email - have been extremely happy with RPush so definitely don't want to migrate away from it. If maintainers have got a beer donation address happy to get some beers delivered to help support updating of API's :)

**Comment by AnilRh** [comment]
In the same boat. It would be great to know that RPush is planning to support FCM beyond June 20, 2024. I'd be happy offer some beer/kombucha/frappuccino support too.

**Comment by paulcarpenter** [comment]
We would also love to see this supported. Also happy to chip in if it helps!

**Comment by mazoonit** [comment]
In the same boat, We would love to see this supported.. ready to help also!

**Comment by KevinColemanInc** [comment]
The MR to support this looks dead:

https://github.com/rpush/rpush/pull/620

I am going to move to use https://github.com/miyataka/fcmpush

**Comment by AnilRh** [comment]
We have a new MR - #660. Any help to push that forward would be appreciated.

**Comment by benlangfeld** [comment]
FCM support is now on the master branch and will soon be released, likely as 7.1.0.

**Comment by paulcarpenter** [comment]
Very exciting! Thank you!

**Comment by benlangfeld** [comment]
Support for FCM was added in 8.0.0 and support for GCM will be removed in 9.0.0, to be released soon. To migrate from GCM->FCM:

1. Upgrade to 8.x (not 9.x).
2. Switch from `Rpush::Gcm` (which Google shut down already) to `Rpush::Fcm`, using the README for guidance on the configuration you need to set.
3. Upgrade to 9.x; this version removes support for `Rpush::Gcm`.
