### ISSUE TITLE
Unable to send notification through FCM

### ISSUE THREAD

**Issue by jeremiahlukus** [rpush/rpush#592]
**Describe the bug**
FCM notifications are not being sent

**To Reproduce**
Used readme example
https://github.com/rpush/rpush#firebase-cloud-messaging

**Expected behavior**
Send a notification

**Additional context**
rails -v
Rails 6.1.3

ruby -v
ruby 2.7.2

I am able to curl `https://fcm.googleapis.com/fcm/send` and see my notification so i know my key is correct. 

```
DATA='{"notification": {"body": "this is a body","title": "this is a title"}, "priority": "high", "data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, "to": "MYDEVICETOKEN"}'
```

```
curl https://fcm.googleapis.com/fcm/send -H "Content-Type:application/json" -X POST -d "$DATA" -H "Authorization: key="MYSERVERKEY"
```

I have tried to fill out the device_id as well but still nothing is sent.

**Comment by jeremiahlukus** [comment]
Notification record

```
=> #<Rpush::Client::ActiveRecord::Gcm::Notification:0x00007fe00607dd50
 id: 7,
 badge: nil,
 device_token: "myddeviceid",
 sound: nil,
 alert: nil,
 data: "{\"message\":\"hi mom!\"}",
 expiry: 86400,
 delivered: false,
 delivered_at: nil,
 failed: false,
 failed_at: nil,
 error_code: nil,
 error_description: nil,
 deliver_after: nil,
 created_at: Thu, 25 Feb 2021 22:02:24.113087000 UTC +00:00,
 updated_at: Thu, 25 Feb 2021 22:02:24.113087000 UTC +00:00,
 alert_is_json: false,
 type: "Rpush::Client::ActiveRecord::Gcm::Notification",
 collapse_key: nil,
 delay_while_idle: false,
 registration_ids:
  ["mydeviceid"],
   app_id: 5,
 retries: 0,
 uri: nil,
 fail_after: nil,
 processing: false,
 priority: 10,
 url_args: nil,
 category: nil,
 content_available: true,
 notification: "{\"body\":\"great match!\",\"title\":\"Portugal vs. Denmark\",\"icon\":\"myicon\"}",
 mutable_content: false,
 external_device_id: nil,
 thread_id: nil,
 dry_run: false,
 sound_is_json: false>
 ```

**Comment by jeremiahlukus** [comment]
App is 

```
=> #<Rpush::Client::ActiveRecord::Gcm::App:0x00007fdffb668928
 id: 5,
 name: "firebase_ios",
 environment: nil,
 certificate: nil,
 password: nil,
 connections: 1,
 created_at: Thu, 25 Feb 2021 21:57:13.794351000 UTC +00:00,
 updated_at: Thu, 25 Feb 2021 21:57:13.794351000 UTC +00:00,
 type: "Rpush::Client::ActiveRecord::Gcm::App",
 auth_key: "MY_KEY",
 client_id: nil,
 client_secret: nil,
 access_token: nil,
 access_token_expiration: nil,
 apn_key: nil,
 apn_key_id: nil,
 team_id: nil,
 bundle_id: nil,
 feedback_enabled: true>
 ```

**Comment by Menghongli** [comment]
Hi @jeremiahlukus,

Did you solve your issue? If so, would you mind post a few comments on what was the issue and how did you fix it?

**Comment by jeremiahlukus** [comment]
In my cause I needed to do Rpush.push after its created ha. @Menghongli

**Comment by jeremiahlukus** [comment]
So I’m doing this 



`

Device.all.each do |device|
          n = Rpush::Gcm::Notification.new
          # use the pushme_droid app we previously registered in our initializer file to send the notification
          n.app = Rpush::Gcm::App.find_by_name("how-to-think")
          n.registration_ids = [device.token]
          n.data = {message: "hi mom!"}
          n.notification = {
            body: params["announcement"]["description"],
            title: params["announcement"]["title"],
            sound: "default"
          }
          n.data = {message: "hi mom!"}

          # save notification entry in the db
          n.save!
        end

        # send all notifications stored in db
        Rpush.push
        Rpush::Gcm::Notification.delete_all

`

**Comment by jeremiahlukus** [comment]
I have a table in my dB called Device which has a device ID and references user. Hopefully this helps

**Comment by Menghongli** [comment]
oh cool, thanks

I am also interested in the `click_action` part, did you get it working as well?

Does it belongs to the notification payload or the data payload?
