### ISSUE TITLE
HTTP/2‑based Apple Push Notification service

### ISSUE THREAD

**Issue by jose-airspace** [rpush/rpush#594]
Apple sent me the following today:

> The HTTP/2‑based Apple Push Notification service (APNs) provider API lets you take advantage of great features, such as authentication with a JSON Web Token, improved error messaging, and per‑notification feedback. If you still send push notifications with the legacy binary protocol, make sure to upgrade to the APNs provider API as soon as possible. APNs will no longer support the legacy binary protocol after March 31, 2021.

Is this currently available in the gem? I don't see any mention of people able to use the JSON web token. The reason I really want to use this new way though is for the improved error messaging and per-notification feedback.

Link to the docs:
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

**Comment by benlangfeld** [comment]
Yes it's available and documented: https://github.com/rpush/rpush#apple-push-notification-service

See also https://github.com/rpush/rpush/issues/568
