### ISSUE TITLE
Silent/Background notifications don't work for P8 and Apns2

### ISSUE THREAD

**Issue by shved270189** [rpush/rpush#598]
Silent/Background notification works fine for legacy Apns provider. After update to P8 or Apns2 Silent/Background notifications don't work. I checked apple documentation: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app#2980040 about background notifications APNs server requires the apns-push-type field when sending push notifications to Apple Watch, and recommends it for all platforms. Also from documentation about POST APNS requests: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns#2947607 apns-push-type header required for watchOS 6 and later; recommended for macOS, iOS, tvOS, and iPadOS.

This header is recommended for iOS, but without it Background notification does not work fine.

I added this header in this PR https://github.com/rpush/rpush/pull/596 and it helps me to fix this issue.

have anyone other ideas, solutions for this issue?

**Comment by benlangfeld** [comment]
Fix merged in #596

**Comment by benlangfeld** [comment]
Once we merge a solution to https://github.com/rpush/rpush/issues/568 we can cut v6.0.0 with this fix in it.

**Comment by aried3r** [comment]
I want to reference this comment https://github.com/rpush/rpush/pull/596#issuecomment-799454563 here since we might need to change a few things in order for this to ship in 6.0. But I'd need some help from someone who uses APNs.

**Comment by aried3r** [comment]
Hey @shved270189, @rpush/maintainers. I'd love to release v6 of rpush soon and for this I'd love to see the questions I had in #596 addressed if possible. I assume APNs would still work without these fixes, but I'd be nice if someone who actively uses APNs and maybe has a bit more insight could have a look.

Thanks!

**Comment by aried3r** [comment]
I have released a version 6.0.0 which contains the fix from #596 but I'm leaving this open for now.
