### ISSUE TITLE
Rpush::Daemon::Apnsp8::Delivery leaves notifications permanently in "processing"

### ISSUE THREAD

**Issue by diminish7** [rpush/rpush#606]
**Describe the bug**
In `Rpush::Daemon::Apnsp8::Delivery#prepare_async_post`, when `@first_push` is `false`, it calls `#delayed_push_async`, which checks for `#streams_available?` , and loops until that is `true`. `#streams_available?` checks that `#remote_max_concurrent_streams` is greater than the current stream count. But, `#remote_max_concurrent_streams` has a branch that says, if `@client.remote_settings[:settings_max_concurrent_streams] == 0x7fffffff` then return `0`. And in that scenario, `#streams_available?` is always false, and it will loop forever, leaving the batch's notifications in "processing" permanently.

**To Reproduce**
Configure rpush to use `Apnsp8`. An instance of `Rpush::Daemon::Apnsp8::Delivery` will always process the first notification of batch, set the `@first_push` flag to `false`, and then leave all other notifications in the batch in "processing"

**Expected behavior**
It should process process all notifications. Should there be a reasonable default, like 100, in the case where `settings_max_concurrent_streams` is the default value?

**System configuration (please complete the following information):**
 - OS: macOS
 - OS version: 11.2.3
 - Ruby version: 2.4.5
 - Rails version: 4.2.11
 - Rpush version: 3.2.4 (But I've verified the same code exists on master)

**Additional context**
Thanks!

**Comment by aried3r** [comment]
Hey @diminish7, thanks for the bug report! Do you think you could send a PR with these changes and a spec to verify? You seem to have a good understanding of the bug already and I'd love to see a spec that fails with the current behavior.

Although, it might not benefit you directly as the current release of Rpush does not support Rails 4.2 anymore.

**Comment by diminish7** [comment]
Hey @aried3r , yeah sure thing. I'm not sure what to do for the default max concurrent streams. In my local monkey patch, I'm using 100. Thoughts?

**Comment by aried3r** [comment]
Would it be okay if we explore this particular value in the context of the PR? Then some other maintainers that actively use APNs (I don't) can also chime in. For me, a failing test that is made green via your fix would be key, if possible. The APNs code has received many fixes in the last weeks and I'd just love to make sure we don't break anything and document faulty behavior has been corrected.

Thanks for offering to help even if you won't directly benefit from it in your Rails app, yet!

**Comment by diminish7** [comment]
@aried3r FYI: I pushed a PR (#608). Thanks!
