### ISSUE TITLE
[Request] - Metrics integration

### ISSUE THREAD

**Issue by mhenrixon** [rpush/rpush#616]
Hi,

I have a request for some guidance on how to expose metrics from RPush. I am currently in the process of exposing metrics in a project using https://github.com/discourse/prometheus_exporter. For Sidekiq, Rails and Puma there are ways of exposing metrics using that gem.

Can I achieve the same thing for RPush somehow? I am happy to supply a patch should I be able to figure it out. I still haven't looked into the code. Figured it would make sense to ask first.

**Comment by aried3r** [comment]
Hey! We're not currently exposing anything for metrics. Or rather, nothing that I am aware of.

Would you be looking to use `ActiveSupport::Notifications` for this?

**Comment by ileitch** [comment]
The reflection api can be used to export events, checkout the statsd plugin as an example: https://github.com/rpush/rpush-plugin-statsd

**Comment by mhenrixon** [comment]
> The reflection api can be used to export events, checkout the statsd plugin as an example: https://github.com/rpush/rpush-plugin-statsd

That is exactly what I was looking for @ileitch, I can use that to figure out the necessary metrics for prometheus. I also saw the https://github.com/rpush/rpush-plugin-bugsnag. I can do the same for integrating honeybadger. 

Great stuff!

**Comment by aried3r** [comment]
Completely forgot about plugins. Thanks for keeping an eye on the issues here @ileitch!

I'll be closing this issue then. :)

**Comment by maxsz** [comment]
I created a simple plugin that does just that: https://github.com/equinux/rpush-plugin-prometheus-exporter
@aried3r should we list it in the readme?

**Comment by aried3r** [comment]
Hey @maxsz! Sounds good to me. Could you send a PR? Ideally we'd list this one as a third party plugin.

**Comment by maxsz** [comment]
> Hey @maxsz! Sounds good to me. Could you send a PR? Ideally we'd list this one as a third party plugin.

Sure: https://github.com/rpush/rpush/pull/617
