### ISSUE TITLE
Rpush can't find app with id

### ISSUE THREAD

**Issue by wolak88** [rpush/rpush#621]
**Describe the bug**
In production when creating new notifications for one of the apps (iOS) I get:
```[ERROR] ActiveRecord::RecordNotFound, Couldn't find Rpush::Client::ActiveRecord::App with 'id'=3```

**Logs and other output**
```
2021-07-26 16:21:53] [fcm] Starting 1 dispatcher... ✔
[2021-07-26 16:22:47] [ERROR] ActiveRecord::RecordNotFound, Couldn't find Rpush::Client::ActiveRecord::App with 'id'=3
/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/core.rb:338:in `find'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/store/active_record.rb:22:in `app'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/app_runner.rb:25:in `start_app_with_id'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/app_runner.rb:17:in `block in enqueue'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/app_runner.rb:16:in `each'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/app_runner.rb:16:in `enqueue'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/feeder.rb:58:in `enqueue_notifications'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/feeder.rb:48:in `block in feed_forever'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/feeder.rb:47:in `loop'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/feeder.rb:47:in `feed_forever'
/bundle/ruby/3.0.0/gems/rpush-5.4.0/lib/rpush/daemon/feeder.rb:11:in `block in start'
```

**Additional context**
I'm using dockerized app with kubernetes. I have special pod for Rpush which is running in foreground. I have deleted initial iOS app that had wrong credentials, then everything started to fail. I've tried restarting the pod/recreating it but it seems that something is cached/saved in DB.

**Comment by benlangfeld** [comment]
The `rpush_notifications.app_id` column is basically a foreign key to `rpush_apps.id`. You'll need to delete all the notifications queued to deliver via that app or update the `app_id`. It would have been better to fix the existing app's credentials rather than create a new one.

Since this isn't a bug in rpush, I'm closing the issue.
