### ISSUE TITLE
Rails 7 Time.now.to_s deprecation warning

### ISSUE THREAD

**Issue by culov** [rpush/rpush#628]
Hi, thanks for this great gem! Reporting this deprecation warning I encountered when upgrading to Rails 7.

DEPRECATION WARNING: Time#to_s(:db) is deprecated. Please use Time#to_formatted_s(:db)

The warning is coming from `/lib/rpush/logger.rb` line 72:

`formatted_msg = "[#{Time.now.to_s(:db)}] "`

**Comment by gregblake** [comment]
Hey @culov, thank you for reporting this. I opened a PR to resolve the deprecation warning: https://github.com/rpush/rpush/pull/630.
