### ISSUE TITLE
How to switch from RPush APNS app to an APNS2/APNSP8 app?

### ISSUE THREAD

**Issue by talshr** [rpush/rpush#633]
(I'm sorry if this is not the right place to post this question)

I've upgraded RPush, but reading the readme, it sounds like I need to update from Rpush::APNS and to Rpush::APNS2 or RPush:APNSP8 as Rpush:APNS it will soon be deprecated [https://developer.apple.com/news/?id=c88acm2b].

The question is what's the right procedure for that. Should I just create another app and use that to send notifications?

**Comment by benlangfeld** [comment]
Yes, you just create a second app and migrate usage to it, then remove the original.
