### ISSUE TITLE
`content_available` stops sending push notification to Apple APNS silently.

### ISSUE THREAD

**Issue by sadjow** [rpush/rpush#647]
**Describe the bug**
When setting `content_available` in a rpush's `Rpush::Apns2::Notification` object. The notification is sent, but it is not displayed on the device.

**To Reproduce**
1. Create a notification object
```ruby
n = Rpush::Apns2::Notification.new
n.app = my_valid_app
n.device_token = "valid token here."
n.content_available = true
n.alert = "hi!"
n.data = {
  headers: { 'apns-topic': "valid.topic.here" },
}
n.save!
```
3. Run 'Rpush.push`
4. The notification is delivered, but no warning is displayed, and also it is not displayed.

**Expected behavior**
We need to warn that the notification should not work because the content available option is not valid anymore on APNS. 

**Logs and other output**
N/A

**System configuration (please complete the following information):**
 - Rpush version: 7.0.1

**Additional context**
N/A

**Comment by thejspr** [comment]
I think this is related to this change https://github.com/rpush/rpush/pull/596

We just got bit by it as well when upgrading.

**Comment by sadjow** [comment]
@thejspr yes, it was related to the `content_available` I had to remove it to work. I'm closing this issue.

**Comment by benlangfeld** [comment]
I'm going to leave this open as a marker for the bug introduced in #596 so that others can easily find it.
