### ISSUE TITLE
[Discussion] Consider migration to web-push fork?

### ISSUE THREAD

**Issue by sergioisidoro** [rpush/rpush#653]
Webpush gem has been stale without commits since 2020, with some dependencies (`hkdf`) pinned to 2016 versions. Furthermore it's not tested for Ruby 3.x

There seems to be a growing fork that is maintained, supports OpenSSL3 and is tested for Ruby 3.1
https://github.com/pushpad/web-push

https://github.com/zaru/webpush/issues/107

**Comment by chiraggshah** [comment]
Agree on the above.

**Comment by benlangfeld** [comment]
Done in #673.
