### ISSUE TITLE
Why Rpush do not work with iOS simulators?

### ISSUE THREAD

**Issue by Klim-Karma** [rpush/rpush#663]
> Simulator supports remote notifications in iOS 16 when running in macOS 13 on Mac computers with Apple silicon or T2 processors. Simulator supports the Apple Push Notification Service Sandbox environment. Your server can send a remote notification to your app running in that simulator by connecting to the APNS Sandbox ([api.sandbox.push.apple.com](http://api.sandbox.push.apple.com/)). Each simulator generates registration tokens unique to the combination of that simulator and the Mac hardware it’s running on. See User Notifications for more information.

I can confirm that another providers like Braze can send pushes (even silent one) to the iOS simulator on Mac with M processors.

Why don't we have this such ability with Rpush ?

**Comment by benlangfeld** [comment]
Are you appropriately selecting the sandbox environment for your Rpush app?

Can you provide code to reproduce and your rpush logs?

**Comment by Klim-Karma** [comment]
I think we've setup this properly, cuz pushes comes to real devices.
Unfortunately I can't provide the code right now.

**Comment by benlangfeld** [comment]
> I think we've setup this properly, cuz pushes come to real devices, but to simulators.

But the point is the setup is different for each case. For a simulator you need to select the sandbox environment.

**Comment by Klim-Karma** [comment]
We have to select the sandbox even for real devices with mobile builds, which are subscribed with developer certificate. So, sandbox is connected to certificate type, not to device type (real phone / simulator) - https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns#Establish-a-connection-to-APNs

**Comment by Klim-Karma** [comment]
> > I think we've setup this properly, cuz pushes come to real devices, but to simulators.
> 
> But the point is the setup is different for each case. For a simulator you need to select the sandbox environment.

We have to select the sandbox even for real devices with mobile builds, which are subscribed with developer certificate. So, sandbox is connected to certificate type, not to device type (real phone / simulator) - https://developer.apple.com/documentation/usernotifications/sending-notification-requests-to-apns#Establish-a-connection-to-APNs

**Comment by benlangfeld** [comment]
Are you trying to use the production or sandbox endpoint when sending notifications to a simulator?

**Comment by Klim-Karma** [comment]
We have 2 envs test and prod. The first one uses sandbox for sending pushes, the second one production. The certificates are setup in right way, cuz for real devices all is ok on both envs. Braze uses the same certificates as Rpush on our side, but for some reason Braze can send push to simulator, but our server not. Do you have any idea what we need to check except of certificates? Are theres any limitation on Rpush side in this?

**Comment by benlangfeld** [comment]
I need to know if you're using the sandbox endpoint to dispatch notifications to the simulator or not. That's all. Code please.

**Comment by benlangfeld** [comment]
I'm going to assume this was fixed due to the lack of responses.
