### ISSUE TITLE
Inconsistent test runs on ruby 2.7 (in CI and local test runs).

### ISSUE THREAD

**Issue by timdiggins** [rpush/rpush#677]
**Describe the bug**

CI test runs sometimes fail on ruby 2.7 (which went EOL in May 2023 https://endoflife.date/ruby).
Because of a failure to bundle install with sqlite3.

**To Reproduce**

When I try to reproduce locally (bundle install with say rails-6.0 and ruby 2.7) I do the following: (in a docker based on ruby:2.7.8)

```
export BUNDLE_GEMFILE=gemfiles/rails_6.0.gemfile
rm Gemfile.lock # see below 1)
bundle install
```

1) I get problems because of the existence of Gemfile.lock at the top of the repo (can't we delete this - is it really needed in the repo?). I could make a PR for this>

2) there are problems because the highest version of sqlite supported by  ruby 2.7 is 1.7.x (2.0 doesn't support 2.7) but 1.7.x drops the embedded sqlite3 library, so you then get whatever comes with your system. The easiest thing is to pin down the sqlite3 gem version to be lower than that. Also rails 6.0 and 6.1 seem to imply a need for ~1.4 of sqlite3. I have made a PR for this. https://github.com/rpush/rpush/pull/676

But then:

Why is it sometimes suceeding on github actions?
And why are the failures sometimes very strange?
Maybe there is a problem with the caching

**Comment by benlangfeld** [comment]
Fixed by https://github.com/rpush/rpush/pull/672
