### ISSUE TITLE
NameError: uninitialized constant Rpush::Fcm (NameError)

### ISSUE THREAD

**Issue by ghillahill** [rpush/rpush#683]
**Describe the bug**
Hello everyone, we are migrating from Gcm to Fcm after getting this error message: 

> [ERROR] Rpush::DeliveryError, Unable to deliver notification 19929, received error (Failed to deliver to all recipients. Errors: DeprecatedApi.)

But after using Rpush::Fcm::App.new we are getting en error: 

> NameError: uninitialized constant Rpush::Fcm (NameError)
>     fcm_app = Rpush::Fcm::App.new
> Did you mean?  Rpush::Gcm

**To Reproduce**
1. Snipped code of the rake task: 
```
    fcm_app = Rpush::Fcm::App.new
    fcm_app.name = "android"
    fcm_app.firebase_project_id = ENV['FIREBASE_PROJECT']
    fcm_app.json_key = ENV['RPUSH_FCM_JSON_KEY']
    fcm_app.connections = 30
    fcm_app.save!
```
2. Run the rake task
3. Get error:
> NameError: uninitialized constant Rpush::Fcm (NameError)
> 
>     fcm_app = Rpush::Fcm::App.new
>                    ^^^^^
> Did you mean?  Rpush::Gcm

**Expected behavior**
We expected to not get this error, since this Rpush::Fcm::App.new is mentioned into the README section of Rpush gem.

**Additional context**
It is quite urgent for us to address this problem because we don't have the time to re write the code using another solution.

**Comment by maciejgruszczynski** [comment]
same here.  but it seems that it is working on [this fork ](https://github.com/Inito-Team/rpush)

**Comment by ghillahill** [comment]
> same here. but it seems that it is working on [this fork ](https://github.com/Inito-Team/rpush)

It is working using Rpush::Fcm ?

**Comment by benlangfeld** [comment]
Which version of rpush are you using?

**Comment by s4herp** [comment]
Any suggestion with this issue, we are having the same problem.

**Comment by maciejgruszczynski** [comment]
> ng is wrong with my configuration. Yesterday was all working fine.

(re: fork) Rpush::Fcm foes not raise any error and i do not get 403/400 erros from the service. But i also do not have notifications sent - no idea yet if there is an issue with my local setup. firebase configuration or sth is not working in the gem.....

**Comment by maciejgruszczynski** [comment]
i think there is a bug here https://github.com/rpush/rpush/blob/4c98e1712a93b84d095188ecff1a4c9faaa11bd8/lib/rpush/daemon/fcm/delivery.rb#L152

should it return a boolean?

**Comment by benlangfeld** [comment]
I need more details of the behaviour you're seeing. Code, logs etc. I also need to know which version (commit hash) of rpush you're using.

**Comment by ghillahill** [comment]
> Which version of rpush are you using?

latest version from rpush/rpush.

As far for code the one that i posted above.

With Rpush::Gcm was working fine but now I have a problem with deprecatedApi. Using Rpush::Fcm give problems. I am not using any fork.

**Comment by benlangfeld** [comment]
Please use the master branch of this repo. The original error in this issue seems to be using the latest release, not the master branch.

**Comment by benlangfeld** [comment]
> > Which version of rpush are you using?
> 
> 
> 
> latest version from rpush/rpush.
> 
> 
> 
> As far for code the one that i posted above.
> 
> 
> 
> With Rpush::Gcm was working fine but now I have a problem with deprecatedApi. Using Rpush::Fcm give problems. I am not using any fork.

The NameError cannot be from the latest master of this repo. Please provide your Gemfile.lock.

**Comment by lluis-sancho** [comment]
Hi, 
same problem here "Unable to deliver notification 292, received error (Failed to deliver to all recipients. Errors: DeprecatedApi, DeprecatedApi"

    rpush (5.4.0)
      activesupport (>= 5.0)
      jwt (>= 1.5.6)
      multi_json (~> 1.0)
      net-http-persistent
      net-http2 (~> 0.18, >= 0.18.3)
      railties
      rainbow
      thor (>= 0.18.1, < 2.0)
      webpush (~> 1.0)

**Comment by lluis-sancho** [comment]
What about the 7.0.1, we are having exactly the same issue.

**Comment by benlangfeld** [comment]
> What about the 7.0.1, we are having exactly the same issue.

FCM support is not yet released, you have to use the master branch for now. See https://github.com/rpush/rpush/issues/665

/cc @aried3r

**Comment by ghillahill** [comment]
> > What about the 7.0.1, we are having exactly the same issue.
> 
> FCM support is not yet released, you have to use the master branch for now. See #665
> 
> /cc @aried3r

So in order to get it work we need to switch to the master branch and use Rpush::Fcm instead of Rpush::Gcm? Is that correct?

**Comment by ghillahill** [comment]
> > > Which version of rpush are you using?
> > 
> > 
> > latest version from rpush/rpush.
> > As far for code the one that i posted above.
> > With Rpush::Gcm was working fine but now I have a problem with deprecatedApi. Using Rpush::Fcm give problems. I am not using any fork.
> 
> The NameError cannot be from the latest master of this repo. Please provide your Gemfile.lock.

GIT
  remote: https://github.com/rpush/rpush.git
  revision: ef13b40096577e93334a8153205ac1cb934219be
  branch: master
  specs:
    rpush (7.0.1)
      activesupport (>= 5.2, < 7.1.0)
      googleauth
      jwt (>= 1.5.6)
      multi_json (~> 1.0)
      net-http-persistent
      net-http2 (~> 0.18, >= 0.18.3)
      railties
      rainbow
      thor (>= 0.18.1, < 2.0)
      web-push

**Comment by lluis-sancho** [comment]
> > What about the 7.0.1, we are having exactly the same issue.
> 
> FCM support is not yet released, you have to use the master branch for now. See #665
> 
> /cc @aried3r

changing to master branch: 

  remote: https://github.com/rpush/rpush.git
  revision: ef13b40096577e93334a8153205ac1cb934219be
  branch: master
  specs:
    rpush (7.0.1)
      activesupport (>= 5.2, < 7.1.0)
      googleauth
      jwt (>= 1.5.6)
      multi_json (~> 1.0)
      net-http-persistent
      net-http2 (~> 0.18, >= 0.18.3)
      railties
      rainbow
      thor (>= 0.18.1, < 2.0)
      web-push
      
Not working either.

**Comment by lluis-sancho** [comment]
Ok, 
in order to make it work i did: 

1. update the gemfile: gem 'rpush', git: "https://github.com/rpush/rpush.git", branch: 'master'
2. bundle install
3. bundle exec rpush init (ommiting rewriting) it creates a new migration
4. create a new Rpush::Fcm::App
fcm_app = Rpush::Fcm::App.new
fcm_app.name = "fcm_app"
fcm_app.firebase_project_id = "someapp-123456"
fcm_app.json_key = Rails.root.join("your/key/somewhere.json").read # or from a ENV variable - just needs to be the whole json file
fcm_app.connections = 30
fcm_app.save!
5. Send notifications : 
n = Rpush::Fcm::Notification.new
n.app = Rpush::Fcm::App.where(name: "fcm_app").first
n.device_token = device_token # Note that device_token is used here instead of registration_ids
n.data = {}.transform_values(&:to_s) # All values going in here have to be strings, if you have anything else - nothing goes through
n.save!
6. Rpush.push (if not demonized)

**Comment by benlangfeld** [comment]
> > > What about the 7.0.1, we are having exactly the same issue.
> > 
> > 
> > FCM support is not yet released, you have to use the master branch for now. See #665
> > /cc @aried3r
> 
> So in order to get it work we need to switch to the master branch and use Rpush::Fcm instead of Rpush::Gcm? Is that correct?

Correct.

**Comment by benlangfeld** [comment]
> > > What about the 7.0.1, we are having exactly the same issue.
> > 
> > 
> > FCM support is not yet released, you have to use the master branch for now. See #665
> > /cc @aried3r
> 
> changing to master branch:
> 
> remote: https://github.com/rpush/rpush.git revision: [ef13b40](https://github.com/rpush/rpush/commit/ef13b40096577e93334a8153205ac1cb934219be) branch: master specs: rpush (7.0.1) activesupport (>= 5.2, < 7.1.0) googleauth jwt (>= 1.5.6) multi_json (~> 1.0) net-http-persistent net-http2 (~> 0.18, >= 0.18.3) railties rainbow thor (>= 0.18.1, < 2.0) web-push
> 
> Not working either.

What's not working? GCM? Sure, because Google shut it down already as I said in my previous reply.

**Comment by benlangfeld** [comment]
> > > > Which version of rpush are you using?
> > > 
> > > 
> > > latest version from rpush/rpush.
> > > As far for code the one that i posted above.
> > > With Rpush::Gcm was working fine but now I have a problem with deprecatedApi. Using Rpush::Fcm give problems. I am not using any fork.
> > 
> > 
> > The NameError cannot be from the latest master of this repo. Please provide your Gemfile.lock.
> 
> ```
> GIT
>   remote: https://github.com/rpush/rpush.git
>   revision: ef13b40096577e93334a8153205ac1cb934219be
>   branch: master
>   specs:
>     rpush (7.0.1)
>       activesupport (>= 5.2, < 7.1.0)
>       googleauth
>       jwt (>= 1.5.6)
>       multi_json (~> 1.0)
>       net-http-persistent
>       net-http2 (~> 0.18, >= 0.18.3)
>       railties
>       rainbow
>       thor (>= 0.18.1, < 2.0)
>       web-push
> ```

That can't be the Gemfile.lock from when the bug was reported because that commit was from after I asked for the Gemfile.lock.

**Comment by benlangfeld** [comment]
The solution to this problem is to:

1. Upgrade to 7.1.0 when it is released. Use the latest `master` branch from this repo if you're reading this before that release happens.
2. Switch from `Rpush::Gcm` (which Google shut down already) to `Rpush::Fcm`, using the README for guidance on the configuration you need to set.

I'm locking this for comments now. If anyone correctly completes these steps and has a different problem, please open a new issue for each one, so as not to mix up multiple different problems in a single ticket.

I will leave this open until the 7.1.0 release lands and then close it.
