### ISSUE TITLE
Error with column 'type' for 'Rpush::Client::ActiveRecord::Fcm::Notification'

### ISSUE THREAD

**Issue by carlossalazar2000** [rpush/rpush#699]
**Describe the bug**
Hello, when I attempt to send a notification following the README for Rpush v 9.0.0, i receive the following error in the rpush.log:

```
ActiveRecord::SubclassNotFound, The single-table inheritance mechanism failed to locate the subclass: 'Rpush::Client::ActiveRecord::Fcm::Notification'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Rpush::Client::ActiveRecord::Notification.inheritance_column to use another column for that information.
```

**To Reproduce**
1. Following the README, I created and ran the rake task

```
    fcm_app = Rpush::Fcm::App.new
    fcm_app.name = "fcm_app"
    fcm_app.firebase_project_id = ENV['FIREBASE_PROJECT']
    fcm_app.json_key = ENV['RPUSH_FCM_JSON_KEY']
    fcm_app.connections = 30
    fcm_app.save!
```

2. I then build a notification to send

```
  n = Rpush::Fcm::Notification.new
  n.app = Rpush::Fcm::App.where(name: "fcm_app").first
  n.device_token = device_token # Note that device_token is used here instead of registration_ids
  n.data = {}.transform_values(&:to_s) # All values going in here have to be strings, if you have anything else - nothing goes through
  n.save!
```

3. I navigate to my rpush.log and i see the generated error:

```
ActiveRecord::SubclassNotFound, The single-table inheritance mechanism failed to locate the subclass: 'Rpush::Client::ActiveRecord::Fcm::Notification'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Rpush::Client::ActiveRecord::Notification.inheritance_column to use another column for that information.
```

**Expected behavior**
This should be able to build and send a notification with no issue. This was working in previous versions so I am not sure why this issue with the attribute 'type' is appearing now.

**Additional context**
If it helps, within the rpush.log where this error appears:

```
ActiveRecord::SubclassNotFound, The single-table inheritance mechanism failed to locate the subclass: 'Rpush::Client::ActiveRecord::Fcm::Notification'. This error is raised because the column 'type' is reserved for storing the class in case of inheritance. Please rename this column if you didn't intend it to be used for storing the inheritance class or overwrite Rpush::Client::ActiveRecord::Notification.inheritance_column to use another column for that information.
```

multiple logs like this appear even though I am not using rpush-7.0.1 anymore.

```
/Users/<user>/.rvm/gems/ruby-3.1.3/gems/rpush-7.0.1/lib/rpush/daemon/store/active_record/reconnectable.rb:36:in `with_database_reconnect_and_retry'
```

I prefer to continue using Rpush instead of trying another solution for FCM to send notifications but i cannot proceed past this issue.

**Comment by benlangfeld** [comment]
Given that backtraces show you are using 7.0.1, why are you so sure you are using rpush 9.0.0?

You should resolve your bundler difficulty before we move forward in handling this bug report.

**Comment by benlangfeld** [comment]
I'd need to see more complete implementation details to debug your use of bundler, but it is apparent that the version of rpush being loaded in your application is 7.0.1.

Can you perhaps reproduce the problem in a dummy application which you could push publicly to github?

**Comment by kofiasare-dev** [comment]
@carlossalazar2000 Ensure all records in your DB with references to the old 'type' i.e 'Rpush::Client::ActiveRecord::Fcm::Notification', 'Rpush::Client::ActiveRecord::Fcm::App' are deleted.

**Comment by marknuzz** [comment]
Putting this code in config/initializers/rpush.rb allowed me to not have to delete the previous notifications. Use with caution, I can't promise this will work perfectly, but it allowed me to start the server without wiping data. 

```
module ::Rpush::Client::ActiveRecord::Gcm
  class App < ::Rpush::Client::ActiveRecord::App; end
  class Notification < ::Rpush::Client::ActiveRecord::Notification; end
end
```

**Comment by benlangfeld** [comment]
The bug reported here is the inverse of what y'all are suggesting as a solution. The database contains references to FCM and the rpush dispatcher process is running an old version of rpush which can't reference FCM classes.

**Comment by benlangfeld** [comment]
A lack of further comments from the reporter leads me to suspect this was fixed already, so I'm closing this.
