### ISSUE TITLE
Unable to send FCM notification to iOS Device

### ISSUE THREAD

**Issue by randelsr-vault** [rpush/rpush#700]
**Describe the bug**
Upgraded to RPUSH 8.0.0, firing manual notifications to Android work successfully. Firing manual notification to iOS device (multiple devices) fails.

**To Reproduce**
1. Rails console
2. Run the following commands:
```
fcm_app = Rpush::Fcm::App.new
fcm_app.name = "fcm_app"
fcm_app.firebase_project_id = "correct_project_id"
fcm_app.json_key = Rails.root.join("./firebase-admin-sdk-xxx.json").read # or from a ENV variable - just needs to be the whole json file
fcm_app.connections = 30
fcm_app.save!

n = Rpush::Fcm::Notification.new
n.app = Rpush::Fcm::App.where(name: "fcm_app").first
n.device_token = "ios_device_token"
n.data = {title: "helloWorld", body: "wild"}.transform_values(&:to_s)
n.save!
```

**Expected behavior**
iOS devices should receive notification.

**Logs and other output**
Notes:
- When I attempt this using an Android device, it successfully delivers the notification
- When I attempt to use the iOS token to send a test notification in the Firebase Messaging Web UI, *it is successfully received on device* <<< this to me is the indicator that iOS notifications issues for RPUSH FCM
- RPUSH logs successful send: `INFO -- : [2024-09-16 22:42:40][fcm_app] 11 sent to ios_device_token`
- I've reviewed the diff 8.0...9.0 and don't see any updates to FCM besides removal of GCM. Ruby upgrade to 3.x is preventing updating to 9.0.0

**System configuration (please complete the following information):**
 - OS: [e.g. Ruby-2.7-alpine3.11 container]
 - Ruby version: [e.g. 2.7.0]
 - Rails version: [e.g. 6.0.0]
 - Rpush version: [e.g. 8.0.0]

**Comment by randelsr-vault** [comment]
Looks like PR was merged in with outstanding comments? https://github.com/rpush/rpush/pull/620/files#r879481880

**Comment by benlangfeld** [comment]
> Looks like PR was merged in with outstanding comments? https://github.com/rpush/rpush/pull/620/files#r879481880

That was addressed already at https://github.com/rpush/rpush/commit/840125aa568740f87e1e4a60f052748ddbe9c668#diff-6442eb03e61e6d11b126830bae34da5288b95c440ec14f88fa9d2ce11657a9a2R55

**Comment by benlangfeld** [comment]
Prior to upgrading to 8.0.0, were you using GCM to send iOS notifications? Was that working?

**Comment by randelsr-vault** [comment]
> > Looks like PR was merged in with outstanding comments? https://github.com/rpush/rpush/pull/620/files#r879481880
> 
> That was addressed already at [840125a#diff-6442eb03e61e6d11b126830bae34da5288b95c440ec14f88fa9d2ce11657a9a2R55](https://github.com/rpush/rpush/commit/840125aa568740f87e1e4a60f052748ddbe9c668#diff-6442eb03e61e6d11b126830bae34da5288b95c440ec14f88fa9d2ce11657a9a2R55)

Thank you for confirming; reviewing further this looks to also be incorporated into v8.0.0


> Prior to upgrading to 8.0.0, were you using GCM to send iOS notifications? Was that working?

It's been a while (few months) since we manually tested the E2E push notification functionality for iOS devices, but assuming yes it was working prior to September 1st 2024.

**Comment by benlangfeld** [comment]
```ruby
n.reload!
puts n.delivered
```

What do you get?

**Comment by benlangfeld** [comment]
The rpush log message you see confirms that FCM returned a 200 OK when sending the notification, so unless they can tell you what happened to it, I'm not sure how to go about trying to track this down.

**Comment by randelsr-vault** [comment]
I'll see if we can somehow increase verbosity on this / reach out to Firebase for more info. I'll be sure to keep you posted, thank you

**Comment by randelsr-vault** [comment]
Resolved. I missed the implementation detail for `FCM silent notifications` that requires `content_available` to be false in order for it to be delivered to foreground. 

```
n = Rpush::Fcm::Notification.new
n.app = Rpush::Fcm::App.where(name: "fcm_app").first
n.device_token = "ios_device_token"
n.data = {title: "helloWorld", body: "wild"}.transform_values(&:to_s)
n.content_availablel = false
n.save!
```

Thanks for your prompt help @benlangfeld
