### ISSUE TITLE
FCM does not support iOS badges

### ISSUE THREAD

**Issue by WoutDev** [rpush/rpush#703]
**Describe the ~bug~ feature**
When sending a FCM notification with a non-zero `badge` value, no such badge is sent to FCM.

Monkey patching [`Rpush::Client::ActiveModel::Fcm::Notification#apns_config`](https://github.com/rpush/rpush/blob/master/lib/rpush/client/active_model/fcm/notification.rb#L72) to include `aps['badge'] = badge if badge` seems to do the trick 'on my machine'. With the required disclaimer that my tests were quite basic.

**To Reproduce**
Send a FCM notification with a non-zero `badge` value.

**Expected behavior**
iOS would show the badge.

**Logs and other output**
N/A

**System configuration (please complete the following information):**
Rpush version: 9.0.0 on branch 20240829-rails-7.1

**Additional context**
N/A

I would be willing to contribute this in a PR, but am not very experienced with this codebase or the FCM API.

**Comment by benlangfeld** [comment]
Would you mind opening a PR at least for attribution purposes? I can provide guidance there on whatever might need to change for it to be mergeable, but broadly it would include:

* Unit test coverage
* A changelog entry
* References to FCM API documentation maybe
