### ISSUE TITLE
[ERROR] [fcm_app] Exception raised during startup. Notifications will not be delivered for this app.

### ISSUE THREAD

**Issue by jaahoo** [rpush/rpush#709]
**Describe the bug**
While sending notifications, I get an exception that kills my entire Sidekiq queue, requiring me to restart the Heroku server to resume operations until the next exception occurs.

**Expected behavior**
If an exception is raised, the queue should continue running without stopping.

**Logs and other output**
[ERROR] [fcm_app] Exception raised during startup. Notifications will not be delivered for this app.

**System configuration (please complete the following information):**
Ruby version: 3.3.4
Rails version: 7.1.3.4
Rpush version: 9.1.0
Sidekiq version: 7.1.3

**Comment by benlangfeld** [comment]
Can I please see the full logs? How are you running rpush? What does sidekiq have to do with rpush?

**Comment by jaahoo** [comment]
Sadly this is all I see
```shell
2024-10-03T16:02:13.919890+00:00 app[worker.1]: pid=2 tid=1e1q class=PushNotificationJob jid=2dcb0ee1bba2be859b31281a INFO: start
2024-10-03T16:02:13.920394+00:00 app[worker.1]: I, [2024-10-03T16:02:13.920361 #2]  INFO -- : [ActiveJob] [PushNotificationJob] [09655108-6a9f-464b-9061-aa17106a0e8e] Performing PushNotificationJob (Job ID: 09655108-6a9f-464b-9061-aa17106a0e8e) from Sidekiq(notifications) enqueued at 2024-10-01T23:00:57.305196023Z with arguments: "a21ca951-2a76-4f79-954a-d656e324105e", "fef81cf1-6759-4d78-b420-5120c10345a1"
2024-10-03T16:02:13.939971+00:00 app[worker.1]: [2024-10-03 16:02:13][ERROR] [fcm_app] Exception raised during startup. Notifications will not be delivered for this app.
```
I run rpush in job handle via sidekiq
```ruby
class PushNotificationJob < ApplicationJob
  queue_as :notifications

  def perform(notification_id, device_id)
    notification = Notification.find_by(id: notification_id)
    device = Device.find_by(id: device_id)
    data = JSON.parse(notification.data)
    if device && device.platform == 'ios'
      ###
      
      ###
    elsif device && device.platform == 'android'
      n = Rpush::Fcm::Notification.new
      n.app = Rpush::Fcm::App.where(name: "fcm_app").first
      n.device_token = device.token
      n.sound = 'default'
      n.data = data
      n.content_available = true
      n.notification = {
        title: notification.title,
        body: notification.body
      }
      n.save!
      Rpush.push
    end
  end
end
```

**Comment by benlangfeld** [comment]
Are you sure the exception itself is not logged after that? https://github.com/rpush/rpush/blob/fe0decac1dcb2ef983773e3d8ceefb91bc455093/lib/rpush/daemon/app_runner.rb#L37

Anyway, the topology you're using doesn't make a lot of sense. You are writing a job to Redis, to then pull it out, write a notification to Redis, then open an FCM connection just to pull that notification out of Redis again, send it, then shut down. This is absurdly inefficient.

Have you tried queuing your notification from your request handling thread and running rpush standalone?

**Comment by jaahoo** [comment]
Thank you for your feedback! I tried the standalone version, as you suggested, and it seems to have fixed the issue I was facing.

I appreciate your insights regarding the topology as well. I'll reconsider the architecture and explore queuing the notification directly from the request handling thread with rpush, as that does sound like a more efficient approach. Thanks again for pointing that out!
