### ISSUE TITLE
APNS Notification usage & storage

### ISSUE THREAD

**Issue by andreimarinescu** [rpush/rpush#78]
Hi everyone, first of all congrats on a very well put-together PN gem!

I've set up Rpush to work with GCM with no problems, however I'm having a few questions regarding the Apns notifications:
- in GCM I've seen that I can set a number of registration ids instead of just one. in APNS I've seen that I can only set one token per each notification object. If I'm correct, this means that if I want to send 100k notifications, I have to create 100k record in the DB (I have to save 100k Notification objects). This looks like a potential performance bottleneck to me, are there any pointers regarding how to configure this in a better way?
- I've seen in the github readme that Redis is supported as an alternative to ActiveRecord/MySQL. I didn't find any documentation in the wikis about how to configure this though. Could you provide any pointers for this as well? At the very least I think that there should be less performance issue when saving so many notification objects to redis instead of a  MySQL table.

Thanks!

**Comment by henb** [comment]
@andreimarinescu you create cleanup script?
please attach link for this
Thanks

**Comment by twobitlabs** [comment]
We're working on notification cleanup right now to keep the database from growing too large and at the moment we've created a "daily" rake task that we call via the heroku scheduler:

```
  task :daily => :environment do
    puts "Cleaning up notifications that were delivered and older than a day..."
    puts Rpush::Notification.where("delivered = ? AND delivered_at < ?", true, 1.day.ago).destroy_all.count
    puts "Done."
  end
```
