### ISSUE TITLE
Redis store slow due to YAML.dump/YAML.load

### ISSUE THREAD

**Issue by gdeglin** [rpush/rpush#90]
When using the Redis store, rpush serializes all attributes using YAML.dump when saving them into Redis, and it loads them back out using YAML.load. However, it seems like Ruby's YAML implementation is really slow.

Here's an example when working with an ```Rpush::Notification``` object (```n```):
```
Benchmark.measure { 5000.times { n.attributes.each { |k,v| YAML.dump(v) } } }.real
=> 8.672811
```

This adds up to almost 30 minutes when queueing 1M notifications, negating many of the benefits of using the Redis store in the first place.

Here's the speed when you include the time to load them back out:
```
Benchmark.measure { 5000.times { n.attributes.each { |k,v| YAML.load(YAML.dump(v)) } } }.real
=> 16.878561
```

Perhaps it would be feasible to switch this to Marshal.dump instead? Here's how much faster that would be:

```
Benchmark.measure { 5000.times { n.attributes.each { |k,v| Marshal.load(Marshal.dump(v)) } } }.real
=> 0.489435
```

JSON serialization could be another option:

```
Benchmark.measure { 5000.times { n.attributes.each { |k,v| JSON.load(v.to_json) } } }.real
=> 1.760379
```

**Comment by ileitch** [comment]
Performance in Modis `1.4.1` should be much improced.
