### ISSUE TITLE
InvalidRegistration on gcm but works

### ISSUE THREAD

**Issue by MirkoMignini** [rpush/rpush#96]
Hello,
while sending push notifications to android I always experience this error, but the push notification is delivered:

``` ruby
[2014-10-27 17:40:41] [ERROR] Rpush::DeliveryError, Unable to deliver notification 17, received error (Failed to deliver to recipients 0. Errors: InvalidRegistration.)
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:87:in `handle_failures'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:54:in `ok'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:34:in `handle_response'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/gcm/delivery.rb:21:in `perform'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher/http.rb:12:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:61:in `dispatch'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:35:in `block (2 levels) in start'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `loop'
/Library/Ruby/Gems/2.0.0/gems/rpush-2.2.0/lib/rpush/daemon/dispatcher_loop.rb:25:in `block in start'
```

I'm using the last version 2.2.0. Any ideas?
Thank you.

**Comment by priegler** [comment]
I had the same issue. 
What I did wrong was to add the registration ids inside an Array although the element itself was already an array: e.g. gcm_notification.registration_ids = [gcm_tokens_array]
So its an array inside an array with resulted in exactly the same behaviour as you described here.
Just remove the enclosing brackets and it should work correctly: gcm_notification.registration_ids = gcm_tokens_array

**Comment by MirkoMignini** [comment]
Thank you very much priegler for the tip, yes I'm using an array, I will try as soon as possible without :)

**Comment by bbonamin** [comment]
@MirkoMignini are you sure you're not sending the notification to the token `'token'`? I had the same problem because I was confused by the example, so I was assigning the registration ids as follows:
```ruby
n.registration_ids = ["token", "APA91bFG-HTUxzgIvBhW_dYSGs8i-......."]
```

so the element 0 on the array is `"token"`, but that should actually be removed and just the REAL token/tokens should be sent:
```ruby
n.registration_ids = ["APA91bFG-HTUxzgIvBhW_dYSGs8i-......."]
```

**Comment by adeelraza** [comment]
I was having the same problem but @bbonamin is right. It's just a confusion in the documentation :+1:

**Comment by MirkoMignini** [comment]
@bbonamin @adeelraza you are right, thank you very much :+1:

**Comment by boyfunky** [comment]
does registration id mean the device.uuid or the device.token?? i am confused

**Comment by pdecarcer** [comment]
Sorry I am confused How I have to send the notification here is my code
`n = Rpush::Gcm::Notification.new
n.app = Rpush::Gcm::App.find_by_name("vmobile")
n.registration_ids = ["dthVgVoxR..."]
n.data = { message: "test" }
n.save!`

In the table show as send but I never recive

Thanks

**Comment by aried3r** [comment]
@pdecarcer Try to debug using something like https://www.getpostman.com or similar to verify it's Rpush and not your client implementation that's at fault.

Once you've verified, we can better help you :)
